### ISSUE TITLE
Animefenix cloudflare

### ISSUE THREAD

**Issue by edmxn** [aniyomiorg/aniyomi-extensions#1044]
### Source information and language

Animefenix 13.11 (Español)

### Steps to reproduce

open source

### Expected behavior

load animes

### Actual behavior

failure to avoid cloudflare

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Other details

it opens in webview, the problem is when opening the extension directly
![Screenshot_20221124_094632_Aniyomi](https://user-images.githubusercontent.com/101371218/203824395-f5167415-0bd9-4321-8f58-6cd566523562.jpg)
![Screenshot_20221124_094644_Aniyomi](https://user-images.githubusercontent.com/101371218/203824413-907c64ae-ccb3-448e-b523-4863c60844c2.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
For the _Failed to bypass Cloudflare_ error, refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
