### ISSUE TITLE
Zoro.to subs

### ISSUE THREAD

**Issue by edmxn** [aniyomiorg/aniyomi-extensions#1066]
### Source information and language

zoro.to (experimental) 13.14

### Steps to reproduce

1. check on the web if an ep has the preferred subs
2. open the ep (already confirmed that the preferred subs are there)

### Expected behavior

the subs (in the preferred language, which are on the web) should load and be seen

### Actual behavior

the subs are not loaded, both in external and internal player

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Other details

Maybe it's because in the configuration of the extension there are different language names with the web (Spanish in this case)
Example: "Spanish" (in the source config) "Spanish - Spanish [LAT]" on the web

It can be checked in https://zoro.to/watch/jojos-bizarre-adventure-part-2-stardust-crusaders-uncensored-350?ep=7806

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
Subs are already implemented for extensions that supports them and you can check out beta [here](https://github.com/jmir1/aniyomi-mpv-beta/releases)

**Comment by edmxn** [comment]
> Subs are already implemented for extensions that supports them and you can check out beta [here](https://github.com/jmir1/aniyomi-mpv-beta/releases)

**Comment by edmxn** [comment]
> Subs are already implemented for extensions that supports them and you can check out beta [here](https://github.com/jmir1/aniyomi-mpv-beta/releases)



> Subs are already implemented for extensions that supports them and you can check out beta [here](https://github.com/jmir1/aniyomi-mpv-beta/re
