### ISSUE TITLE
[ru] Anilibria.TV

### ISSUE THREAD

**Issue by monolit** [aniyomiorg/aniyomi-extensions#1068]
---

## Source website
- Name: Anilibria.TV
- Link: https://www.anilibria.tv/pages/catalog.php
- Language(s): Russian

## Other details
- API: https://github.com/anilibria/docs/blob/master/api_v2.md

**Comment by ToxesFoxes** [comment]
Мне осталось буквально доделать поиск и фильтрацию, в остальном всё работает
