### ISSUE TITLE
Yugen

### ISSUE THREAD

**Issue by Divivats** [aniyomiorg/aniyomi-extensions#1112]
### Source name

yugen

### Source link

https://www.yugen.to/

### Language

English

### Other details

One of the best alternative for animixplay.
It loads videos very fast and has every anime in 1080p quality.
It would be besg for aniyomi app 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.jmir.xyz/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Solovertical** [comment]
Kamyroll will be best

**Comment by qryptonique** [comment]
Thank you! I like the clean UI, if only I could see upcoming schedules for the week, it currently says something about indexing

**Comment by rollingmoai** [comment]
@Divivats Can you rename the issue title to "Yugen" so the site name is more clearer?

**Comment by Divivats** [comment]
> @Divivats Can you rename the issue title to "Yugen" so the site name is more clearer?

Sure
