### ISSUE TITLE
Couldn't find any video link in Neko-Sama

### ISSUE THREAD

**Issue by YoCErwan** [aniyomiorg/aniyomi-extensions#1118]
### Source information and language

Neko-Sama 13.2 (French)

### Steps to reproduce

1. Open mob psycho 100 III
2. Select episode 11
3. Then the video will open and say couldn t find any video link
4. 
![Screenshot_20221227_014510_Aniyomi](https://user-images.githubusercontent.com/65460854/209591671-d545964c-acd4-4d49-9527-70bc4abc7576.jpg)

### Expected behavior

I think the latest episodes released on the site do not work on the application.

### Actual behavior

I wanted to watch the last two episodes of mob psycho 100 and I saw that the first worked but the last two did not. 

### Aniyomi version

R4515 and 0.12.3.8

### Android version

Android 13

### Other details

it's the same for many other anime in this extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closed as this issue is mostly likely not relevant. If you still have problems, please create a new issue.
