### ISSUE TITLE
Sflix extension: Subtitles don't work

### ISSUE THREAD

**Issue by i-report-bugs** [aniyomiorg/aniyomi-extensions#1136]
### Source information and language

Sflix 13.15 English

### Steps to reproduce

1. Watch any of the listings in this extension
2. Not see any subtitles

### Expected behavior

It should show the subtitles (English in this case)

### Actual behavior

It doesn't show the subtitles

### Aniyomi version

Stable 0.12.3.8

### Android version

Android 11

### Other details

The checkbox below says "I have updated the app to version 0.13.5" but it isn't available on the releases so I just checked it to be able to post this report.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This issue has been resolved in the [preview version](https://github.com/aniyomiorg/aniyomi-preview/releases/latest) of aniyomi. If the problem still persists, please create a new issue on the repo for the [main app](https://github.com/aniyomiorg/aniyomi).
