### ISSUE TITLE
[Add more extension] People need more extension to download anime

### ISSUE THREAD

**Issue by AniimeyForYou** [aniyomiorg/aniyomi-extensions#1178]
Why everytime i find a good extension to download anime it's not working or just obsolete the next week...

Any good extension for this right now ?! 🥺

First i tried animixplay (shut down one week later)
So i tried animepahe (not working anymore the next week) 
So i tried tenshi (shut down too)

Please add more Extension to download anime it's important for some people 🙏

**Comment by Secozzi** [comment]
Closed as this does not follow the format for a source request.
