### ISSUE TITLE
[Source Request] uakino.club

### ISSUE THREAD

**Issue by lv0-0vl** [aniyomiorg/aniyomi-extensions#1201]
### Source name

uakino.club

### Source link

https://uakino.club

### Language

Ukrainian

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.jmir.xyz/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by CakesTwix** [comment]
I think I can do it. I recently made a parser for UFDub
https://github.com/jmir1/aniyomi-extensions/pull/1268

**Comment by CakesTwix** [comment]
@lv0-0vl, debug
[aniyomi-uk.uakino-v13.1-debug.tar.gz](https://github.com/jmir1/aniyomi-extensions/files/10720982/aniyomi-uk.uakino-v13.1-debug.tar.gz)

**Comment by Secozzi** [comment]
Closed by #1278
