### ISSUE TITLE
Add Luminous Scans

### ISSUE THREAD

**Issue by ImpenetrableNoble** [aniyomiorg/aniyomi-extensions#1216]
### Source name

Luminous Scans 

### Source link

https://luminousscans.com/

### Language

English 

### Other details

Please add this!! thank you! 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.jmir.xyz/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheGoldenSun** [comment]
🙏🙏🙏🙏🙏

**Comment by Solovertical** [comment]
> 🙏🙏🙏🙏🙏
Aniyomi only add anime extension not manga/ manhwa go to tachiyomi GitHub( but they already removed that extension when translations group requested so it not be added again you should read this  https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md )
