### ISSUE TITLE
Fail to gather Extensions - Extensions not showing ( error in both anime and manga ) 

### ISSUE THREAD

**Issue by PNR2** [aniyomiorg/aniyomi-extensions#1226]
### Source information and language

Every extension 

### Steps to reproduce

In browser > in anime Extensions/ manga Extensions > fail to gather Extensions 
Blank black screen
 no Extensions to install 

### Expected behavior

In browser > in anime Extensions/ manga Extensions > list of Extensions to install

### Actual behavior

In browser > in anime Extensions/ manga Extensions > blank black page ( in both anime / manga Extensions) 

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Other details

I download aniyomi from different 2nd phone and share to this main phone 
 i don't even able to see extension if i download aniyomi by this main phone now i can see extension but its just stuck at downloading 

Same thing happen with me when i download aniyomi with this main phone 
I change settings in 
Setting > advanced > network > dnh : google, adgaurd, cloudflare 
( i tried all three of them dnh)
After changing dnh i was able to see extension list but when i try to install 
It just stucks at downloading s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [ ] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Pro2736** [comment]
Now I am facing the same issue

**Comment by Pro2736** [comment]
Also the extension page of the website is not working for aniyomi extensions

**Comment by Pro2736** [comment]
https://aniyomi.jmir.xyz/extensions/

See ☝️

**Comment by PNR2** [comment]
> Now I am facing the same issue

They should upload extensions on there discord server because after you get the extensions and install it individually ( not in app or by app ) 
Every works perfectly fine

**Comment by Secozzi** [comment]
This issue has been resolved in the [preview version](https://github.com/aniyomiorg/aniyomi-preview/releases/latest) of aniyomi. If the problem still persists, please create a new issue on the repo for the [main app](https://github.com/aniyomiorg/aniyomi).
