### ISSUE TITLE
Zoro Subtitles is not showing

### ISSUE THREAD

**Issue by Monkeyluffy0** [aniyomiorg/aniyomi-extensions#1240]
### Source information and language

Zoro 13.18

### Steps to reproduce

Zoro subtitles does not working

### Expected behavior

Add subtitles

### Actual behavior

Does not showing subtitles

### Aniyomi version

O.12.3.8

### Android version

Android  10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Monkeyluffy0** [comment]
Please fix this

**Comment by Secozzi** [comment]
Use [beta](http://www.github.com/jmir1/aniyomi-mpv-beta/releases/latest) to show soft subs
