### ISSUE TITLE
Gogostream server is not showing in any extension 

### ISSUE THREAD

**Issue by Animerana** [aniyomiorg/aniyomi-extensions#1261]
### Source information and language

Gogoanime 13.54

### Steps to reproduce

Gogostream server not showing in any extension 

### Expected behavior

Bring bak gogostream server 

### Actual behavior

Not showing gogostream server 

### Aniyomi version

0.13.5

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Animerana** [comment]
I am also facing the same issue

**Comment by Animerana** [comment]
Why are you not restoring gogostream servers😡😡😡😡😡😡😡😡😡😡

**Comment by Secozzi** [comment]
Closing as this issue is mostly likely not relevant. If you still have problems, please create a new issue.
