### ISSUE TITLE
Consumybili - No Audio and Subtitles

### ISSUE THREAD

**Issue by KiritoX1** [aniyomiorg/aniyomi-extensions#1292]
### Source information and language

Consumybili 13.1

### Steps to reproduce

Audio and Subtitle are missing

### Expected behavior

Should play Video normally with audio and subtitle 

### Actual behavior

Video is streaming without Audio and subtitle

### Aniyomi version

0.12.3.10

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Use [the latest beta](http://github.com/jmir1/aniyomi-mpv-beta/releases/latest) if you want audio and subtitles to work correctly

**Comment by Secozzi** [comment]
Closed as the extension has been removed.
