### ISSUE TITLE
Kickassanime 404 Error

### ISSUE THREAD

**Issue by conztanz045** [aniyomiorg/aniyomi-extensions#1317]
### Source information and language

Kickassanime 13.17

### Steps to reproduce

Open extension

### Expected behavior

Normal

### Actual behavior

Giving 404 Error

### Aniyomi version

Beta r6080

### Android version

Android 9

### Other details

There change to a new site format so maybe that why the extension broke, need new adjustment to the new format

I dont know if there change there url but its look same
![Screenshot_2023-02-22-23-19-53-90](https://user-images.githubusercontent.com/79831076/220667651-ea361640-b8ca-4021-89c5-deea752bf461.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by conztanz045** [comment]
I hope this will be fix soon please

**Comment by Secozzi** [comment]
Closed as this issue is no longer relevant, due to the changes made to the website.
