### ISSUE TITLE
Failed to get manga extension list 

### ISSUE THREAD

**Issue by NCee0283** [aniyomiorg/aniyomi-extensions#1321]
### Source information and language

"Bacakomik 1.4.4 (ID)" "failed to get extension list"

### Steps to reproduce

"Bacakomik 1.4.4 (ID)" the problem all extension manga tachiyomi on the last update (1.4.-) not work in the Aniyomi app. Please fix this

### Expected behavior

If i scroll to extension list it's any notif "failed to get extension list"

### Actual behavior

the problem all extension manga tachiyomi on the last update (1.4.-) not work in the Aniyomi app. Please fix this

### Aniyomi version

0.12.3.10-4517

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by eokwuanga** [comment]
I have encountered this same problem, I can't access any manga extensions.

**Comment by Secozzi** [comment]
This issue has been resolved in the [preview version](https://github.com/aniyomiorg/aniyomi-preview/releases/latest) of aniyomi. If the problem still persists, please create a new issue on the repo for the [main app](https://github.com/aniyomiorg/aniyomi).
