### ISSUE TITLE
[Yomiroll] Only Eng & Jap audio available

### ISSUE THREAD

**Issue by Junins** [aniyomiorg/aniyomi-extensions#1332]
### Source information and language

Yomiroll 13.16

### Expected behavior

Show all audios available

### Actual behavior

Only shows Jap & Eng audio, even though the anime has dub for other languages

### Aniyomi version

0.12.3.9

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
You have to select your preferred audio in the extension settings to load the other languages. So by default, subbed version, English dub (if available) and preferred audio (if available) are loaded
