### ISSUE TITLE
Yomiroll issue Host is unresolved beta-api.crunchyroll.com

### ISSUE THREAD

**Issue by ridoy829** [aniyomiorg/aniyomi-extensions#1337]
### Source information and language

Yomiroll 13.16

### Steps to reproduce

Open extension

### Expected behavior

Normal

### Actual behavior

Host is unresolved beta-api.crunchyroll.com

### Aniyomi version

r6129

### Android version

Android 6.0

### Other details

Once I updated consumyroll it's changed to yomiroll and showing host is unresolved. Opening web in view redirects to official crunchyroll site

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
can you update to 13.17 and try again? it will be out shortly.

**Comment by ridoy829** [comment]
> can you update to 13.17 and try again? it will be out shortly.

Just updated, it's still the same

**Comment by Samfun75** [comment]
do you have access to this site on the same device? cr-unblocker.us.to

**Comment by ridoy829** [comment]
> do you have access to this site on the same device? https://cr-unblocker.us.to

Yes

**Comment by Samfun75** [comment]
Is this issue still relevant? Please reopen if issue still persists on the latest version of app and extension.
