### ISSUE TITLE
One Pace Extension Not Working

### ISSUE THREAD

**Issue by saiyam3214** [aniyomiorg/aniyomi-extensions#1342]
### Source information and language

One Pace 13.8

### Steps to reproduce

![Screenshot_20230228_122451_Aniyomi](https://user-images.githubusercontent.com/87685722/221777290-ef143906-220f-4d83-a4b3-6dc63f517446.jpg)
 This error is showing

### Expected behavior

Idk

### Actual behavior

When i click on one pace extensions its shows the above picture

### Aniyomi version

0.12.3.9

### Android version

Android 11

### Other details

![Screenshot_20230228_122742_Aniyomi](https://user-images.githubusercontent.com/87685722/221777696-fde4a263-583f-46f4-9311-970188fd0d34.jpg)
Also when i open the url of that extension(one pace) its shows this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closed as the extension has been removed.
