### ISSUE TITLE
Extension not showing 

### ISSUE THREAD

**Issue by anjan172** [aniyomiorg/aniyomi-extensions#1371]
### Source information and language

All

### Steps to reproduce

![Screenshot_2023-03-08-11-54-44-517_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/127284078/223633849-978ea755-146d-4518-8dda-1485b9301c99.jpg)

Extension is not showing plz fix this

### Expected behavior

My extension isn't showing plz help me to fix this problem.

### Actual behavior

![Screenshot_2023-03-08-11-54-44-517_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/127284078/223634304-d6fee494-dcf7-4fd9-83b2-0bd1319bdad8.jpg)

### Aniyomi version

v0.12.3.10

### Android version

Android 9

### Other details

![Screenshot_2023-03-08-11-54-44-517_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/127284078/223634083-20872009-d490-4310-baa4-5ca173d901a4.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by RuDru-OP** [comment]
Yes bro this is a big issue cz I m not able to use Tachiyomu extensions also

**Comment by odball0** [comment]
Same bro

**Comment by Secozzi** [comment]
This issue has been resolved in the [preview version](https://github.com/aniyomiorg/aniyomi-preview/releases/latest) of aniyomi. If the problem still persists, please create a new issue on the repo for the [main app](https://github.com/aniyomiorg/aniyomi).
