### ISSUE TITLE
Downloading wrong quality 

### ISSUE THREAD

**Issue by hvroun1** [aniyomiorg/aniyomi-extensions#1385]
### Source information and language

Yomiroll v13.19 (English)

### Steps to reproduce

Trying to download on 720p unsuccessful no matter what I do.
Setting default stream quality works fine but trying to download, only downloads massive 1080p files.

### Expected behavior

It should just download 720p since it's streaming 720p.

### Actual behavior

Trying to download on 720p unsuccessful no matter what I do.
Setting default stream quality works fine but trying to download, only downloads massive 1080p files 

### Aniyomi version

Beta v6135

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
720p videos are around 700MB and 1080p videos are around 1.7GB.

**Comment by hvroun1** [comment]
@Samfun75 Then why does its metadata show 1920x1080p?
I thought I had found the perfect anime streaming extension since it categorized season into a single anime, but now looks like I'll have to find another one.

**Comment by Samfun75** [comment]
The download chooses the quality same as streaming, when you open the episode if it is playing 720p automatically then it is downloading 720p. If it is not playing 720p adjust it in extension settings. And make sure you have the latest version of the extension 13.19.

 How are you checking the metadata? do you have a screenshot.

**Comment by hvroun1** [comment]
@Samfun75  Yes i am aware. Since I've been using aniyomi for more than a year and i never stream, i only download since i have dodgy internet. Storage is also an issue thats how I was able to notice the file sizes. I checked the resolution on an external file explorer.
i stepped down the quality to 480p on extension settings and tried downloading but it was still the same.

**Comment by Samfun75** [comment]
can you confirm if it is actually not choosing 480p by playing the file and checking the quality selected by the player? the playback doesn't have to start just check which quality is at the top of the quality selection menu

**Comment by Samfun75** [comment]
Closing as preferred quality download feature has been implemented on the app
