### ISSUE TITLE
Superstream no episode since 2023

### ISSUE THREAD

**Issue by hvroun1** [aniyomiorg/aniyomi-extensions#1400]
### Source information and language

Superstream v13.8 (English)

### Steps to reproduce

No new episodes since late last year. It shows the list for episodes and movies but when trying to watch or download it says entry list is empty.

### Expected behavior

It should just play.

### Actual behavior

It fails to stream or download.

### Aniyomi version

Beta r6135

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Superstream's servers are notorious for having problems. Closing as I'm unable to replicate this, and it being a very high chance of being a source issue, not an extension issue.
