### ISSUE TITLE
No descarga las extensiones de manga

### ISSUE THREAD

**Issue by Sara9806** [aniyomiorg/aniyomi-extensions#1427]
### Source information and language

Extensiones de manga 

### Steps to reproduce

Abro la app 
Explorar 
Manga extensions 
No se pudo descargar el listado de extensiones 

### Expected behavior

Se que de vería a ver una lista de extensiones para descargar y poder ver manga

### Actual behavior

![Screenshot_2023-03-20_121419](https://user-images.githubusercontent.com/128414214/226432277-fa70d62f-e431-4a26-9e16-592a86aa7315.jpg)

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Download the [beta](http://github.com/jmir1/aniyomi-mpv-beta/releases/latest) version of aniyomi to fix your problem
