### ISSUE TITLE
Share/webview aren't working on Animepahe

### ISSUE THREAD

**Issue by Fuuk1** [aniyomiorg/aniyomi-extensions#1478]
### Source information and language

AnimePahe 13.24 (English)

### Steps to reproduce

Open any random animepahe entry in library
Refresh the entry so it refreshes with new link of the entry
Click on webview or share in overflow menu

### Expected behavior

It should show webview page or have share popup

### Actual behavior

Webview or share don't work.

### Aniyomi version

MPV Beta r6145

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Fixed by #1531
