### ISSUE TITLE
SoraStream lite Sorastream stremioX 

### ISSUE THREAD

**Issue by Doctor2023** [aniyomiorg/aniyomi-extensions#1485]
### Source name

SoraStream lite Sorastream stremioX 

### Source link

SoraStream lite Sorastream stremioX 

### Language

English 

### Other details

Thanks you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
SoraStream is a Cloudstream extension that scrapes from multiple sites, and uses tmdb as cataloging. SoraStream will not made made into an Aniyomi extension, but someone could make an extension that scrapes the same sites as SoraStream, effectively making it a clone.
