### ISSUE TITLE
zoro.to extension does not have subtitles

### ISSUE THREAD

**Issue by Keno417** [aniyomiorg/aniyomi-extensions#149]
## Device information
- Tachiyomi version: 0.12.3.2
- Android version: 10

## Source information
- Name: Kaith
- Extension version: zoro.to

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
to make the selection of video quality in the extension settings so that the viewers can easily watch the anime because they set automatically the video resolution

### Actual behavior
to have subtitles on zoro.to extension,

**Comment by tharn0029** [comment]
Yes please 🙏 fix it
