### ISSUE TITLE
Source requests 🇪🇦

### ISSUE THREAD

**Issue by Credits125** [aniyomiorg/aniyomi-extensions#1500]
### Source name

Series, movies, anime

### Source link

https://playhublite.com/

### Language

Spanish 

### Other details

https://hdfull.org/ "series, movies"
https://cinehdplus.org/ "serie, movies"
https://www.iq.com/?lang=es_mx "asian dramas"
https://hdfull.club/ "series, movies"
https://animeblix.com/ "anime"
https://nextdede.com/ "series, movies, anime"
https://playhublite.com/ "series, movies, anime"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closing as multiple source requests were made. Please make a separate issue for each extension.
