### ISSUE TITLE
Türk Anime: No results found for existing anime

### ISSUE THREAD

**Issue by kyoyacchi** [aniyomiorg/aniyomi-extensions#1553]
### Source information and language

Türk Anime TV: 13.2 - Turkish

### Steps to reproduce

1. Install Türk Anime TV
2. Open the extension
3. Try searching "Mashle"

### Expected behavior

It should show results for "Mashle" it exists on the website.

### Actual behavior

It doesn't show "Mashle" and some other anime.(Like, Otonari no Ginga) even tho they're in the website.
![Screenshot_20230429-181826](https://user-images.githubusercontent.com/63583961/235310258-0f433a1e-e84f-474a-b7cf-938d1eecf0d9.jpg)

![Screenshot_20230429-181930](https://user-images.githubusercontent.com/63583961/235310305-5ded05f5-013d-4254-b4a8-6e655af29cb4.jpg)
(Ep 4 of Mashle)

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by toprak** [comment]
still no updates?

**Comment by mamiyaso** [comment]
mashl yazınca çıkıyor

**Comment by kyoyacchi** [comment]
Son eklenti güncellemesiyle birlikte çözülmüş gibi görünüyor.

It seems like it has been fixed with the latest extension update.

**Comment by kyoyacchi** [comment]
@toprak Sizde de düzeldi mi efenim?

**Comment by toprak** [comment]
@kyoyacchi aynen duzelmis pinglemesen farketmeyecektim :D
