### ISSUE TITLE
Super stream preferred domain fix

### ISSUE THREAD

**Issue by binyaminyblatt** [aniyomiorg/aniyomi-extensions#1567]
### Source information and language

Superstream

### Steps to reproduce

If you click on me option to choose your preferred domain it should give you a list of domains to use there's only one option

### Expected behavior

From reading the code I know that there's at least three domains to choose from which should allow me to choose a domain in the preferred domain box

### Actual behavior

There's only one option

### Aniyomi version

App version: 0.14.3-6147

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
From the 3 domains you mentioned, one doesn't work completely and it's not used and the other only works for search and detail fetch and is used to reduce load to the main server. Closing as this won't be implemented.
