### ISSUE TITLE
Ozulscans.com 

### ISSUE THREAD

**Issue by slimessan** [aniyomiorg/aniyomi-extensions#1578]
### Source information and language

Arabic

### Source new URL

Ozulscans.net

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Manga extensions are managed by tachiyomi, not aniyomi. However, there already exists an issue for [Ozulscans](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16282), so no need to open another request
