### ISSUE TITLE
[Error getting links] <all sources available>:<error getting links whenever i start any episode>

### ISSUE THREAD

**Issue by MooseZM** [aniyomiorg/aniyomi-extensions#161]
**PLEASE READ THIS**

I acknowledge that:

- I have updated:
  - To the latest version of the app (stable is v0.10.12)
  - All extensions
- I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/
- If this is an issue with the app itself, that I should be opening an issue in https://github.com/jmir1/aniyomi
- I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another open issue
- For source requests, I have checked the list of existing extensions including the multi-source spreadsheet: https://tachiyomi.org/extensions
- 
## Device information
-aniyomi version 1.5.3.4
- Android version: 11

## Source information
- Name: all of them
- Extension version: latest

## Steps to reproduce
1. Just starting a new episode

### Expected behavior
the episode plays

### Actual behavior
I get error getting links

**Comment by jplie** [comment]
I also have this error with any sources

**Comment by Samfun75** [comment]
Closing as this issue is not applicable on latest [Preview](https://github.com/aniyomiorg/aniyomi-preview/releases/latest) version.
