### ISSUE TITLE
Animeonline360

### ISSUE THREAD

**Issue by Delmarcop52** [aniyomiorg/aniyomi-extensions#1610]
### Source information and language

Animeonline360 13.1

### Steps to reproduce

I was to restart the app 

### Expected behavior

The all movies played right one

### Actual behavior

When I was trying to watch movies it keeps playing the another movie 

### Aniyomi version

Aniyomi App version: 0.14.3-6147 

### Android version

Motorola 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closing as this issue was resolved on discord. The problem was that the website was displaying the wrong movie, but that's a website issue which has nothing to do with Aniyomi.
