### ISSUE TITLE
Anime-Sama request

### ISSUE THREAD

**Issue by Urbexed** [aniyomiorg/aniyomi-extensions#1633]
### Source name

Anime-Sama

### Source link

anime-sama.fr

### Language

French

### Other details

They publish the anime in VF for those who have it and in vostfr too 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Kreliam** [comment]
@Urbexed tien je te trouve aussi dans Aniyomi 😁

il faudrait que tu change le Language en French s'il te plaît .

**Comment by Urbexed** [comment]
> @Urbexed tien je te trouve aussi dans Aniyomi 😁
> 
> il faudrait que tu change le Language en French s'il te plaît .

Oui hahaha et ok je le fait

**Comment by Kreliam** [comment]
> > @Urbexed tien je te trouve aussi dans Aniyomi 😁
> > il faudrait que tu change le Language en French s'il te plaît .
> 
> Oui hahaha et ok je le fait
> 
> Édit : c'est fait

Merci beaucoup l'amis  👍

**Comment by jmir1** [comment]
> @Urbexed tien je te trouve aussi dans Aniyomi grin
> 
> il faudrait que tu change le Language en French s'il te plaît .

Je crois que tout le monde peut comprendre le mot "Français" :joy: 
@Urbexed C'est une bonne site, je vais essayer de l'ajouter

**Comment by Kreliam** [comment]
> > @Urbexed tien je te trouve aussi dans Aniyomi grin
> 
> > 
> 
> > il faudrait que tu change le Language en French s'il te plaît .
> 
> 
> 
> Je crois que tout le monde peut comprendre le mot "Français" :joy: 
> 
> @Urbexed C'est une bonne site, je vais essayer de l'ajouter

Juste dans l'éventualité que le dev comprenne tout l'information sur le poste

**Comment by Urbexed** [comment]
> > > @Urbexed tien je te trouve aussi dans Aniyomi grin
> > 
> > 
> > > 
> > 
> > 
> > > il faudrait que tu change le Language en French s'il te plaît .
> > 
> > 
> > Je crois que tout le monde peut comprendre le mot "Français" 😂
> > @Urbexed C'est une bonne site, je vais essayer de l'ajouter
> 
> Juste dans l'éventualité que le dev comprenne tout l'information sur le poste.
> 
> Merci beaucoup pour avoir ajouté anima sama à l'application tu gère 😉

Il a dis qu'il allait essayer, pas qu'il l'avais fait

**Comment by Kreliam** [comment]
@Urbexed
