### ISSUE TITLE
"null" error on Comick extension

### ISSUE THREAD

**Issue by Karperlius** [aniyomiorg/aniyomi-extensions#1650]
### Source information and language

Comick

### Steps to reproduce

just refresh any manga on Comick extension

### Expected behavior

work fine just like the other extension

### Actual behavior

the error display doesn't show anything but with black border without text but the error log show "null" 

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Other details

! null
  # Comick (EN)

(The error detail)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closing as I'm unable to replicate this, and has most likely been fixed already. If you still have problems, please include the version of the extension and an example of a manga that gives the erorr
