### ISSUE TITLE
[BUG]The Comick extension is very slow in Aniyomi

### ISSUE THREAD

**Issue by breaking-loss** [aniyomiorg/aniyomi-extensions#1675]
### Source information and language

1.4.26

### Steps to reproduce

The slowness (takes 20-25 seconds to load) can be observed when you disable all languages apart from English and try to open the source and when you search for manga or when you trying to migrate one .

1. Go to manga extensions
2. Select comick
3. Disable all languages apart from English
4. Go to manga source and open comick
Or
4. Migrate a manga
Or
4. Search for a manga

### Expected behavior

When you do any of the above the display of manga should be loaded instantly . It should only take like 1-3 seconds in theory . The above works when I try repeat the same steps in Tachiyomi-priview and Tachij2K .

### Actual behavior

In Aniyomi the mangas are not loaded for a good 20-30 seconds . I have confirmed this by only searching through comick by pinning and enabling search only pinned sources. 

### Aniyomi version

Beta r6150

### Android version

Android 13

### Other details

This issue is not observed on Tachiyomi or Tachij2k . 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by breaking-loss** [comment]
Can anyone also know how comick changes the mangas title when you search for them . Can it be reproduced artificially ? I would like to convert all my non English title mangas to English ones . ( It worked for martial peak and jujutsu kaisen (from peak of martial arts to martial peak and magical fights to jujutsu kaisen). But it didn't work for Yuusha Party o Oida Sareta Kiyou Binbou ( it reverted from The Jack-of-all-trades Kicked Out of the Hero’s Party ~ The Swordsman Who Became a Support Mage Due to Party Circumstances, Becomes All Powerful to Yuusha Party o Oida Sareta Kiyou Binbou)

**Comment by Secozzi** [comment]
Closed as this issue has nothing to do with Aniyomi extensions. If the issue still persists, please open a new issue in the repo for the main app.
