### ISSUE TITLE
GoogleDrive extension don't save url for the drives path

### ISSUE THREAD

**Issue by PHBN2021** [aniyomiorg/aniyomi-extensions#1679]
### Source information and language

Google Drive 13.4

### Steps to reproduce

1.Enter Configurations of Google Drive Extension
2.Paste url of the drive folder you desire
3. Press Ok

### Expected behavior

The url path should be saved to access the folder through the extension

### Actual behavior

The url is not saved and the extension is blank without the folders

### Aniyomi version

12.3.10

### Android version

Android 12 S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
The extension doesn't work for the stable version of Aniyomi, consider using [preview](https://github.com/jmir1/aniyomi-preview/releases/tag/r6150)

**Comment by Secozzi** [comment]
Fixed by #1716
