### ISSUE TITLE
Gogoanime extension not downloading episodes

### ISSUE THREAD

**Issue by Clutchess** [aniyomiorg/aniyomi-extensions#1681]
### Source information and language

Gogoanime 13.64

### Steps to reproduce

 Start downloading episodes
Doesn't download, give notification of finished downloading but doesn't download and just pauses it

### Expected behavior

Should download

### Actual behavior

Isn't downloading

### Aniyomi version

0.12.3.10

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Cistmist** [comment]
Yup same. The extension prioritizes Doodstream for some reason even if you had chosen other preferred servers.

And if you disable Doodstream to try to get around that issue. You only get Download Errors.

The extension used to automatically choose a close enough quality to the one you selected in case the chosen quality doesn't exist for download. (Ex: if you chose to download 360p and that quality doesn't exist, it would choose the 480p from the same server).

**Comment by Clutchess** [comment]
the same issue has started again since last night, please fix it. It is happening every other day now, and its annoying as hell.

**Comment by Secozzi** [comment]
This issue has been resolved in the [preview version](https://github.com/aniyomiorg/aniyomi-preview/releases/latest) of aniyomi. If the problem still persists, please create a new issue on the repo for the [main app](https://github.com/aniyomiorg/aniyomi).
