### ISSUE TITLE
Gogo anime 

### ISSUE THREAD

**Issue by akumarsmapp** [aniyomiorg/aniyomi-extensions#1696]
### Source information and language

English 

### Source new URL

https://www3.gogoanimes.fi/

### Other details

Gogo anime website is not working 😭😭
But gogo anime change connection reset

But gogo anime create website is gogoanime.fl new website
Please aniyomi staff and create see this problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by akumarsmapp** [comment]
Gogo anime change website is gogoanime.cl/ connection reset 
But gogo anime create website https://www3.gogoanimes.fi/ and this new website create gogo anime
Please request 🥺🙏 for aniyomi staff and create see this problem

**Comment by Secozzi** [comment]
Will be fixed by #1693
