### ISSUE TITLE
[Source Request] -- <JetAnime>

### ISSUE THREAD

**Issue by Kreliam** [aniyomiorg/aniyomi-extensions#1705]
### Source name

JetAnime

### Source link

https://ssl.jetanimes.com/

### Language

French

### Other details

please notify me if the site does not work so that I can change the link

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Fred-Vatin** [comment]
Thanks. But fail to fetch video for this source when start playing an episode (any anime)
