### ISSUE TITLE
Yomiroll, video playback problem

### ISSUE THREAD

**Issue by Gtbita** [aniyomiorg/aniyomi-extensions#1720]
### Source information and language

Yomiroll 13.24 (All)

### Steps to reproduce

I select an anime from the library and try to play the episodes, apparently only the first three episodes are played.

### Expected behavior

All episodes should play normally.

### Actual behavior

Only episodes 1, 2 and 3 play.

### Aniyomi version

Beta r6412

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by josefredohd** [comment]
I have the same problem, please fix the error

**Comment by toomyzoom** [comment]
The response with yomiroll token doesn't return "streams_link" field

cc @Samfun75

**Comment by Samfun75** [comment]
Well i guess the account stopped being premium again...

**Comment by venkat2305** [comment]
I can play some videos and mostly the videos couldn't be played. For example , the first 3 episodes of mashle can be played but the remaining episodes of that anime cannot be played , the link couldn't be fetched

**Comment by Lukyzzz** [comment]
👀

**Comment by Blokheck011** [comment]
Also having this problem, it seems like downloading doesn't work no matter what episode you try.

**Comment by Samfun75** [comment]
Token is updated to premium and extension is working fine again. Closing.
