### ISSUE TITLE
Wrong domain on Toonitalia

### ISSUE THREAD

**Issue by GioAltoni** [aniyomiorg/aniyomi-extensions#1729]
### Source information and language

Toonitalia 13.8 (ITA)

### Source new URL

https://toonitalia.xyz/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closing in favor of #2052
