### ISSUE TITLE
Add Source RedeCanais

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi-extensions#1735]
### Source name

REDE Canais

### Source link

https://redecanais.la

### Language

Portuguese

### Other details

It's not dead, try to use VPN
![Screenshot_20230616-114957](https://github.com/aniyomiorg/aniyomi-extensions/assets/102862985/07977ddc-7abe-4a16-9276-617a77f4bdd7)
![Screenshot_20230616-114945](https://github.com/aniyomiorg/aniyomi-extensions/assets/102862985/97b1f5f7-f6ef-44b4-abf5-b7f39f1e412c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Oh, my mistake
