### ISSUE TITLE
[GDrive]No video

### ISSUE THREAD

**Issue by BlanXyz** [aniyomiorg/aniyomi-extensions#1760]
### Source information and language

Google Drive 13.5

### Steps to reproduce

1) Open video in GDrive Extension

### Expected behavior

Video Plays

### Actual behavior

Audio Only, No video output.

### Aniyomi version

Preview: 0.14.3-6151 

### Android version

10 | Huawei P30 Pro

### Other details

I have attached the Verbose log of:
1)Opening Gdrive Extension
2)Opening title (folder)
3)Opening video
[googleDriveExtSW.log](https://github.com/aniyomiorg/aniyomi-extensions/files/11782386/googleDriveExtSW.log)

Additional notes:

> Video occasionally flashes on Screen upon initial playback/resume.

> SW decoding is enabled

> Toggling Stats in player menu, fixes video output as long as the menu is left open. Breaks again when menu is closed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Since the audio plays, that means that the extension still works fine. Because it's not an extension issue, you should open up an issue on the repo for [the app](https://github.com/aniyomiorg/aniyomi). I would recommend downloading mpv from play store then open it up as an external player, because it could potentially provide info on whether or not its an issue with mpv or Aniyomi.
