### ISSUE TITLE
Global Update Lateinit property title not initialized

### ISSUE THREAD

**Issue by thiccguy21** [aniyomiorg/aniyomi-extensions#1762]
### Source information and language

AllAnime 13.22

### Steps to reproduce

1. Have an anime in library from Allanime (EN)
2. Click Global Update button
3. All updates failed in notification 
4. Showing lateinit property title has not been initialized

### Expected behavior

It should successfully update all anime in the library

### Actual behavior

Instead showed an error not being able to update it

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Other details

https://github.com/aniyomiorg/aniyomi-extensions/assets/121115775/980d87bb-738f-4ee8-abaf-86eb817e5f10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This issue has been resolved in the [preview version](https://github.com/aniyomiorg/aniyomi-preview/releases/latest) of aniyomi. If the problem still persists, please create a new issue.
