### ISSUE TITLE
[Source Request] -- <KDramaVostfr>

### ISSUE THREAD

**Issue by Kreliam** [aniyomiorg/aniyomi-extensions#1771]
### Source name

KDramaVostfr

### Source link

https://kdramavostfr.com/

### Language

French

### Other details

please notify me if the site does not work so that I can change the link

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by hollowshiroyuki** [comment]
Looks like a mirror or alternative domain of #1772
It has a different IP but the domain in the about is mykdrama, https://kdramavostfr.com/dmca/

**Comment by Kreliam** [comment]
> Looks like a mirror or alternative domain of #1772
> 
> It has a different IP but the domain in the about is mykdrama, https://kdramavostfr.com/dmca/

Je pense que c'est un clone mais bon si ça te dérange tu a #1702 Voirdrama qui plus complet et à jour

**Comment by hollowshiroyuki** [comment]
Site is dead or changed url

**Comment by Kreliam** [comment]
> Site is dead sorry , i closs the subject
