### ISSUE TITLE
Failed stuck on WebView? Can't bypass cloudfare in nhentai extension!

### ISSUE THREAD

**Issue by erickyun** [aniyomiorg/aniyomi-extensions#1780]
### Source information and language

Nhentai 1.4.37

### Steps to reproduce

Since yesterday,
When I try to Open nhentai extention I get can't bypass cloudflare anymore?
When I click on webview, then I click to human confirmation, it says failed no matter how many times I ty! The site gets stuck in infinite loop in cloudflare secure checking?

### Expected behavior

Nhentai bypass cloudflare!

### Actual behavior

Nhentai doesn't bypass cloudflare!

### Aniyomi version

0.14.3-6151 preview

### Android version

Android 11

### Other details

Redmi note 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.
