### ISSUE TITLE
Anime library went missing when launched

### ISSUE THREAD

**Issue by farsdewibs0n** [aniyomiorg/aniyomi-extensions#1787]
### Source information and language

All extensions 

### Steps to reproduce

1. launch the app
2. ...

### Expected behavior

Anime library shouldn't be gone (incl history)

### Actual behavior

The anime library is gone

### Aniyomi version

R6151

### Android version

Android 12

### Other details

For some reason, my whole anime library is gone (incl updates and history) and restoring doesnt restore anime

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This is an app issue, not an issue with any extension. Please open an issue of the repo for the app instead.
