### ISSUE TITLE
Google Drive Extension Crashes when opening with url

### ISSUE THREAD

**Issue by FiringTyphoon** [aniyomiorg/aniyomi-extensions#1789]
### Source information and language

Google Drive 13.5

### Steps to reproduce

1. Add the drive folder path
2. Restart the app
3. Click on the extension to see the contents on the extension

### Expected behavior

The extension opens and I can see the list of episodes to watch

### Actual behavior

The app crashes

### Aniyomi version

0.12.3.10

### Android version

Android 12 SKQ1.211103.001 | Miui Global 13.0.6 | Xiaomi Redmi Note 11 4g

### Other details

[Error.txt](https://github.com/aniyomiorg/aniyomi-extensions/files/11886282/Error.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Can you try [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/latest) and see if the problem persists?

**Comment by FiringTyphoon** [comment]
> Can you try [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/latest) and see if the problem persists?

In the preview it stops crashing but it says "Failed to load items, please log in through webview", perhaps I need to put the episodes in a special way to work with the preview?

**Comment by Claudemirovsky** [comment]
> In the preview it stops crashing but it says "Failed to load items, please log in through webview", perhaps I need to put the episodes in a special way to work with the preview?

Just to be sure, did you login in webview as the error message asks you to do? if not, then do it and try again.

**Comment by FiringTyphoon** [comment]
> 
I entered to show you that it didn't work, but after it gave me an error I retry to login and now it works, I will attach the error just so if someone have the same problem, just try again

Just as an extra, if someone is having problems with the episodes not showing, you just need to set them like the local, you make a subfolder for every anime and put cover.jpg to have an image 

![Screenshot_2023-06-27-21-23-33-836_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi-extensions/assets/29073951/84333e08-968a-4453-a31f-03ef67470bf5)
