### ISSUE TITLE
Wbijam-Removal of Source

### ISSUE THREAD

**Issue by tsuperongpu** [aniyomiorg/aniyomi-extensions#1804]
### Source information and language

Wbijam 13.1

### Steps to reproduce

1.Open Wbijam.pl source.
2. Attempt to select anime.

### Expected behavior

It should be able to show list of anime.

### Actual behavior

It does not work.

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Other details

Site is expected to shut down on July 1st 2023 due to the legal action. Information given in advance, due to the annoucment on the site.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closing as site seem to not have shut down after all
