### ISSUE TITLE
Various sources in Spanish 

### ISSUE THREAD

**Issue by Credits125** [aniyomiorg/aniyomi-extensions#1818]
### Source name

Series, movies, anime

### Source link

https://playhublite.com/

### Language

Español

### Other details

https://playhublite.com/ "series, movies, anime, dramas
https://hdfull.org/ "series, movies"
https://cinehdplus.org/ "series, movies"
https://www.iq.com/?lang=es_mx "asian dramas"
https://hdfull.club/ "series, movies"
https://animeblix.com/ "anime"
https://nextdede.com/ "series, movies, anime"
https://pelisforte.nu/ "movies"
https://sololatino.net/ "series, movies, animes"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closed because multiple requests were made in the same issue. Please open a separate issue for each source.
