### ISSUE TITLE
Animeworld extension does not work ("Failed to bypass cloudfare") and none of the suggested fix seem to work

### ISSUE THREAD

**Issue by Benji357k** [aniyomiorg/aniyomi-extensions#1834]
### Source information and language

Animeworld 13.26 (Italian)

### Steps to reproduce

1. Open any episode of any anime inside the app or try to download it.
2. "Failed to bypass Cloudflare".

### Expected behavior

The episode should be played/downloaded as normal. The Cloudflare issue should be easily fixed, as reported in the troubleshooting section.

### Actual behavior

It's impossible to play or download any episode (unless it was downloaded before the issue occured). The Cloudflare issue fix does not seem to work in any way.

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
1. go to webview and verify.
2. change your user agent. guide: https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by Benji357k** [comment]
As I said, there's no fix in the troublshooting section which works (at least for me) in this case. I've already changed the agent (with a proper one, of course), but no result occured.
The issue must be linked with the latest update of the extension, since I had an older version of it on another device and it was working fine, until I updated it and stopped working there too.

**Comment by fakebhai** [comment]
same for preview version?

**Comment by fakebhai** [comment]
yup I checked many user agents, doesn't seem like cloudflare issue but certainly isn't working.

**Comment by Benji357k** [comment]
Will there be an update for the extension in order to fix the issue?

**Comment by fakebhai** [comment]
> Will there be an update for the extension in order to fix the issue?

can't say if anyone's working on it or not you can check commit or check on their discord server for updates on extensions/app
