### ISSUE TITLE
Saikô Animes (PT-BR)

### ISSUE THREAD

**Issue by Rey619Gamer** [aniyomiorg/aniyomi-extensions#1835]
### Source name

Saikô Animes 

### Source link

https://saikoanimes.net/

### Language

Portuguese - Brazil

### Other details

I don't know if it's possible to add this extension.

+18/NSFW = No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
It seems to be possible to add, but i am in doubt about the usefulness of the extension, since you have to subscribe to the "saiko pass" in order to watch most anime....

Anyway, i'm not going to add it for now, but any other contributor can do it, so you may need to be patient and wait a bit.
