### ISSUE TITLE
zoro.to domain change

### ISSUE THREAD

**Issue by Rik-Kirtaniya** [aniyomiorg/aniyomi-extensions#1836]
### Source information and language

zoro.to (experimental) 13.29

### Source new URL

https://aniwatch.to/

### Other details

sanji.to no longer works, and all previous domains are redirected to the aforementioned url

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
#1832
