### ISSUE TITLE
9Anime: Failed Bypass Cloudflare

### ISSUE THREAD

**Issue by Harleythetech** [aniyomiorg/aniyomi-extensions#1847]
### Source information and language

9Anime 13.46(English)

### Steps to reproduce

1. Search for an anime globally 
2. Wait for it to load
3. Be Greeted with "Failed to Bypass Cloudflare" (Seems to be a network issue? even on my laptop it shows the cloudflare checkpoint before opening the site)

### Expected behavior

Aniyomi should show the lists of anime for that search 

### Actual behavior

fails to load the anime and shows "Failed to bypass Cloudflare"

### Aniyomi version

Preview r6151

### Android version

Android 11

### Other details

is there any way for the cloudflare checkpoint to be bypassed? I Don't mind clicking on captchas just to search and play a video from 9anime

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Skill issue. The [cloudflare troubleshooting manual](https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues) solves it just fine (tested here).
