### ISSUE TITLE
EXTENSION : ANIME SUGE

### ISSUE THREAD

**Issue by RuDru-OP** [aniyomiorg/aniyomi-extensions#1849]
### Source name and language

https://ANIMESUGE.TO
### Describe your suggested feature

ANIME NOW IS A VERY GOOD SITE PLEASE ADD THIS EXTENSION

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
This site is a 9anime mirror, closing as there is already an extension for the original.
