### ISSUE TITLE
AniWatch.to Can't Bypass Cloudflare from App

### ISSUE THREAD

**Issue by Rik-Kirtaniya** [aniyomiorg/aniyomi-extensions#1850]
### Source information and language

AniWatch.to 13.31 (English)

### Steps to reproduce

1. Do any of the following:
a. Try to open the Anime Source from the Browse section
b. Try to open an anime episode
2. "Failed to Bypass Cloudflare".

Furthermore
3. Try opening any of the anime pages in webview within the app
4. Encounter Cloudflare Verification Captcha
5. Touch on the "Verify you are human" checkbox
6. Instead of verifying the same verification page reloads and makes you check the box again, ad infinitum

### Expected behavior

Episodes should play normally.
Anime Source should be able to be browsed in the Browse section.
Opening in webview from within the app should not have an infinite loop reloading into the same verification page due to verification failing.

### Actual behavior

Episodes don't play.
Anime Source cannot be browsed.
Webview has infinite loop of reloading verification page.

### Aniyomi version

Preview r6151 (43e8dcd1f, 15/06/2023 2:14 pm)

### Android version

Android 13

### Other details

User agent is as it was set by default and was not changed by me.
This problem appeared less than a day earlier from the moment of me posting this.
The Cloudflare Verification page can be successfully passed when accessed via mobile firefox browser, with the homepage displaying normally, but fails to do so when accessed from the webview ui in the app itself, and instead shows the behaviour as previously described.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
In the [cloudflare troubleshooting manual](https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues), among its ways to fix CF problems, there's a part where it says about **changing** your user-agent. You said that you're using the default one, so changing it (ex, to the UA of a mobile browser) will help you.
