### ISSUE TITLE
Source Request: Movie4U

### ISSUE THREAD

**Issue by Bayuftj** [aniyomiorg/aniyomi-extensions#1876]
### Source name

Movie4U

### Source link

https://movie4u.watch/series?category=24&quality=undefined&imdb=0.0|10.0&year=1900|2021

### Language

Arabic

### Other details

It is not an inappropriate content site

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by adly98** [comment]
Already exists
@jmir1
