### ISSUE TITLE
Rule34video duration filter

### ISSUE THREAD

**Issue by fakebhai** [aniyomiorg/aniyomi-extensions#1891]
### Source name and language

Rule34video 13.5 (English)

### Describe your suggested feature

It's usually very hard to search on Rule34video (extension) so link redirections/opening-links can help a lot. also there's time filter already avaliable on website so if it's possible to implement that then that would be great.

also, for some reason search on Rule34video site and extension shows completely different results. so syncing it should help a lot. (site results preferred).

opening links example: 
![Screenshot_2023_0706_182343](https://github.com/aniyomiorg/aniyomi-extensions/assets/101493467/f0f17149-5ca9-42b9-90ad-60ffb7524032)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
fulfilled, closing.

**Comment by Secozzi** [comment]
Reopened as duration filter wasn't implemented

**Comment by fakebhai** [comment]
![Screenshot_2023_0718_172049.jpg](https://github.com/aniyomiorg/aniyomi-extensions/assets/101493467/8cf9af4c-36a9-467f-a76f-34c0339933d2)

![Uploading Screenshot_2023_0718_172012.jpg …]()

should I open another issue for it or you can add error option in it insted of opening/downloading it and file format not supported things.
