### ISSUE TITLE
Change domain oploverz

### ISSUE THREAD

**Issue by kitsu2** [aniyomiorg/aniyomi-extensions#1893]
### Source information and language

Oploverz 13.14

### Source new URL

https://oploverz.care/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by kinoarizu** [comment]
https://oploverz.care can no longer be accessed, it looks like the new site has changed again.

I found several similar Oploverz sites, which one is the correct one?

https://oploverz.red/
https://oploverz.fit/
https://oploverz.org/

**Comment by kitsu2** [comment]
> https://oploverz.care can no longer be accessed, it looks like the new site has changed again.
> 
> I found several similar Oploverz sites, which the correct one?
> 
> https://oploverz.red/ https://oploverz.fit/ https://oploverz.org/

Oplover.win

**Comment by kitsu2** [comment]
> https://oploverz.care can no longer be accessed, it looks like the new site has changed again.
> 
> I found several similar Oploverz sites, which the correct one?
> 
> https://oploverz.red/ https://oploverz.fit/ https://oploverz.org/

Will you fix the extension?

**Comment by kinoarizu** [comment]
> > https://oploverz.care can no longer be accessed, it looks like the new site has changed again.
> > I found several similar Oploverz sites, which the correct one?
> > https://oploverz.red/ https://oploverz.fit/ https://oploverz.org/
> 
> Will you fix the extension?

Yeap, I'll fix it soon
