### ISSUE TITLE
Yomiroll - Add Catalan ("ca-ES") to the list of languages.

### ISSUE THREAD

**Issue by adrineko98** [aniyomiorg/aniyomi-extensions#1894]
### Source name and language

Yomiroll

### Describe your suggested feature

With new Dragon Ball Super movie, they added Catalan ("ca-ES") language to the list of languages.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
This has already been added
