### ISSUE TITLE
Extract/Show hosts after a fansub is selected in turkanime.tv

### ISSUE THREAD

**Issue by glaicodes** [aniyomiorg/aniyomi-extensions#1903]
### Source name and language

Turkanime.tv (Turkish)

### Describe your suggested feature

The current source loading system for turkanime could be improved imo

An idea I had which is you select fansubs first on the source selection screen then it extracts the hosts and displays them after
Since on anime with a lot of different fansub translations even with only 3 or 4 hosts selected in the settings the episodes take forever or dont even load

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This is not currently possible in Aniyomi given the layout of the website.
