### ISSUE TITLE
Download issue: MyStream server

### ISSUE THREAD

**Issue by fakebhai** [aniyomiorg/aniyomi-extensions#1904]
### Source information and language

AnimeWorld India 13.2 (Multi) 

### Steps to reproduce

select preferred server : MyStream in extension settings. (it's default so you can skip)
try downloading episode which contains MyStream Server (Ben 10 alien force for easiness)
it's likely it'll fail (instant download) unless it picks StreamSB somehow. 

### Expected behavior

Download episode completely using MyStream. 

### Actual behavior

Can't download (instant download) episodes From MyStream. (occurs 98% of time 2% could be auto selecting StreamSB due to unavailability of MyStream) 

### Aniyomi version

preview: r6151; beta: r6453, r6473

### Android version

Android 12

### Other details

this could be due to MyStream extractor. streaming is working completely fine but download isn't working. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Are you still able to play the videos from MyStream? Because if so, then it's a download problem which the extension can do nothing about.

**Comment by fakebhai** [comment]
> Are you still able to play the videos from MyStream? Because if so, then it's a download problem which the extension can do nothing about.

yes I can stream, I also thought it's an ffmpeg issue but can't be sure. I tried ffmpeg on replit by coping the same link and download it, which worked. so idk what's the exact issue.

**Comment by Secozzi** [comment]
If you can still play the videos, it's not an extension issue. Open this in the repo for the app instead.
