### ISSUE TITLE
Animeworld.tv: Missing servers

### ISSUE THREAD

**Issue by Yoshinizar** [aniyomiorg/aniyomi-extensions#1920]
Source information

Animeworld.tv 13.31

### Source language

Italian

### Source new URL

www.animeworld.so

### Other details

Thank you for update animeworld.tv but missed animeworld server and Dodestream in a player video of episode

Animeworld server Is a direct server player with High quality video, please add and fix

See photo 
[
![Screenshot_2023-09-21-17-09-33-97_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi-extensions/assets/72281082/f744bd34-4e89-46c3-b5c9-c155a605d8ba)
![Screenshot_2023-09-21-17-08-49-78_8fdea02c47a76e0fe7eccbf0ee9f2748](https://github.com/aniyomiorg/aniyomi-extensions/assets/72281082/e48a1280-9a02-427a-9b32-d4340a8f3b27)
](url)

![IMG_20230921_171927](https://github.com/aniyomiorg/aniyomi-extensions/assets/72281082/f3c9bc35-abb7-46d8-af6a-369b8bb3213e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Yoshinizar** [comment]
![IMG_20230717_232017](https://github.com/aniyomiorg/aniyomi-extensions/assets/72281082/d174e491-2fdf-4986-9a6f-317ed30c06d0)

**Comment by Yoshinizar** [comment]
> ### Source information
> Animeworld.tv 13.27
> 
> ### Source language
> Italian
> 
> ### Source new URL
> [www.animeworld.so](http://www.animeworld.so)
> 
> ### Other details
> Thank you for update animeworld.tv but missed animeworld server in a player video of episode
> 
> Animeworld server Is a direct server player with High quality video, please add and fix
> 
> See photo ![Screenshot_2023-07-17-22-54-20-54_423fe07c33ed17f15a4e92e5e3a15972](https://user-images.githubusercontent.com/72281082/254070378-0bb7e1ce-1efa-4047-8ad2-918aafb23501.jpg) ![Screenshot_2023-07-17-22-57-57-15_423fe07c33ed17f15a4e92e5e3a15972](https://user-images.githubusercontent.com/72281082/254070382-c354b756-e084-4c21-bc52-2cd43fe9e841.jpg)
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated all installed extensions.
> * [x]  I have opened WebView and checked that the source URL is not updated yet.
> * [x]  I will fill out all of the requested information in this form.

![IMG_20230717_232017](https://github.com/aniyomiorg/aniyomi-extensions/assets/72281082/d39f1d50-7ba7-4232-8bc3-ee2cd572689d)

**Comment by Yoshinizar** [comment]
![IMG_20230717_232017](https://github.com/aniyomiorg/aniyomi-extensions/assets/72281082/8abd615f-e871-482c-a02c-091248f8aa8d)

**Comment by Yoshinizar** [comment]
Please anyone can fix this?

**Comment by Yoshinizar** [comment]
@Samfun75 @jmir1

**Comment by Secozzi** [comment]
@Yoshinizar do not ping contributors, someone will see to it if they feel like it.

**Comment by Yoshinizar** [comment]
Please Is a Little fix, can anyone add Animeworld server in the player?

**Comment by Fedekika** [comment]
4 months to fix this problem and I still don't see any updates, apparently Italian users are not to your liking, dozens of updates for other extensions from various countries and this is nothing, long live Saikou

**Comment by Diegopyl1209** [comment]
In 4 months you could have learned to program and solve it yourself, long live aniyomi

**Comment by Roby93IT** [comment]
yes it's really embarrassing, I follow this post for updates, but nothing, aniyomi 🐢
No TV Mod After 1 Year, no fix, wow, users can no longer open requests on Discord and are redirected here

**Comment by Roby93IT** [comment]
> In 4 months you could have learned to program and solve it yourself, long live aniyomi

rude answer, not everyone is as good as you, you make it easy m, go away

**Comment by Diegopyl1209** [comment]
xd

**Comment by Secozzi** [comment]
> 4 months to fix this problem and I still don't see any updates, apparently Italian users are not to your liking

This app is community driven, so ideally the updates to Italian extensions should come from Italian users. None of the active Devs are Italian so there won't be as many updates to Italian extension.

**Comment by Roby93IT** [comment]
> > 4 mesi per risolvere questo problema e ancora non vedo nessun aggiornamento, a quanto pare gli utenti italiani non sono di tuo gradimento
> 
> Questa app è guidata dalla community, quindi idealmente gli aggiornamenti alle estensioni italiane dovrebbero provenire da utenti italiani. Nessuno degli sviluppatori attivi è italiano, quindi non ci saranno così tanti aggiornamenti all'estensione italiana.

who created your Italian extensions?  I don't see Italian developers on aniyomi GitHub or discord

**Comment by Secozzi** [comment]
The extensions were originally created by non-Italians as far as I know, but being open source us developers will only work on whatever we feel like working. Since we don't speak Italian, we're less incentivized to work on them as opposed to other extensions. Remember, we are volunteers spending our free time to work on this, if you're not happy with us not working on something you should try and fix it yourself because nagging us won't do anything.

**Comment by jmir1** [comment]
> yes it's really embarrassing, I follow this post for updates, but nothing, aniyomi 🐢
> No TV Mod After 1 Year, no fix, wow, users can no longer open requests on Discord and are redirected here

It's not surprising that issues like these don't get much attention and aren't high on anyone's priorities.
There are probably around 10 active developers who work on Aniyomi. No-one has any tasks assigned to them, everyone works on what they feel like doing. This is because we all do this in our precious free time.
It's actually embarrassing that you think you are somehow entitled to getting the updates that you want.

P.S. I've been waiting for some GitHub drama, finally it's here.

**Comment by Roby93IT** [comment]
> Per quanto ne so, le estensioni sono state originariamente create da non italiani, ma essendo open source noi sviluppatori lavoreremo solo su ciò su cui abbiamo voglia di lavorare. Dato che non parliamo italiano, siamo meno incentivati ​​a lavorarci rispetto ad altre estensioni. Ricorda, siamo volontari che spendono il nostro tempo libero per lavorare su questo, se non sei soddisfatto del fatto che non lavoriamo su qualcosa dovresti provare a risolverlo da solo perché assillarci non servirà a nulla.

I have never pestered or written or made any requests to you, I only follow the development, I only read the replies and commented, since they are Italian and I am also interested in these fixes and extensions, but if you have to create extensions and leave them to rot without even making small corrections, then only make extensions that you feel like wasting time on

**Comment by Yoshinizar** [comment]
@Roby93IT and @Fedekika please be polite people, the guys at aniyomi have always helped me especially secozzi, if it weren't for him 80% of the Italian extensions wouldn't even exist, you just have to thank these people who work for free, sooner or later someone will fix animeworld, don't be rude

**Comment by Rufusnightly** [comment]
but how do you add a site and not put the main server?  you are geniuses 😂

**Comment by Yoshinizar** [comment]
Please anyone can add miss servers?
