### ISSUE TITLE
OnePace Possibility 

### ISSUE THREAD

**Issue by CodeOelta** [aniyomiorg/aniyomi-extensions#1926]
### Source name

OnePace

### Source link

https://onepace.net/

### Source language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by tsunaproxD** [comment]
Yes, this is necessary

**Comment by Secozzi** [comment]
The site currently only offers torrents and telegram downloads, neither of which Aniyomi can stream from. Until they offer a suitable streaming provider, the only option is to download and use [local anime](https://aniyomi.org/help/guides/local-anime/)
