### ISSUE TITLE
the old Cuevana page died

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi-extensions#1933]
### Source name

Cuevana 3

### Source language

Español

### Source link

https://n2.cuevana3.me/

### Other details

Could you please fix the source, you will see the old page died and I know that you can't fix that, but Cuevana created a new page and we want the Spanish server to update the extension by removing the link from the old page and adding the new one, which is this https://cuevana3.desi/ 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by tsunaproxD** [comment]
Yes pls

**Comment by Fidelo8** [comment]
Hopefully they are working on this one, haven't been working for a while now
