### ISSUE TITLE
Fix Egy Dead Download

### ISSUE THREAD

**Issue by Bayuftj** [aniyomiorg/aniyomi-extensions#1947]
### Source information

EgyDead 13.4 (Arabic)

### Source language

Arabic

### Steps to reproduce

I did everything to download from this site but it didn't want to 

### Expected behavior

It was supposed to download the episode but it stopped

### Actual behavior

When I want to download an episode from this site, it doesn't download with me

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Other details

Thank you for fixing the servers, they are working perfectly

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Are you still able to play the videos?

**Comment by Bayuftj** [comment]
Yes

**Comment by Secozzi** [comment]
If you're able to play videos, then the extension works fine. Any download issues are caused by the app so please open an issue on the repo for the [app](https://github.com/aniyomiorg/aniyomi) instead.

**Comment by Bayuftj** [comment]
How do I fix it then

**Comment by Secozzi** [comment]
Please follow the instructions I gave you in my last comment
