### ISSUE TITLE
Unable to parse TLS packet header

### ISSUE THREAD

**Issue by MiracoleWorker** [aniyomiorg/aniyomi-extensions#1956]
### Source information

WeLoveMangaOne 1.4.9

### Source language

Japanese

### Steps to reproduce

1. Install WeLoveMangaOne 1.4.9
2. Search for and select One Piece
3. Click on chapter to view or to download

### Expected behavior

The cover page of the chapter appears if you clicked on it or a progress wheel appears if you hit download. 

### Actual behavior

After clicking on the chapter, a black screen appears for a microsecond and then it returns to the chapter select screen with the error message at the bottom of the screen: "Unable to parse TLS packet header."

When hitting the download button, the progress wheel spins endlessly.

When swiping down to refresh the chapter select page, an error appears that says "javax.net.ssl.SSLException: Unable to parse TLS packet header." 

### Aniyomi version

Preview r6151

### Android version

Android 13

### Other details

One Plus 5, LineageOS (20) + microG

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
Manga extensions are managed on tachiyomi. Please test on tachiyomi app and report on their GitHub.
