### ISSUE TITLE
asia2tv Remove Source

### ISSUE THREAD

**Issue by Bayuftj** [aniyomiorg/aniyomi-extensions#1961]
### Source link

https://ww1.asia2tv.pw/

### Other details

Delete this site because it is not an anime site, it is a Korean series site

### Requirements

- [X] Proof of ownership/intent to remove sent to a Aniyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by Secozzi** [comment]
We allow non-anime streaming sites.

**Comment by Bayuftj** [comment]
I mean, you added it before, and it's not an anime site, it's a Korean series site
