### ISSUE TITLE
9anime problem

### ISSUE THREAD

**Issue by Nintenstation** [aniyomiorg/aniyomi-extensions#1970]
### Source information

9anime 13.46 (English)

### Source language

English

### Steps to reproduce

Whenever I open the source and go to an anime, it gives a big warning and I cannot open any episodes.

### Expected behavior

It should open as normal, with any big error.

### Actual behavior

It shows me the big message like in the image:
![Screenshot_20230728_231234_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/110612128/f0b09e3b-dc6d-40a2-a921-8c779cf75453)

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Shinmentakezo0** [comment]
![Screenshot_2023-07-29-10-00-07-16_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi-extensions/assets/140866459/a694cb13-a8d3-4690-8c58-8c9342afa619)
Same problrm

**Comment by spicyroe** [comment]
![IMG_20230729_094513](https://github.com/aniyomiorg/aniyomi-extensions/assets/140866933/0f3ebd3d-cf12-41b3-801c-229b4cbe97a0)

Same

**Comment by Onlyracc** [comment]
Same with 9anime
![Screenshot_20230730-100815](https://github.com/aniyomiorg/aniyomi-extensions/assets/91634260/e4d7e8bd-024f-4c15-a82e-70ce51e12d6b)

**Comment by Harleythetech** [comment]
9anime got rebranded to AniWave 

[AniWave](https://aniwave.to/home)

![image](https://github.com/aniyomiorg/aniyomi-extensions/assets/51787264/501057af-bd42-4384-bbf8-4c8df3387ecf)
