### ISSUE TITLE
Animeonline360

### ISSUE THREAD

**Issue by Delmarcop52** [aniyomiorg/aniyomi-extensions#1971]
### Source information

Animeonline360 13.1

### Source language

English 

### Steps to reproduce

Solve

### Expected behavior

Play video 

### Actual behavior

Dont play video
Infinite loading

### Aniyomi version

Aniyomi App version: 0.14.3-6147 

### Android version

Motorola 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Does the video play in webview? I tried a bunch of different videos and neither would load in app nor webview, which indicates that its a problem with the website.

**Comment by Secozzi** [comment]
Closing due to no response, and the fact that the issue is most likely the website's fault
