### ISSUE TITLE
SuperStream API issue (Possible Fix suggestion)

### ISSUE THREAD

**Issue by Bipolar708** [aniyomiorg/aniyomi-extensions#1972]
### Source information

Superstream 13.9

### Source language

English

### Steps to reproduce

Try downloading any thing released from December 2022 till recently

### Expected behavior

Be able to stream and/or download recent movies and TV series

### Actual behavior

Endless buffering and a "list is empty" when trying to download

### Aniyomi version

Preview r6151

### Android version

Android 13

### Other details

Regarding this Superstream extension problem with the API

Couldn't yall just kinda like 're-route' it to get content like other extensions, like with extractors and stuff(assuming other extensions dont use APIs 🤔)

Cz from the extension status message...... the site/source just stopped 'updating' the API with new content...... so couldn't y'all work some programming magic around this issueㄟ(ツ)ㄏ

Or is it just wishful thinking🥲

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
What exactly is being proposed? Re-route it where?

**Comment by Bipolar708** [comment]
Maybe re-route is a bad term....... what Im trying to say is instead of getting the content from the API thats not getting new content why not get it from the website directly 👀..... I hope Im making sense😅


For example the same way y'all would get content from a typical anime website.... do the same with Showbox

Or do all sites utilize APIs ㄟ(ツ)ㄏ

**Comment by hvroun1** [comment]
it's no longer free for content 2023 and onwards.
