### ISSUE TITLE
Fmovies showing an error 

### ISSUE THREAD

**Issue by Fidelo8** [aniyomiorg/aniyomi-extensions#2004]
### Source information

Fmovies English 13.4

### Source language

English 

### Steps to reproduce

Gives an error message when trying to watch something 

### Expected behavior

Should be able to play movies and TV shows

### Actual behavior

Not showing the video and gives error message 
![Screenshot_20230803-150859_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/140089163/06a8a8d9-e6d9-4d1e-ad02-7b98637fbd80)

### Aniyomi version

App version: 0.14.5-6453 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Jnss98b** [comment]
Also have this exact error on aniyomi 0.12.3.10 on android 13 with fmovies extension version 13.4

**Comment by OMTDesign** [comment]
I also get this error using Preview build R6151, and tested versions 13.5, 13.4 and 13.3 of Fmovies extension.

I was looking at previous commits to the extension and saw that @enimax-anime had done some work on it. I saw on their profile that they create a similar application to Aniyomi, called Enimax.  I installed Enimax and tested the Fmovies plugin on the application and it works fine there.

**Comment by Secozzi** [comment]
We're currently using Enimax's solution to help scrape fmovies, but it had to be disabled due to (what we think is) external abuse. We have not gotten their permission to use it again and until we do, we either have to figure out another way to scrape or just let the extension be broken.
