### ISSUE TITLE
Showbox (Superstream Replacementㄟ(ツ)ㄏ)

### ISSUE THREAD

**Issue by Bipolar708** [aniyomiorg/aniyomi-extensions#2009]
### Source name

Showbox

### Source link

https://www.showboxmovies.net/

### Source language

English

### Other details

Since Superstream has become obsolete...... this might be a great replacement

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
1. Superstream isn't obsolete
2. The site is a mirror of sflix, which already exists as an extension

**Comment by Bipolar708** [comment]
Well there's an status message in extention status....... saying the extension wont be able to stream/download new(2023) content
