### ISSUE TITLE
Subtitle downloads

### ISSUE THREAD

**Issue by Bipolar708** [aniyomiorg/aniyomi-extensions#2011]
### Source name

Any extension with subtitles on source site

### Source language

English

### Describe your suggested feature

Can yall make it possible to get the corresponding subtitle files 'srt' when downloading episodes from extensions/sites with players that offer subtitles 

### Other details

Either by embedding the subtitles directly into the epidodes if possible...... or just download both the episode and subtitles from a chosen language and provide a way to choose srt files from our devices (sort of like a VLC interface)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
