### ISSUE TITLE
Being able to open links on app to add series easier 

### ISSUE THREAD

**Issue by EfeDevirgen** [aniyomiorg/aniyomi-extensions#2015]
### Describe why this should be added

On share menu or open app menu there is an option to open link and that would send you to that seri on that site's source 
![Screenshot_20230805-084427_Android System](https://github.com/aniyomiorg/aniyomi-extensions/assets/136119810/9728ad0c-54d3-4ce9-b5f2-8e63a3d55f51)
![Screenshot_20230805-082359_Android System](https://github.com/aniyomiorg/aniyomi-extensions/assets/136119810/74188290-1326-460d-b973-a3e6d9e25222)
Like in these photos it would be good/foolproof if its both of them

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open (or closed) issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
"Open link with aniyomi" has to be implemented in each respective extension, so make an issue for each extension you want this to happen to

**Comment by EfeDevirgen** [comment]
![Screenshot_20230805-143338_Discord](https://github.com/aniyomiorg/aniyomi-extensions/assets/136119810/e4073570-43b1-4c16-962d-5c281986767d)
Clarification

**Comment by EfeDevirgen** [comment]
![Screenshot_20230805-151850_Discord](https://github.com/aniyomiorg/aniyomi-extensions/assets/136119810/3f0d8a88-9622-4b19-bb90-6d406b9ca41c)
Another one
