### ISSUE TITLE
Voir cartoon

### ISSUE THREAD

**Issue by Urbexed** [aniyomiorg/aniyomi-extensions#2027]
### Source name

Voir Cartoon

### Source link

https://voircartoon.com/

### Source language

French

### Other details

Nsfw = no

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Kreliam** [comment]
Salut @Urbexed , voircarton n'est il pas down ?

**Comment by Urbexed** [comment]
> Salut @Urbexed , voircarton n'est il pas down ?

Non et il l'a jamais été de ce que je sais, si tu as pas accès au site configure un DNS

**Comment by Kreliam** [comment]
> > Salut @Urbexed , voircarton n'est il pas down ?
> 
> 
> 
> Non et il l'a jamais été de ce que je sais, si tu as pas accès au site configure un DNS

J'ai essayée avec un dns adguard ça marche bien mais tu a utilisé d'autres dns ?

**Comment by Urbexed** [comment]
> > > Salut @Urbexed , voircarton n'est il pas down ?
> > 
> > 
> > Non et il l'a jamais été de ce que je sais, si tu as pas accès au site configure un DNS
> 
> J'ai essayée avec un dns adguard ça marche bien mais tu a utilisé d'autres dns ?

Oui j'utilise le DNS de cloudflare, si tu vas dans les paramètres de sécurité d'un navigateur tu peux choisir un DNS, par exemple sur chrome tu peux sélectionner cloudflare (ce que j'ai fait)

**Comment by Kreliam** [comment]
> personne pour le faire ? sérieux ?

Pas le choix on doit se démerder à apprendre le code pour réglé les soucis nous mêmes 🥲. mais tu peux  toujours taguer hollowshiroyuki c'est le même qui géré ta demande pour anime-sama

**Comment by Secozzi** [comment]
@Kreliam please do not tag contributors for extension requests. Someone will make an extension for this when they feel like it

**Comment by Urbexed** [comment]
> @Kreliam please do not tag contributors for extension requests. Someone will make an extension for this when they feel like it

at what point is my message off-topic ????

**Comment by Urbexed** [comment]
> > personne pour le faire ? sérieux ?
> 
> Pas le choix on doit se démerder à apprendre le code pour réglé les soucis nous mêmes 🥲. mais tu peux toujours taguer hollowshiroyuki c'est le même qui géré ta demande pour anime-sama

ça pête les couilles j'ai juré, le français est une des langues les plus parlées et tout le monde s'en bat les reins

**Comment by Secozzi** [comment]
Friendly reminder that GitHub is for development, not discussion
