### ISSUE TITLE
Add xhamster to unofficially source

### ISSUE THREAD

**Issue by 1YuviKing1** [aniyomiorg/aniyomi-extensions#2030]
### Source name

Xhamster

### Source link

https://amp.xhamster.com/ 

### Source language

Multi

### Other details

+18/NSFW = yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by MikaelaMuller** [comment]
Why the hell is it the AMP version
Comment aside, xhamster has an alternative URL for countries that blocked it, for me its xhamster3.com
