### ISSUE TITLE
[Feature Request] Dub selection for KickAssAnime.am if available

### ISSUE THREAD

**Issue by Jake36921** [aniyomiorg/aniyomi-extensions#2032]
### Source name

kickAssAnime

### Source language

English

### Describe your suggested feature

There should be an option to switch between sub or dub if available in either inside the video player or the episode list

![Screenshot_20230810_005912_com huawei photos](https://github.com/aniyomiorg/aniyomi-extensions/assets/113159896/957443bf-8e9d-4d24-a9c4-092c1b93a9e1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Already exists, in extension settings
