### ISSUE TITLE
Animepahe 404

### ISSUE THREAD

**Issue by antocs** [aniyomiorg/aniyomi-extensions#2033]
### Source information

AnimePahe 13.26

### Source language

English

### Steps to reproduce

Try to watch or download an episode.

### Expected behavior

Should start the episode or download.

### Actual behavior

Download doesn't, but trying to watch without download gives error 404.

### Aniyomi version

App version: 0.12.3.10

### Android version

Android 12

### Other details

It worked earlier today, suddenly broken, the episodes I downloaded and watched now also give the error.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
both working fine in mine, just try DoH or VPN

**Comment by Secozzi** [comment]
Animepahe can sometimes be tricky with its url, try and refresh episode list and if that doesn't work, migrate to animepahe (click the three dots in top right, then migrate). Do you still get 404 after doing those two steps?

**Comment by antocs** [comment]
I already use DoH (google), and also migrating didn't fix it.

**Comment by Secozzi** [comment]
What about refreshing episode list? Also, which anime and episode does this happen for?

**Comment by fakebhai** [comment]
since it wasn't specific I took it as all

**Comment by antocs** [comment]
It seems it was specific episodes not working, tho episodes i already watched also threw the 404 error, its working with the new episodes now.
