### ISSUE TITLE
Instead of downloading apk of extension can't we make it like cloudstream

### ISSUE THREAD

**Issue by Gamer750** [aniyomiorg/aniyomi-extensions#2035]
### Source name

Anime and manga

### Source language

English

### Describe your suggested feature

Instead of downloading apk of extension can't we make it like cloudstream. Downloading via link inside the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
> If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
