### ISSUE TITLE
anix.to source request, very good site

### ISSUE THREAD

**Issue by Nintenstation** [aniyomiorg/aniyomi-extensions#2036]
### Source name

anix.to

### Source link

https://anix.to/

### Source language

English

### Other details

While 9anime is down, this site is an extremely good alternative to have that have similar video quality and whatnot. Please team, take notice! Thanks in advance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
It's a mirror of 9anime/aniwave, which already exists as an extension.

**Comment by Nintenstation** [comment]
> It's a mirror of 9anime/aniwave, which already exists as an extension.

But it's down. Is it being fixed, or is it impossible in current state? Sorry for asking too much, it's just my favorite source. But thank you so much for your work in advance! Just curious.

**Comment by Secozzi** [comment]
It's not possible to say whether or not someone is working on it, but it's not impossible to fix, just really difficult.

**Comment by Nintenstation** [comment]
> It's not possible to say whether or not someone is working on it, but it's not impossible to fix, just really difficult.

Okay, thank you! I'll wait patiently. G'luck to the team.
