### ISSUE TITLE
Some anime not loading, others stuck in infinite Loading, JSON Parsing Error (Desu-online extension)

### ISSUE THREAD

**Issue by Szesznik** [aniyomiorg/aniyomi-extensions#2041]
### Source information

desu-online 13.1 (Polish)

### Source language

Polish

### Steps to reproduce

   1. Open the anime viewing application.
   2. Select the "DesuOnline" source.
   3. Try to watch different anime to observe the different behaviors.

### Expected behavior

I should be able to successfully view and play all anime series.

### Actual behavior

1. Some anime load and play correctly. (e.g. Bleach)
2. Some anime are stuck in an infinite loading state and never play. (e.g. Monster)
3. For some anime, I receive the following error: (e.g. Sono Bisque Doll wa Koi wo Suru)
![signal-2023-08-13-004932_002](https://github.com/aniyomiorg/aniyomi-extensions/assets/91370976/662d5ffb-27a0-45c8-81f3-ea664241feb6)

### Aniyomi version

Preview r6151

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Resolved by #2039
