### ISSUE TITLE
Animension Stream not starting 

### ISSUE THREAD

**Issue by LittleFreak** [aniyomiorg/aniyomi-extensions#2051]
### Source information

Animension 13.20

### Source language

Englisch 

### Steps to reproduce

1. Browse Animension
2. Enter an Anime Entry
3. Start an Episode 

### Expected behavior

Stream should start /Video playing 

### Actual behavior

Playback stops/ Toast message "Video list is missing" although it just works fine in web view. 

### Aniyomi version

Animiru App version: 0.15.2.3 (standard, f5b0522, 103, 2023-08-04T19:02Z) 

### Android version

Android version: 13 (SDK 33) Android build ID: TP1A.220624.014.X806BXXU4BWD8

### Other details

Animiru is an direct fork of Aniyomi, so the bug in the source extension bug should still be present when installed in Anyomi. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LyuboA31** [comment]
Animension also Only shows 1 Source Host Doodstream while theres many on the Animension website can you please fix it
