### ISSUE TITLE
StreaminCommunity not work in aniyomi

### ISSUE THREAD

**Issue by Yoshinizar** [aniyomiorg/aniyomi-extensions#2053]
### Source information

StreamingCommunity 13.1

### Source language

Italian

### Source new URL

https://streamingcommunity.bet/

### Other details

The extension not work in aniyomi, but work in WebView, please fix this extension
![Screenshot_2023-08-16-11-57-02-01_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi-extensions/assets/72281082/2d42a7f1-ff8f-4d75-9691-7f867280311e)
![Screenshot_2023-08-16-11-57-06-47_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi-extensions/assets/72281082/8befbdaf-cb5b-4a97-a327-83ba8e2759fe)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Change URL in extension settings
