### ISSUE TITLE
Gogoanime language filter bug

### ISSUE THREAD

**Issue by bungadrum** [aniyomiorg/aniyomi-extensions#2056]
### Source information

Gogoanime 13.70

### Source language

English

### Steps to reproduce

1. Browse
2. Filter
3. Language set "Sub"
4. Apply Filter

### Expected behavior

It should only display the Subbed content

### Actual behavior

It displays both Sub and Dub at the same time the filter doesn't work it can't seperate the subbed and dubbed from each other and display only one of the two

### Aniyomi version

Stable 0.12.3.10

### Android version

Emui 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
That's a problem in the source itself, not the extension; so we "can't" fix it. You can check it in [this url](https://gogoanimehd.io/filter.html?keyword=Saiki+kusuo&language%5B%5D=sub&sort=title_az)
