### ISSUE TITLE
[Bug] <tenshi.moe> forbidden 403

### ISSUE THREAD

**Issue by ukbeast** [aniyomiorg/aniyomi-extensions#206]
## Device information
- Tachiyomi version: App version: 0.12.3.5-4403 (standard, 737c5c988, 71, 2021-11-29T21:33Z)
Android version: 11 (SDK 30)

## Source information
- Name: Tenshi.moe
- Extension version: latest.

## Steps to reproduce
1. Enable and open extension
2. Witness http 403

### Expected behavior
Be able to watch anime through this extension.

### Actual behavior
Can't see anime due to the site blocking the extension.

## Other details
Recieving notification about not being able to update anime list through tenshi.moe.

**Comment by BlanxZA** [comment]
+1 Webview works completely fine but as soon as i try to watch in player, i get a 403 error..

Seems to be related to the new ddos- guard that has been implemented.

**Comment by X9DF** [comment]
Same issue here

**Comment by Claude-Kenni** [comment]
It is still not working for me

**Comment by BlanXyz** [comment]
> It is still not working for me

Well that shouldn't be possible, bec its a known issue in the disc by now..

Maybe ur using an external player

**Comment by Claude-Kenni** [comment]
> > > It is still not working for me
> > 
> > Well that shouldn't be possible, bec its a known issue in the disc by now..
> > 
> > Maybe ur using an external player
> 
> ![Screenshot_2022-03-04-06-54-33-843_xyz.jmir.tachiyomi.mi.jpg](https://user-images.githubusercontent.com/97787671/156667357-26c4615a-6e83-423b-8716-aebfd4d47b01.jpg)
> 
> Whenever I tried to watch using tenshi.moe extension, I get this message. It's not forbidden 403 but it is "Error 403: Response code: 403" and I don't know what it is lol 😆. 
> 
> I'm using the internal player

Good news: it worked on an external player😄

**Comment by rollingmoai** [comment]
https://tenshi.moe/ has moved to https://marin.moe/: #1161

**Comment by Samfun75** [comment]
Closing as extension is migrated
