### ISSUE TITLE
remove this trash(akumanga)

### ISSUE THREAD

**Issue by zrql** [aniyomiorg/aniyomi-extensions#2085]
### Source link

don't know

### Other details

it was an arabic source at first but now it's an English hentai source 

### Requirements

- [X] Proof of ownership/intent to remove sent to a Aniyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by Secozzi** [comment]
This isn't the repo for manga extensions
