### ISSUE TITLE
AnimeFLV changed their domain 

### ISSUE THREAD

**Issue by XxS3RxX** [aniyomiorg/aniyomi-extensions#2098]
### Source information

AnimeFLV 13.47

### Source language

Spanish

### Source new URL

https://m.animeflv.net/

### Other details

Hello, I apologize for the inconvenience. 
The source in question has changed its domain. I hope they can correct the error and give a good quality. Thank you in advance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by imper1aldev** [comment]
That domain is the one currently being used in the extension, "https://m.animeflv.net" and "https://www3.animeflv.net" both domains belong to the same owner, redirect to the same site and contain exactly the same content, obviously adapted to display the content on a mobile device.
