### ISSUE TITLE
animeblkom (انمي بالكم)

### ISSUE THREAD

**Issue by ZoMpziO** [aniyomiorg/aniyomi-extensions#2099]
### Source information

انمي بالكم 13.12

### Source language

Arabic

### Source new URL

https://blkom.com/

### Other details

The last URL is https://animeblkom.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
This domain was already added in the extension's preferences in #2083.

**Comment by ZoMpziO** [comment]
Please change it

**Comment by Claudemirovsky** [comment]
> The url you change it is wrong

No, it isn't: Look at [this line](https://github.com/aniyomiorg/aniyomi-extensions/blob/41b84e2c757de1514bbae2ef62a657ee45293ad2/src/ar/animeblkom/src/eu/kanade/tachiyomi/animeextension/ar/animeblkom/AnimeBlkom.kt#L250), it contains exactly the same URL you provided in this issue, but it won't be used by default; You'll have to change it in the extension's preferences as i said before.

Also why tf are you submiting replies as issues to aniyomiorg/aniyomi-website (a repo completely unrelated with this issue)????????
