### ISSUE TITLE
Haikyuu To The Top S1 Ep1 doesn't load hosts in Turkanime

### ISSUE THREAD

**Issue by glaicodes** [aniyomiorg/aniyomi-extensions#2117]
### Source information

Turkanime TV 13.8

### Source language

Turkish

### Steps to reproduce

Open Haikyuu To The Top S1 Ep1 from Turkanime

### Expected behavior

The hosts should load 

### Actual behavior

It just spins forever

### Aniyomi version

r6648

### Android version

Android 11

### Other details

I tried changing the hosts but none of them worked, also it loads other anime 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closing as it was discovered on discord that this is a device issue, not an extension issue
