### ISSUE TITLE
Fix multimovies 

### ISSUE THREAD

**Issue by SaurabhKaperwan** [aniyomiorg/aniyomi-extensions#2120]
### Source name

Multimovies 

### Source language

English ,Hindi

### Source link

https://multimovies.xyz/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Change the URL in extension settings, access it in Browse -> Anime Extensions -> scroll to multimovies and click settings, then click the gear.
