### ISSUE TITLE
Source Request: Movies123

### ISSUE THREAD

**Issue by Zii9** [aniyomiorg/aniyomi-extensions#2130]
### Source name

Movie123

### Source link

https://ww1.new-movies123.co/

### Source language

English

### Other details

Movie site

**Comment by fakebhai** [comment]
![Screenshot_2023_0903_124102.jpg](https://github.com/aniyomiorg/aniyomi-extensions/assets/101493467/6d46bbbc-a8fb-425d-bc21-4c2f132899e5)

I won't be so sure unless we can scrape qualities better than 360p
