### ISSUE TITLE
 Manga Source Request

### ISSUE THREAD

**Issue by Bipolar708** [aniyomiorg/aniyomi-extensions#2136]
### Source name

Godamanga

### Source link

https://godamanga.art/ or https://en.baozimh.org/

### Source language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We don't manage Tachiyomi extensions here, make an issue on [Tachiyomi's github page](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose) instead
