### ISSUE TITLE
Aniwatch not working 

### ISSUE THREAD

**Issue by Fidelo8** [aniyomiorg/aniyomi-extensions#2150]
### Source information

Aniwatch.to 13.33

### Source language

English 

### Steps to reproduce

Tried playing an episode and it never loads 

### Expected behavior

Play video

### Actual behavior

When choosing an episode it should play 

### Aniyomi version

App version: 0.14.5-6453 

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Go to extension settings (Browse -> Anime Extensions -> scroll to aniwatch and click settings, then click the gear) and change the domain. If that doesn't help, please create a new issue and give an example anime & episode that doesn't load.
