### ISSUE TITLE
No episode runs under latest tab.

### ISSUE THREAD

**Issue by lambhassador** [aniyomiorg/aniyomi-extensions#2153]
### Source information

Superstream English  13.9 ,

### Source language

English 

### Steps to reproduce

1. Open Aniyomi ( Latest Stable release or Latest preview release)
2. Go to Browse>Anime Sources>SuperStream>Latest
3. Open any show, pick an episode

### Expected behavior

Some time to load and then episode runs

### Actual behavior

Infinite loading

### Aniyomi version

0.12.3.10 and  Priview r1651

### Android version

Android 11

### Other details

I have installed both Latest Stable release and Latest Preview versions. The problem is only with SuperStream. Any other extensions,  the shows under latest tab load fine. The shows under SuperStream popular tab work fine as well. It is only under latest tab that the issue occur. I have all the latest extensions. The shows under the  latest tab were working in the previous versions of Aniyomi but stopped working when I switched to the latest version.  I tried reinstalling the older versions, but the problem remained. I have updated Web View and changed user agent. The other shows run, SuperStream latest do not. I have Aniyomi installed on my Firestick , same problem on the Firestick as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Superstream doesn't work for content after december 2022. See #1972
