### ISSUE TITLE
More Gogoanime low year options

### ISSUE THREAD

**Issue by bungadrum** [aniyomiorg/aniyomi-extensions#2155]
### Source name

Gogoanime

### Source language

English

### Describe your suggested feature

Can you add more lower year options in the filter for Gogoanime?

### Other details

When you go to the Year option the lowest it goes is 1999, but there are more year options bellow it all the way to the 80's or even lower then that

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by F-Wer** [comment]
The years are retrieved from the filter gogoanimehd.io/filter.html . In the dropdown you can only filter for the years 1999 - 2023.

![image](https://github.com/aniyomiorg/aniyomi-extensions/assets/43503689/47b1aebc-c9f1-4071-980c-dea801008770)


I tried to filter for earlier years and I could find anime till 1957. But I don't know if this is a good idea to let the user filter years from a list of ~80 years.

**Comment by Secozzi** [comment]
It would be better to make a textbox where the user enters the year then, that way the extension doesn't need to update the filters every year as well.
