### ISSUE TITLE
MangaFire 

### ISSUE THREAD

**Issue by iCeY3** [aniyomiorg/aniyomi-extensions#2169]
### Source name

MangaFire 

### Source language

Multi

### Source link

Mangafire.to

### Other details

Website upgraded to v2

Please update extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Manga extensions aren't managed here. They go to the tachiyomi-extensions repo, but since there's already an [issue](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/17799) for it, just wait until someone decides to fix it.
