### ISSUE TITLE
Egy Dead

### ISSUE THREAD

**Issue by joessef45** [aniyomiorg/aniyomi-extensions#2192]
### Source information

ar.egydead  13.5v

### Source language

العربية/ Arabic

### Source new URL

https://a46.egydead.live/

### Other details

The old domain is broken and not working and there is a new domain which is https://a46.egydead.live/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
You can change the url yourself in extension settings, in Browse -> Anime Extensions, scroll to EgyDead, click "settings" then the gear. From there you can change the url manually.
