### ISSUE TITLE
Fuente de Donghua (Animación china) 

### ISSUE THREAD

**Issue by rodalvis-sys** [aniyomiorg/aniyomi-extensions#2205]
### Source name

ModaGamers

### Source link

https://tiodonghua.com/

### Source language

Español 

### Other details

+18/NSFW = no

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Main site uses dooplay theme, and the `anime` subdomain uses animestream theme

**Comment by rodalvis-sys** [comment]
Disculpa mi ignorancia ¿Que quieres decir con eso?

**Comment by Diegopyl1209** [comment]
> Disculpa mi ignorancia ¿Que quieres decir con eso?

que el tipo que hizo el sitio es re pajero y no le dio la imaginacion para hacer algo original

**Comment by christmovies** [comment]
Estos sitios son complicados de hacer

**Comment by Diegopyl1209** [comment]
> Estos sitios son complicados de hacer

No, Además, me di cuenta de que el subdominio de anime obtiene la información de https://tioanime.com/, que a su vez obtiene datos de https://m.animeflv.net/. Es decir, la persona que realizó esto no se tomó la molestia de obtener la información directamente del sitio original. También, copió el nombre del sitio de donde obtiene datos, que es tioanime Bruh, el don copias le dicen
