### ISSUE TITLE
Rule34video: HTTP Error 403

### ISSUE THREAD

**Issue by 12vince12** [aniyomiorg/aniyomi-extensions#2206]
### Source information

Rule34video 13.6

### Source language

Englisj

### Steps to reproduce

I tried to troubleshoot it but the web view is okay but the extension itself is broken
Tried all possible fix but no avail

### Expected behavior

The webview on it is okay but when playing it on the app itself is having an error403 response code 403

### Actual behavior

Well i can watch anything due to having 403 error tried all of the possible fix for it

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Other details

It also happened to my other phone idk why but it has the same problem error 403

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by XarisZ** [comment]
Same issue. Tried the experimental version as well and its still the same

**Comment by 12vince12** [comment]
Damn i accidentally close it
