### ISSUE TITLE
Change fansub toggle to blacklist/whitelist on Turkish extensions

### ISSUE THREAD

**Issue by glaicodes** [aniyomiorg/aniyomi-extensions#2208]
### Source name

Turkanime TV, Anizm, TR Anime Izle

### Source language

Turkish

### Describe your suggested feature

Currently, It only has enabled and disabled toggle which doesn't help faster loading at all. My suggestion is to add a setting that you can select blacklist or whitelist and all the toggled fansubs are loaded with that setting.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Selected = whitelist
Non-selected = blacklist
You = stupid
