### ISSUE TITLE
gogoanimex (improved gogoanime site)

### ISSUE THREAD

**Issue by Nintenstation** [aniyomiorg/aniyomi-extensions#2213]
### Source name

Gogoanimex

### Source link

https://gogoanimex.to/

### Source language

english

### Other details

This might seem like a shady gogoanime link, but I checked through it and it's a safe and legitimate site from what I can tell. It's basically an improved version of the original gogoanime. I think we'd be able to have both at the same time the same reason we have 2 wco extensions. Thanks in advance!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
It's a mirror of 9anime, which already exists as an extension.
