### ISSUE TITLE
Tao sect

### ISSUE THREAD

**Issue by Mynameluis** [aniyomiorg/aniyomi-extensions#2239]
### Source information

Tao sect 1.4.19

### Source language

PT BR 

### Steps to reproduce

![Screenshot_20230922-212008](https://github.com/aniyomiorg/aniyomi-extensions/assets/145807935/4fb56e58-a249-4d2d-9aba-68845bcb3fbf)
L

### Expected behavior

Abrir normalmente 

### Actual behavior

![Screenshot_20230922-212008](https://github.com/aniyomiorg/aniyomi-extensions/assets/145807935/1ca1934a-55ac-437a-8a59-ab0882d382a9)

### Aniyomi version

App version: 0.14.3-6151 (standard, 43e8dcd1f, 94, 2023-06-15T08:44Z) Android version: 10 (SDK 29) Android build ID: QPZS30.30-Q3-38-69-12 Device brand: motorola Device manufacturer: motorola Device name: guam Device model: moto e(7) plus Device product name: guam_retail

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Meu irmão em cristo, isso é uma extensão de MANGÁ, não de anime; portanto, o bug deveria ser reportado no [Repositório do TACHIYOMI](https://github.com/tachiyomiorg/tachiyomi-extensions).
E segundo que, isso NÃO é um bug da extensão, e sim um problema no site em si; Você pode verificar no próprio site que o capítulo não vai abrir. Espere um pouco e em breve você poderá ler o capítulo.
