### ISSUE TITLE
Hikari scan

### ISSUE THREAD

**Issue by Mynameluis** [aniyomiorg/aniyomi-extensions#2240]
### Source name

Hikari scan

### Source link

https://hikariscan.com.br/

### Source language

PT BR 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We don't manage manga extensions on this repo, and hikari scans [was removed](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6611) per the scanlator's request so it's not going to be added.
