### ISSUE TITLE
Fix player's links

### ISSUE THREAD

**Issue by christmovies** [aniyomiorg/aniyomi-extensions#2249]
### Source information

MundoDonghua

### Source language

Spanish

### Steps to reproduce

Mnbbnnn

### Expected behavior

Nbnbbb

### Actual behavior

Bnnbbnnn

### Aniyomi version

Preview r6151

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Please actually fill in the information that's requested.
