### ISSUE TITLE
Add prívate installer from tachiyomi 

### ISSUE THREAD

**Issue by christmovies** [aniyomiorg/aniyomi-extensions#2250]
### Source name

Jju

### Source language

Hjj

### Describe your suggested feature

Bbnb

### Other details

Nnn

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Please don't create nonsensical issues.
