### ISSUE TITLE
Yomovies broken

### ISSUE THREAD

**Issue by 1YuviKing1** [aniyomiorg/aniyomi-extensions#2254]
### Source information

Saying failed to fetch the video

### Source language

Hindi

### Steps to reproduce

Do no

### Expected behavior

Do no

### Actual behavior

Popping up failed to fetch the video then back to ep screen
![Screenshot_20230924_131453_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/112407714/03dcb4ce-71b3-493d-abd6-97c67ff060a0)
![Screenshot_20230924_131404_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/112407714/6b71c15a-da21-496a-a691-c9a34aa73477)

### Aniyomi version

Preview r6658

### Android version

Android 11

### Other details

No thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Please fill in _all_ the information that's requested next time
