### ISSUE TITLE
KAA  failed to fetch video.

### ISSUE THREAD

**Issue by Awesome509** [aniyomiorg/aniyomi-extensions#2259]
### Source information

KickAssAnime 13.33

### Source language

English 

### Steps to reproduce

1. Go to Tokyo Ghoul s1
2. Try to watch any episode 
3. It will fail to fetch videos

### Expected behavior

Normally I would be able to click on any episode and be able to watch it.

### Actual behavior

It instead says "Failed to fetch videos"

### Aniyomi version

Preview r6151 and 0.12.3.10

### Android version

Andriod 13

### Other details

Keep in mind It fails to fetch for some anime so some anime will work. Tokyo ghoul Is not the only anime that it fails to fetch video on.
Domain in use is kickassanime.am

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Awesome509** [comment]
![Screenshot_20230925_083517_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/122478774/150e3f66-ec35-4062-8b10-0b0cd6cc2d98)
![Screenshot_20230925_083530_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/122478774/f65c133a-e5ac-4ee8-bcd5-f4f4146ed463)

**Comment by LittleFreak** [comment]
Got the same issue with another anime; even when it just worked in webview
