### ISSUE TITLE
Anime-Sama Broken

### ISSUE THREAD

**Issue by Urbexed** [aniyomiorg/aniyomi-extensions#2283]
### Source information

Anime-Sama (13.4)

### Source language

French

### Steps to reproduce

Open the Anime-Sama extension or an anime from it

### Expected behavior

Show available anime or play selected anime 

### Actual behavior

No results/unable to play

### Aniyomi version

Animiru (0.15.2.3)

### Android version

12

### Other details

The site was down for several days, something must have changed since it came back online

The site address is the same as before 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
There isn't any version called "Latest" and "Last Animiru" doesn't say anything about which version it is. Please edit your issue with the exact numerical versions of both the extension and app.

**Comment by Urbexed** [comment]
> Il n'existe aucune version appelée "Latest" et "Last Animiru" ne dit rien sur la version dont il s'agit. Veuillez modifier votre problème avec les versions numériques exactes de l'extension et de l'application.

It's modified 🤡
