### ISSUE TITLE
website wit anime 

### ISSUE THREAD

**Issue by 3bakri** [aniyomiorg/aniyomi-extensions#2289]
### Source name

wit anime 

### Source language

Arabic 

### Source link

https://witanime.rest/

### Other details

This site never works, please update it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by 3bakri** [comment]
Sorry, the site does not work in the application at all

**Comment by Secozzi** [comment]
Please use the correct issue template

**Comment by 3bakri** [comment]
sorry. It's my fault.
