### ISSUE TITLE
Yomiroll duplicate Spanish(América Latina)

### ISSUE THREAD

**Issue by christmovies** [aniyomiorg/aniyomi-extensions#2306]
### Source information

Yomiroll

### Source language

All

### Steps to reproduce

Extension config, sub and audio language, search spanish(América Latina)

### Expected behavior

Only the firts

### Actual behavior

The second doesnt work

### Aniyomi version

Preview r6151

### Android version

13

### Other details

Delete the second Spanish(América Latina) because doesnt work, is duplicate language 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by imper1aldev** [comment]
The title is the same ("Spanish (Latin America)") but the "key" that it represents internally in the programming is different, some anime on Crunchy are linked to the key "es-419" and others the key "es-LA", therefore, both are functional but in different situations.
