### ISSUE TITLE
Ongoing Anime labelled as completed in yomiroll

### ISSUE THREAD

**Issue by Sadwhy** [aniyomiorg/aniyomi-extensions#2326]
### Source information

Yomiroll 13.24

### Source language

Multi

### Steps to reproduce

1. Find an ongoing anime
2. Add it to library

### Expected behavior

Be labelled as ongoing 

### Actual behavior

Is labelled completed 

### Aniyomi version

Preview r6668

### Android version

Android 13

### Other details

This wouldn't have been a problem but the latest preview added a new feature called "Show next episode's airing time". Problem is that even if the anime is currently releasing, if the sources mislabel it as completed the app would also think it's completed and won't display the airing date.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
I suppose it's an API issue? You can switch the status with _edit info_ for now.

**Comment by Secozzi** [comment]
The extension sets the "Completed" status to every single anime, regardless of what the API says. Also, "edit info" is an Animiru exclusive feature.

**Comment by Sadwhy** [comment]
I was on a wild goose hunt trying to find the edit info button. Should I open an issue in the main app to suggest that regardless of what the sources says if the tracker has any kind of airing data it would just show it? But that was take a hella long time to be implemented.

**Comment by Secozzi** [comment]
The next airing data was hidden for completed anime to a) lessen the load for anilist and b) hide it for sources that splits up an entry differently from the tracker. This is an issue with the extension assigning the wrong status, not that the app hides it when it shouldn't.

**Comment by Sadwhy** [comment]
> The next airing data was hidden for completed anime to a) lessen the load for anilist and b) hide it for sources that splits up an entry differently from the tracker. This is an issue with the extension assigning the wrong status, not that the app hides it when it shouldn't.

I zee what it is

**Comment by LittleFreak** [comment]
> The extension sets the "Completed" status to every single anime, regardless of what the API says. Also, "edit info" is an Animiru exclusive feature.

It's so handy, that I assumed the origin would be aniyomi. My bad, since I switched from Aniyomi>Animiru>Kuukiyomi ^^
