### ISSUE TITLE
Legión sacn cambio a un nuevo dominio llamado Cerberus series 

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi-extensions#2343]
### Source information

Legion scan 1.4.32

### Source language

Español 

### Source new URL

https://cerberuseries.xyz/

### Other details

No hay

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We don't manage manga extensions, so this should go to tachiyomi. However, there's already an [open issue](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/17862) for it so just wait until they address it.
