### ISSUE TITLE
Hagan algo para arreglar la navegación en olympus scan

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi-extensions#2344]
### Source name

Olympus scanlation 1.4.4

### Source language

Español 

### Describe your suggested feature

Pq olympus cambio de dominio y actualizo su interfaz ahora no puedo navegar para ver todos los reciéntes o populares así que pido que se le pongan filtros a la extensión que me permitan disfrutar y visualizar todo su contenido y también con dragon translation 

### Other details

No hay

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We don't manga extensions here, make sure the issue still happens when using the tachiyomi app and report it to [their repo](https://github.com/tachiyomiorg/tachiyomi-extensions)
