### ISSUE TITLE
Can't download Aniwave

### ISSUE THREAD

**Issue by PHBN1964** [aniyomiorg/aniyomi-extensions#2355]
### Source information

AniWave 13.53

### Source language

English

### Steps to reproduce

1.Enter Aniwave
2.choose Anime
3. Download Episode

### Expected behavior

Download the episodes

### Actual behavior

I can't download Any episode from the source
It says Failed to Fetch video

### Aniyomi version

12.

### Android version

Android 12 S

### Other details

In AniWave my:
Preferred Domain is AniWave.bz
Preferred Type Sub
Preferred Quality 480p
Preferred Server Mp4Upload
Enabled all Hosts
Enable TypeSub and Soft Sub

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Unable to replicate, please open a new issue and mention which anime, and which episode you're trying to play.
