### ISSUE TITLE
extension request

### ISSUE THREAD

**Issue by aadio7** [aniyomiorg/aniyomi-extensions#2359]
### Source name

streamflix

### Source link

https://streamflix.in/

### Source language

Multi

### Other details
when we go their website we got the app ..so idk if we can get ext of an app.. its kind of ntflix(NF) mirror with a content with more than  3 or 4 audio lang and quallity is also good..and its also contain some content from different source other than ntflix(NF) also

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Have you actually tried it?
Because the website raises a big red flag for me 🤔

**Comment by aadio7** [comment]
> Have you actually tried it? Because the website raises a big red flag for me 🤔

Idk but on there group they tell that they will remove some permission they want on the app
