### ISSUE TITLE
[Bug] <DreamSub>: <Find anything>

### ISSUE THREAD

**Issue by MaMMM7** [aniyomiorg/aniyomi-extensions#236]
## Device information
- Tachiyomi version: 0.12.3.6
- Android version: 11

## Source information
- Name: DreamSub
- Extension version: 12.1

## Steps to reproduce
Update anime library

### Expected behavior
Find the new episodes that are already online on the site.

### Actual behavior
Despite the episode are online on the corrispective site the app doesn't find anything.

**Comment by Samfun75** [comment]
Closing as there is no extension by that name anymore.
