### ISSUE TITLE
auto-download not working

### ISSUE THREAD

**Issue by enersenx** [aniyomiorg/aniyomi-extensions#2384]
### Source information

all sources

### Source language

English 

### Steps to reproduce

1. enable auto-download while reading for next 2 unread chapters
2. downloaded current and next chapters of a manga
3. Read current and next chapters

### Expected behavior

next 2 unread chapters should be downloaded

### Actual behavior

the next 2 unread chapters didn't get downloaded and are not added in queue

### Aniyomi version

Preview r6670

### Android version

android 13

### Other details

I've tried this with multiple sources but the issue is the same.
I've tried this on tachiyomi but the tachiyomi app behaves normally.
The issue seems to be with aniyomi.
I have a Samsung S20+ SM-G986B/DS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
>- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
