### ISSUE TITLE
AnimeTV domain changed

### ISSUE THREAD

**Issue by SNoNameS** [aniyomiorg/aniyomi-extensions#2389]
### Source information

AnimeTV 12.1

### Source language

Brazilian Portuguese

### Source new URL

https://atv2.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
forgot to close with #2458
tee hee
