### ISSUE TITLE
Nhentai claudeflare troubleshooting

### ISSUE THREAD

**Issue by Ussop141** [aniyomiorg/aniyomi-extensions#2398]
### Source information

Nhentai 1.4.39 (Multi)

### Source language

Multi

### Steps to reproduce

![Screenshot_20231019_125724](https://github.com/aniyomiorg/aniyomi-extensions/assets/125413104/950dbc35-87a3-40be-b58b-c46a8d998585)

### Expected behavior

I should be able to access the extension but for some reason i can't

### Actual behavior

I can't access it when ever i check the the box in claudeflare it says Failure

### Aniyomi version

Preview r6670

### Android version

Android 11

### Other details

If possible could you try to replace the source to nhentai.to but if the issue is fixed then no need to do it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Read the cloudflare section in the troubleshooting guide that you acknowledged you read. If it doesn't work, migrate to other sources or wait until they lower their protection.
