### ISSUE TITLE
Add "consumybili" again if possible

### ISSUE THREAD

**Issue by Imtiyaz744** [aniyomiorg/aniyomi-extensions#2404]
### Source name

Bilibili/Consumybili

### Source link

https://www.bilibili.tv/

### Source language

English, Japanese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
As for the Source Language: [BiliBili is now available in Indonesia, the Philippines, Thailand, Vietnam, Singapore, and Malaysia. In Indonesia](https://www.bilibili.tv/en/about)

**Comment by SinchanBanerjee-tech** [comment]
Yeah seriously needed! Anyone from the devs, please assign to this task.
