### ISSUE TITLE
No muestra todos los capitulos

### ISSUE THREAD

**Issue by Latinlee** [aniyomiorg/aniyomi-extensions#2410]
### Source information

MetroSeries 13.1 

### Source language

Español

### Steps to reproduce

1. Abrir aniyomi
2. Buscar globalmente "Kuzey Güney" 
3. Seleccionar "Kuzey Güney"

### Expected behavior

Deberia mostrar todos los capitulos de cada temporada.

### Actual behavior

Solo muestra los primeros 12 capitulos de cada temporada.

### Aniyomi version

Preview r6678

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by imper1aldev** [comment]
@Latinlee This bug has been fixed in the latest update. (En la última actualización se ha solucionado este error.)
