### ISSUE TITLE
Cambiaron el dominio de Taurus fansub 

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi-extensions#2413]
### Source information

Taurus fansub 1.4.31

### Source language

Español 

### Source new URL

https://taurusmanga.com/

### Other details

Simplemente les pido que arreglen esto lo más rápido posible por favor 🙏🙁

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by imper1aldev** [comment]
@Alex178190282 Te equivocaste de repositorio aquí solo se piden cambios que sean relacionados a los plugins de Aniyomi (plugins de video), los plugins que tengan que ver con Manga se piden en el repositorio de Tachiyomi, no aquí
