### ISSUE TITLE
Dual/multi and english extensions(🐐)

### ISSUE THREAD

**Issue by aadio7** [aniyomiorg/aniyomi-extensions#2421]
### Describe why this should be added

Seen a lot of request for a lot of website which are too much similar soo instead of these ..aniyomi could give priority to below
1. UHDmovies: solving the bug in #2353  and adding more category other than home
2. Mkvcinemas: best quality and large no of content already requested in #2374 (🐐)
3. Vegamovies: requested in #2180  along with  https://dotmovies.tattoo/ (its bollywood category in vega which redirect to dotmovies website)
4. Olamovies- https://olamovies.tokyo/ best quality and big catalog(🐐)
5. moviemod-already request in #1791 

### Other details

Give priority to these will be the best instead of adding websites with similar catalog and quality 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open (or closed) issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Please only open one issue per source. And no, we won't give any issue "priority" over others, this is all volunteer work and stuff will only be worked on when and if someone feels like volunteering to work on it.

**Comment by aadio7** [comment]
> Please only open one issue per source. And no, we won't give any issue "priority" over others, this is all volunteer work and stuff will only be worked on when and if someone feels like volunteering to work on it.

I did this for enchancement of the app i.e. quality>quantity  ...

**Comment by Secozzi** [comment]
What I said still stands regardless

**Comment by aadio7** [comment]
> What I said still stands regardless

 only thing i can do is to open seperate source request for ola and moviesmod and wait till someone makes it
