### ISSUE TITLE
Aniwave not working

### ISSUE THREAD

**Issue by hanconel** [aniyomiorg/aniyomi-extensions#2425]
### Source information

Aniwave

### Source language

English

### Steps to reproduce

Watch anime or update new anime released episode from Aniwave extention.

### Expected behavior

Play video / update new anime episode 

### Actual behavior

Doesn't play video - "Error 404" or update new anime release - "Failed to bypass Cloudfare" 

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Follow the cloudflare section in the troubleshooting guide that you acknowledged you've read. If it doesn't help, wait until they lower protection or migrate to another extension.
