### ISSUE TITLE
Fmovies: Videos not playing

### ISSUE THREAD

**Issue by BoakyeDarlington** [aniyomiorg/aniyomi-extensions#2427]
### Source information

Fmovies 13.14

### Source language

English

### Steps to reproduce

1. when i play the movie it says expected task of the object
2. When i tried to download it says video list is empty
![Screenshot_20231027_041601_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi-extensions/assets/148963963/b35bd4e6-02b2-47ab-bc59-2f603b71eaab)

### Expected behavior

Since the site of the extension works the app should able to operate well cause aniyomi scrape scrapped movies from a website

### Actual behavior

![Screenshot_20231027_041601_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi-extensions/assets/148963963/a43043a2-05e5-4651-9b7c-d6a44aedd0b6)

### Aniyomi version

Preview r6678

### Android version

Android 11

### Other details

![Screenshot_20231027_041601_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi-extensions/assets/148963963/e068a89e-a1f9-47fc-9d24-f384fb18f904)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closing in favour of #2529
