### ISSUE TITLE
Add FrAnime 

### ISSUE THREAD

**Issue by EnzoD33300** [aniyomiorg/aniyomi-extensions#2431]
### Source name

FrAnime

### Source link

https://franime.fr/

### Source language

French

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by hollowshiroyuki** [comment]
*bruh*

**Comment by Secozzi** [comment]
This extension already exists with the name `FrAnime` under the French section.
