### ISSUE TITLE
Gogoanime extension not working 

### ISSUE THREAD

**Issue by Rahancy** [aniyomiorg/aniyomi-extensions#2453]
### Source information

Gogoanime 13.76

### Source language

English 

### Steps to reproduce

Open an entry to anime 
Opens an episode doesn't work.
Says video list is empty.
Download doesn't work either 

### Expected behavior

Video starts to play

### Actual behavior

Exits the player 

### Aniyomi version

Preview 6678

### Android version

Android 6

### Other details

It started happening after updating the extention from gogoanime 13.67 to gogoanime 13.76 . And can't find older extension versions 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Unable to replicate, please answer _all_ of the questions below:

1. What BaseUrl do you have in extension settings? (Extension settings are in `Browse -> Anime Extensions -> click on "Settings" for Gogoanime -> click the gear`
2. Which hosts do you have enabled in extension settings?
3. Which anime & episode did you try? Please give a specific answer

**Comment by Secozzi** [comment]
Closing due to a lack of both a response and information. Open a new issue with the above questions answered if you still have problems
