### ISSUE TITLE
(Yomiroll)The audio option does not appear in Latin Spanish

### ISSUE THREAD

**Issue by josefredohd** [aniyomiorg/aniyomi-extensions#2468]
### Source information

Yomiroll

### Source language

Spanish

### Steps to reproduce

I can't choose the audio in Latin Spanish and on the official crunchyroll website it is available in the death note anime. I can only choose Japanese audio.

### Expected behavior

That you can choose audio in Latin Spanish

### Actual behavior

I can only choose Japanese audio

### Aniyomi version

Preview r6691

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
This might be to late but the extension only loads, the default jpn, eng and the language selected in proffered sub setting. If you have not picked spanish in the settings, it will not show up in the player.

If it's still a problem update both app & extension and try again. if it doesn't work update the details and re-open the issue.
