### ISSUE TITLE
Hstream is not working.

### ISSUE THREAD

**Issue by irukairu** [aniyomiorg/aniyomi-extensions#2471]
### Source information

Hstream 13.5 (english)

### Source language

english

### Steps to reproduce

1: First select Hstream in the Browse -> Animation Source screen.

### Expected behavior

A list of animations should appear.

### Actual behavior

http error 404 ~ is displayed.

### Aniyomi version

0.12.3.10

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Same here, Webview works though.

**Comment by Omnipotent-Coder** [comment]
Same here, webview works just fine but it doesn't work in the app as it should.
