### ISSUE TITLE
StreamingCommunity Not start video

### ISSUE THREAD

**Issue by Rufusnightly** [aniyomiorg/aniyomi-extensions#2477]
### Source information

StreamingCommunity 13.2

### Source language

Italiani

### Source new URL

Not changed

### Other details

base override URLs fixed, cache cleaned, cookies, WebView data and restarted, movies and series are all visible, but none of them start, please fix streamcommunity.at in a webview work
![Screenshot_2023-11-07-03-43-36-42_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi-extensions/assets/148594216/9d14eeef-8b20-4395-9ad1-d103345eba88)
![Screenshot_2023-11-07-03-43-59-67_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/aniyomiorg/aniyomi-extensions/assets/148594216/d8314748-80c2-46a8-b62e-d3689b330aad)
![IMG_20231107_034447](https://github.com/aniyomiorg/aniyomi-extensions/assets/148594216/8633c974-ebb8-4d01-a519-dc5257a28a6c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by abracadabra32** [comment]
So has the domain changed?
Because with the new domain (".care") does the same thing
