### ISSUE TITLE
Aniwave malfunctioning (Search + Stream)

### ISSUE THREAD

**Issue by ahykono** [aniyomiorg/aniyomi-extensions#2483]
### Source information

Aniwave 13.57

### Source language

English

### Steps to reproduce

1. Open Aniyomi
2. Go to browse tab
3. Open Aniwave
5. Try searching for an anime or watch an episode of any series
6. It will return an error

### Expected behavior

Should return a list with anime titles matching my search query or stream the episode I'm watching 

### Actual behavior

Returns an error

### Aniyomi version

0.14.6-6678

### Android version

Android 13

### Other details

![Screenshot_20231108_134123_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/74881934/4b7becd6-52fb-4d9c-8c4c-cbdcfa61981c)
Webview works fine, I've checked so it is a problem with the extension itself

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Nintenstation** [comment]
Same problem

**Comment by LyuboA31** [comment]
Aniwave dosnt work at all

**Comment by ahykono** [comment]
> Aniwave dosnt work at all

Thanks for mentioning that, I've updated my issue accordingly.

**Comment by JohnKirk1337** [comment]
Same for FMovies. Exact same error.

**Comment by XanXus96** [comment]
this should still be open as the stream isn't working because AniwaveUtils still uses 9anime.eltik.net (wich is down) to get the source

**Comment by ahykono** [comment]
> 9anime.eltik.net is down

So it was also a source problem in the end, I tried visiting that site previously, it seemed weird why I only saw just an apache homepage

**Comment by jmir1** [comment]
> > 9anime.eltik.net is down
> 
> So it was also a source problem in the end, I tried visiting that site previously, it seemed weird why I only saw just an apache homepage

I think 9anime.eltik.net used to be a service by a fellow FOSS developer who had to stop hosting it due to a complain he received. Correct me if I'm wrong @aniyomiorg/extensions

**Comment by ashazalzaman** [comment]
Same it doesn't work

**Comment by LittleFreak** [comment]
With the latest extension update, streams are working again, but I still see javlang errors resulting into a failed download.

**Comment by LittleFreak** [comment]
Issue resolved

**Comment by XanXus96** [comment]
> Issue resolved

no it's not

**Comment by LittleFreak** [comment]
> > Issue resolved
> 
> no it's not

It's not? With aniwave 13.58, I can stream almost every anime without any issues.

**Comment by Nintenstation** [comment]
> > > Issue resolved
> > 
> > no it's not
> 
> It's not? With aniwave 13.58, I can stream almost every anime without any issues. The search works also just fine. 

What are your settings in the aniwave extension? It still shows the 404 error to me, but perhaps you have different settings on, hence it works. Thanks in advance.

**Comment by LittleFreak** [comment]
> What are your settings in the aniwave extension? It still shows the 404 error to me, but perhaps you have different settings on, hence it works. Thanks in advance.

Have you tried a different domain?
![Screenshot_20231115_042138_Kuukiyomi.png](https://github.com/aniyomiorg/aniyomi-extensions/assets/53310735/45159d9e-f896-4b74-9d06-6e29cc784f9d)

**Comment by Nintenstation** [comment]
> > What are your settings in the aniwave extension? It still shows the 404 error to me, but perhaps you have different settings on, hence it works. Thanks in advance.
> 
> Have you tried a different domain?
> ![Screenshot_20231115_042138_Kuukiyomi.png](https://github.com/aniyomiorg/aniyomi-extensions/assets/53310735/45159d9e-f896-4b74-9d06-6e29cc784f9d)
> 
> 

I tried a different domain, didn't work. I tried the settings on your photo, and it still doesn't work! But thanks for it. Interesting though.

**Comment by LittleFreak** [comment]
> I tried a different domain, didn't work. I tried the settings on your photo, and it still doesn't work! But thanks for it. Interesting though.
Does your selected domain load in your browser? 
Have you updated aniwave to 13.58?

**Comment by Nintenstation** [comment]
>  > I tried a different domain, didn't work. I tried the settings on your photo, and it still doesn't work! But thanks for it. Interesting though.
> 
> Does your selected domain load in your browser? 
> Have you updated aniwave to 13.58? 

Did both, still not working

**Comment by Nintenstation** [comment]
Wait a min, it does work on the preview version!! But not on the stable version, which I prefer... anyway for them to update the stable version?

**Comment by jmir1** [comment]
> Wait a min, it does work on the preview version!! But not on the stable version, which I prefer... any way for them to update the stable version?

The stable version will be replaced with what is now the preview. Sorry if you don't like it but it's impossible to keep the stable version because of various bugs like that. 😅

**Comment by Nintenstation** [comment]
> > Wait a min, it does work on the preview version!! But not on the stable version, which I prefer... any way for them to update the stable version?
> 
> The stable version will be replaced with what is now the preview. Sorry if you don't like it but it's impossible to keep the stable version because of various bugs like that. 😅

Oh, that is completely okay! That's actually what I meant, that I'd like if stable would be updated to be like the preview version (although I'm aware preview is for testing and can have bugs and whatnot, so we had to wait).

Anyway, this is such a GOATED android app, and I'll support you guys always! Thanks for the response.
