### ISSUE TITLE
Error al reproducir cualquier video

### ISSUE THREAD

**Issue by Latinlee** [aniyomiorg/aniyomi-extensions#2485]
### Source information

Cuevana 13.25

### Source language

Español

### Steps to reproduce

1. Abrir aniyomi
2. Seleccionar la pestaña "browse"
3. Abrir Cuevana3Eu
4. Reproducir cualquier pelicula

### Expected behavior

Que pueda reproducir cualquier pelicula o serie.

### Actual behavior

No reproduce ninguna pelicula o serie, ademas el reproductor muestra el mensaje "loading failed".

### Aniyomi version

Preview 6691

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by imper1aldev** [comment]
Apparently this kind of error only happens in the Preview version, in the Release version, the extension works correctly. (Why this happens? I don't know)

**Comment by Latinlee** [comment]
I was reviewing and it seems that the extension has trouble connecting with the Doodstream and Streamtape servers, the error message appears only in the movies that only those two servers have. 
In other movies that have more servers such as Jhon Wick, he has no problem reproducing.

**Comment by Dark25** [comment]
> I was reviewing and it seems that the extension has trouble connecting with the Doodstream and Streamtape servers, the error message appears only in the movies that only those two servers have. In other movies that have more servers such as Jhon Wick, he has no problem reproducing.

What movies are they in?

**Comment by Latinlee** [comment]
> > I was reviewing and it seems that the extension has trouble connecting with the Doodstream and Streamtape servers, the error message appears only in the movies that only those two servers have. In other movies that have more servers such as Jhon Wick, he has no problem reproducing.
> 
> What movies are they in?

![Screenshot_2024-01-27-11-50-44-139_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi-extensions/assets/102179835/20328178-c11e-4fd1-b0cd-ba1d87eac733)

**Comment by Latinlee** [comment]
The problem was already solved, it was as simple as changing the default server of Cuevana.
