### ISSUE TITLE
Jellyfin Hikari broken

### ISSUE THREAD

**Issue by rafieurif** [aniyomiorg/aniyomi-extensions#2488]
### Source information

Jellyfin

### Source language

Multi

### Steps to reproduce

1. enter the extension settings then enter this adress in host URL :  https://watch.hikari-anime.com and login to your account
2. in select media library, select anime
3. try launching any animes, it will lend you back to the episode selection and will prompt a error message.

### Expected behavior

the anime should play.

### Actual behavior

it doesn't play and lend you back to the episode selection.

### Aniyomi version

Preview r6691

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
I just tried it and the problem seem to have resolved itself. Please open a new issue if you still have problems.
