### ISSUE TITLE
JavGuru: List  is empty

### ISSUE THREAD

**Issue by totiha** [aniyomiorg/aniyomi-extensions#2489]
### Source information

JavGuru

### Source language

Multiple

### Steps to reproduce

1. Saving a video inthe library
2. Downloading the video

### Expected behavior

This should happen (and happened only 2 times): the video is downloaded 

### Actual behavior

The download does not start and a notification is shown "List is Empty"

### Aniyomi version

App version: 0.14.6-6691 (standard, 5fd00d4a1, 105, 2023-11-02T23:11Z) Android version: 13 (SDK 33) Android build ID: TP1A.220624.014.M536BXXU4CWHB Device brand: samsung Device manufacturer: samsung Device name: m53x Device model: SM-M536B Device product name: m53xnsxx

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Can you provide an entry which this problem occurs? I've tried downloading in multiple entries, but none of them had this issue.
Maybe it's your internet connection (speed or firewalls).
Screenshot:
![Screenshot_20231109212711](https://github.com/aniyomiorg/aniyomi-extensions/assets/63046606/8fccbd2d-fd04-4b5d-ac46-91cdfcbd22f3)

**Comment by totiha** [comment]
Sure! I will send you a screenshot. For me, all entries give the same
error. When i open it in webview, this emote shows up so i thought the site
was hacked or something

Em qui., 9 de nov. de 2023 21:32, Claudemirovsky ***@***.***>
escreveu:

**Comment by LittleFreak** [comment]
The given entry is probably not available anymore. Haven't had this issue yet during my tries.

**Comment by totiha** [comment]
Thanks for trying! I'll just roll with it, thanks for answering too, really
nice.

Em sex., 10 de nov. de 2023 21:38, LittleFreak ***@***.***>
escreveu:
