### ISSUE TITLE
no link available in animekhor

### ISSUE THREAD

**Issue by breakingzero** [aniyomiorg/aniyomi-extensions#2492]
### Source name

AnimeKhor

### Source language

English

### Source link

eu.kanade.tachiyomi.animeextension.en.animekhor

### Other details

video links are not available 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Please use the correct issue template.
