### ISSUE TITLE
Animekhor 

### ISSUE THREAD

**Issue by breakingzero** [aniyomiorg/aniyomi-extensions#2493]
### Source information

Animekhor 13.4

### Source language

English

### Steps to reproduce

when click on any episode the player crash and "Video link not available" dialogue box appears. FTAB
![Screenshot_2023-11-10-15-11-06-184_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi-extensions/assets/122086091/603f5650-1f1b-4f12-be8d-ed60d8f4bb3c)

### Expected behavior

NA

### Actual behavior

NA

### Aniyomi version

0.12.03.10

### Android version

Android 11

### Other details

![Screenshot_2023-11-10-15-11-06-184_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi-extensions/assets/122086091/e6d33d3e-25ca-45a4-ab8c-abde8ad6ae20)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Have you blocked ok.ru by any chance?

**Comment by fakebhai** [comment]
I tried, first it said no list then I opened webview and checked again and it worked. maybe cookie issue of some sort? overall works fine for me now.
maybe try refreshing your list and check your webview. should likely solve it. (assuming you tried all troubleshooting steps)

**Comment by breakingzero** [comment]
> Have you blocked ok.ru by any chance?
> Because the anime I've tried on Animekhor loaded just fine. 

no still not resolved
