### ISSUE TITLE
Haho.moe source does not have settings to change preferred quality.

### ISSUE THREAD

**Issue by ravener** [aniyomiorg/aniyomi-extensions#2494]
### Source information

haho.moe 13.8 (English)

### Source language

English

### Steps to reproduce

The video player can change quality just fine but there's no preferences screen to change the preferred quality for downloading.

### Expected behavior

There should be extension settings to change preferred quality.

### Actual behavior

There isn't one implemented yet.

### Aniyomi version

0.12.3.10

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ravener** [comment]
@jmir1 @Claudemirovsky Thanks for the fast update but it seems to be completely broken on the latest stable version, on the preview it mostly works but some titles keep giving a NullPointerException when loading the episodes list.

**Comment by Claudemirovsky** [comment]
Magnificient, i'll fix this regression after today's exams.
Btw, can you share a example of entry where the episode list fails? When I tested it, none gave this error (and that's why I pushed it).

**Comment by ravener** [comment]
> Btw, can you share a example of entry where the episode list fails? When I tested it, none gave this error (and that's why I pushed it).

Seems to happen to most of the entries in the popular list, but If I have to pick one to demonstrate:

![Screenshot_20231112_220125_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi-extensions/assets/31079629/b12d0231-0161-4009-b9be-d9a31543c753)

**Comment by Claudemirovsky** [comment]
> Seems to happen to most of the entries in the popular list, but If I have to pick one to demonstrate:
> [ Screenshot with Majo no Kekkyoku ]

Thanks, could confirm. This should be fixed in #2507.
Btw, nice felix pic in your profile :+1:

**Comment by ravener** [comment]
Can confirm that fixed it, also works on the non-preview version now. 👍
