### ISSUE TITLE
Fix AnimePahe episodes naming

### ISSUE THREAD

**Issue by chakibchemso** [aniyomiorg/aniyomi-extensions#2502]
### Source information

AnimePahe - latest

### Source language

English

### Steps to reproduce

1. Add an anime from AnimePahe

### Expected behavior

Episodes should have their appropriate names formated as follows:
Episode {num}: {name}

### Actual behavior

All episodes are just numbered like so:
Episode 1
Episode 2
...

### Aniyomi version

latest - Preview and Stable

### Android version

Android 13 - OneUI 5.1

### Other details

![SmartSelect_20231111_122353_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/41765106/ce0fff4b-bd96-455a-9449-a0069eac96b2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This isn't a bug since animepahe doesn't provide episode names, at least for the anime you specified
