### ISSUE TITLE
UHDMovies 2.0

### ISSUE THREAD

**Issue by BinXyX** [aniyomiorg/aniyomi-extensions#2505]
### Source name

VegaMovies 2.0

### Source link

https://m.vegamovies.care/

### Source language

English

### Other details

It is just like the UHDMovies source. And is good alternative if the UHDMovies source is not working.
![Screenshot_20231111_152825_Chrome](https://github.com/aniyomiorg/aniyomi-extensions/assets/150561181/a7f72332-6a04-46a5-aba0-d5f1e355f902)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Duplicate of #2180
