### ISSUE TITLE
edytjedhgmdhm content missing

### ISSUE THREAD

**Issue by aadio7** [aniyomiorg/aniyomi-extensions#2509]
### Source information

 edytjedhgmdhm

### Source language

En

### Steps to reproduce

1. Open aniyomi
2. Search any content available on edytjedhgmdhm website in extension.. it may not be available
3. Maybe reuploading all content again or there is  some other website for samething(https://odd-bird-1319.zwuhygoaqe.workers.dev/)

### Expected behavior

It would be expected that all the movies/tvs at https://edytjedhgmdhm.abfhaqrhbnf.workers.dev/ will be available and shown in the extension

### Actual behavior

Whereas a lot of tvs/movies are not even available and not come also in search ... i cant specify how many and which ones ... 

### Aniyomi version

0.12.3.10

### Android version

Android 12

### Other details

It dont show all the content uploaded on the website ... a lot missing in extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Unable to replicate, can you give an example?

**Comment by aadio7** [comment]
> Unable to replicate, can you give an example?

I think i can only find tvs content ... whole movies folder is missing (ex: dark knight,gangubai kathiawadi,...)

**Comment by Secozzi** [comment]
Use the filter to search for movies.

**Comment by aadio7** [comment]
> Use the filter to search for movies.

Okk thanks got it

**Comment by aadio7** [comment]
> Use the filter to search for movies.

This site showing error due to rate limits of site owner.. but the second url(https://odd-bird-1319.zwuhygoaqe.workers.dev/) is still working ... so maybe you can fix that if the site rate limits dont get solved
