### ISSUE TITLE
Requesting for a source almost like aniwave

### ISSUE THREAD

**Issue by barbielain** [aniyomiorg/aniyomi-extensions#2512]
### Source name

Anix

### Source link

https://anix.to

### Source language

english

### Other details

A new source just like aniwave since aniwave is down.

It can be added, since ive noticed aniwave takes their videos and sources largely from here. Its almost like aniwave, even the servers

I hope it gets added, if not, i hope aniwave gets fixed soon. Thank you guys for your hard work!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
It's a mirror of aniwave, which already exists as an extension.

**Comment by barbielain** [comment]
oh okay, can i know the name of the extension so that i can install it?

**Comment by Secozzi** [comment]
As I just said, it's a mirror of **aniwave**
