### ISSUE TITLE
No reproduce ningun episodio

### ISSUE THREAD

**Issue by Latinlee** [aniyomiorg/aniyomi-extensions#2514]
### Source information

AnimeLatinoHD

### Source language

Español

### Steps to reproduce

1. Abrir aniyomi
2. Abrir animeLatinoHD
3. Buscar cualquier anime por ejemplo Cowboy bebop
4. Reproducir cualquier capitulo

### Expected behavior

Deberia reproducir cualquier capitulo de cualquier anime

### Actual behavior

No reproduce ningun video y muestra el mensaje "video list is empty".

### Aniyomi version

Preview 6691

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
Shouldn't issues be opened in English??

**Comment by Secozzi** [comment]
Issues can be made in any language

**Comment by Latinlee** [comment]
Aparentemente ya se arreglo el problema
