### ISSUE TITLE
HDFilmCehennemi: Download bug

### ISSUE THREAD

**Issue by Lenkalul** [aniyomiorg/aniyomi-extensions#2527]
### Source information

HDFilmCehennemi 13.6 tr

### Source language

Turkish 

### Steps to reproduce

1. Open the movie you want to download on HDFilmCehennemi
2. Download the movie

### Expected behavior

The movie must be downloaded in the selected quality and with subtitles.

### Actual behavior

Even though it has subtitles on its site, it downloads the movie dubbed and as a trailer or in very low quality.

### Aniyomi version

Preview r6691

### Android version

Android 11

### Other details

Although my internet is fast, it downloads movies in low quality or only as trailers. it also downloads some movies without subtitles even though there are subtitles on the site. 
When we want to download movies on Aniyomi, it would be nice if we could choose subtitles-dubbing and movie quality.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Was it not fixed with the 13.7 update of the extension?
