### ISSUE TITLE
Fmovies error

### ISSUE THREAD

**Issue by Nintenstation** [aniyomiorg/aniyomi-extensions#2529]
### Source information

FMovies 13.14 

### Source language

English

### Steps to reproduce

Surprised no one made a thread about it, but I guess not many people use this app for non-anime stuff. Basically, the Fmovies extension is broken and I'm wondering if it can be fixed. The choices of movies and shows do load, but you can't load them at all.

### Expected behavior

It should show the episodes and videos for the movie/show... but instead....

### Actual behavior

This happens, which was a similar issue on the aniwave extension a few days earlier
![Screenshot_20231119_154446_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/110612128/3453cc00-4503-44e4-91cf-120963e74d74)

### Aniyomi version

Both Stable 0.12.3.10 and Preview r6691

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by JohnKirk1337** [comment]
![Screenshot_20231129_083406_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/59065439/3b435e7c-2076-4a3c-8c81-133f41cf152b)
Same here. 

Android 13. Tried logging in, reinstalling, changing the useragent, etc. But alas, t'was to no avail.
