### ISSUE TITLE
Animes Vision

### ISSUE THREAD

**Issue by Mynameluis** [aniyomiorg/aniyomi-extensions#2533]
### Source information

13.21

### Source language

PT BR

### Source new URL

https://tanoshi.digital/

### Other details

O link que está no momento na extensão não está funcionando
Eles disponibilizou esse novo link
Não sei se o problema e só temporário ou não

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
Yes you're right

**Comment by Claudemirovsky** [comment]
The problem was temporary and it's already solved, so a url change isn't needed anymore.
