### ISSUE TITLE
Arreglan la extensión de Olympus cambio de sitio 

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi-extensions#2537]
### Source information

Olympus scanlation 1.4.5

### Source language

Español

### Source new URL

https://olympusvisor.com/

### Other details

Lo que dice el título por favor 🐳❤️‍🩹✨

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
As you've been told plenty of times before, do not open issues related to manga extensions at this repository. Make sure the issue is reproducible on Tachiyomi and open an issue at their extensions repo.
