### ISSUE TITLE
Gogoanime (EN) changed domain

### ISSUE THREAD

**Issue by Radishell** [aniyomiorg/aniyomi-extensions#2548]
### Source name

Gogoanime(EN)

### Source language

English

### Source link

https://gogoanimehd.io/

### Other details

Opening the website leads to a message where it states that they changed their domain to a new one.

![Screenshot_2023-11-25-00-10-20-519-edit_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi-extensions/assets/151973606/793ca1be-2cf5-42f2-891b-49245bc0fb7a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by memejames** [comment]
Where can I download the new domain one?

**Comment by Dsdevil23** [comment]
How to get access to the new domain Anitaku.io

**Comment by avinave14102001** [comment]
Please solved this problem 
Gogoanime is a change domain so aniyomi library in bookmarking of anime as be not opening they showing

Source link in this showing
https://gogoanimehd.io/

But they showing this open the link 
![285553115-793ca1be-2cf5-42f2-891b-49245bc0fb7a](https://github.com/aniyomiorg/aniyomi-extensions/assets/151993381/a0e418ce-3245-4e18-8b57-67c36f4f299f)

**Comment by fakebhai** [comment]
> Please solved this problem 
> Gogoanime is a change domain so aniyomi library in bookmarking of anime as be not opening they showing
> 
> Source link in this showing
> https://gogoanimehd.io/
> 
> But they showing this open the link 
> ![285553115-793ca1be-2cf5-42f2-891b-49245bc0fb7a](https://github.com/aniyomiorg/aniyomi-extensions/assets/151993381/a0e418ce-3245-4e18-8b57-67c36f4f299f)
> 
> 
> I request coming in heart ❤️ please anyone or everyone help to change domain 😭🙏 who created this please provide update this website 🙏🙏🙏🙏

go to gogoanime's extension settings and override the url to "https://anitaku.to" this should make the extension usable

**Comment by avinave14102001** [comment]
> > Please solved this problem
> > Gogoanime is a change domain so aniyomi library in bookmarking of anime as be not opening they showing
> > Source link in this showing
> > https://gogoanimehd.io/
> > But they showing this open the link
> > ![285553115-793ca1be-2cf5-42f2-891b-49245bc0fb7a](https://private-user-images.githubusercontent.com/151993381/285573315-a0e418ce-3245-4e18-8b57-67c36f4f299f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MDIzNDEsIm5iZiI6MTcwMDkwMjA0MSwicGF0aCI6Ii8xNTE5OTMzODEvMjg1NTczMzE1LWEwZTQxOGNlLTMyNDUtNGUxOC04YjU3LTY3YzM2ZjRmMjk5Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQwODQ3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTJmMTNkMGNlZmJhNWY1MWVhODRkM2I5ZTM1ZGY2OTNhNDE1NWNmNzJmYTE0NzI2Yzk0YWVlNTI4YzlmYTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QvJRaDz2XrOegnwM4rvHUbwQNR9MorlaUrgAHp7WRBs)
> > I request coming in heart ❤️ please anyone or everyone help to change domain 😭🙏 who created this please provide update this website 🙏🙏🙏🙏
> 
> go to gogoanime's extension settings and override the url to "https://anitaku.to" this should make the extension usable

Please tell me step by step to used 
How to work

**Comment by Dark25** [comment]
To fix the issue temporarily, follow these steps 

Step 1

![Screenshot_20231125_102752_com.dark.animetailv2.jpg](https://github.com/aniyomiorg/aniyomi-extensions/assets/21024973/d30db584-29c1-47da-af24-4307c2588621)

Step 2

![Screenshot_20231125_102837_com.dark.animetailv2.png](https://github.com/aniyomiorg/aniyomi-extensions/assets/21024973/d1dd494e-71e7-4a15-a0d0-aae8ecf2908a)

Step 3

![Screenshot_20231125_102907_com.dark.animetailv2.png](https://github.com/aniyomiorg/aniyomi-extensions/assets/21024973/dd895dab-95b6-4bd0-bb90-ccca22c61a68)

Step 4

![Screenshot_20231125_102802_com.huawei.smartshot.jpg](https://github.com/aniyomiorg/aniyomi-extensions/assets/21024973/7e09a652-ba1a-4942-8f45-105bc7b2ffaf)
