### ISSUE TITLE
Arreglen las extensiones 

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi-extensions#2552]
### Source information

Metroseries 13.3 olympus scanlation 1.4.6 animeyt.es 13.2 tiodonghua.com 13.2 

### Source language

Español 

### Steps to reproduce

 Entra y dar click a cualquier vaina 

### Expected behavior

Abre la extensiones presenta la portada de todo y sé abren los episodios

### Actual behavior

No se habré los episodios en la fuente de anime y la de serie y manga no carga la portada 

### Aniyomi version

Preview R6691

### Android version

12 hios

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Alex178190282** [comment]
Perdón el autocorrector escribió hijos en vez de HIOS

**Comment by Secozzi** [comment]
Please only create on issue for each source, it makes it easier to keep track of things
