### ISSUE TITLE
Aniwave

### ISSUE THREAD

**Issue by Tochage143** [aniyomiorg/aniyomi-extensions#2553]
### Source information

Aniwave 13.59

### Source language

English

### Steps to reproduce

It show SocketException: Connection reset error 

### Expected behavior

It should show list of anime 

### Actual behavior

![Screenshot_20231126-095535_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/108989114/3a58cbd8-1ae5-413a-86e2-2f5b345abdbd)

### Aniyomi version

Preview arm64-v8a 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Please read the "common issues" section of the troubleshooting guide that you acknowledged you've read. If it doesn't help, use another extension.
