### ISSUE TITLE
[Error] Gogoanime not working

### ISSUE THREAD

**Issue by Cistmist** [aniyomiorg/aniyomi-extensions#2554]
### Source information

Gogoanime 13.77

### Source language

English

### Steps to reproduce

Choose any anime and try to play it or download.

### Expected behavior

Be able to play or download anime

### Actual behavior

Can't play anime nor download.

### Aniyomi version

0.12.3.10

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
What happens when you try? Does any wrror messages show up and if so, what do they say?

**Comment by Cistmist** [comment]
> What happens when you try? Does any wrror messages show up and if so, what do they say?

When I press download, it returns an error "List is empty".

When I press on it to play it, nothing happens. If i try to press the play button again, it gives the loading circle then stops without loading (the pause button which signifies that the video is playing turns to a play button and nothing happens)

**Comment by Claudemirovsky** [comment]
> When I press download, it returns an error "List is empty".

Can you give a example of anime and episode where this happens? So we can reproduce the error and fix it.
Btw, have you checked if it is playing in the site itself?

**Comment by Cistmist** [comment]
> > When I press download, it returns an error "List is empty".
> 
> Can you give a example of anime and episode where this happens? So we can reproduce the error and fix it. Btw, have you checked if it is playing in the site itself?

Just updated the extension. Still doesn't work. All the episodes in the screenshot have that same error. As in can't play them nor download. If I open browser they work fine.
In the browser settings the baseURL is anitaku.to (didn't touch this)

![Screenshot_20231126-183756](https://github.com/aniyomiorg/aniyomi-extensions/assets/49917604/6a16cf1f-4ce7-446a-8667-6f72e24cbb77)

**Comment by Cistmist** [comment]
The greyed out ones are episodes I downloaded previously and watched, this error only started after I updated the extension yesterday.

**Comment by Claudemirovsky** [comment]
> Just updated the extension. Still doesn't work. 

Of course; as I said, the fix wasn't related to this issue.

> All the episodes in the screenshot have that same error.

NOW that's interessing (and strange, considering that it worked perfectly here in the episodes I've tested it). I'll check those episodes soon™️

**Comment by Cistmist** [comment]
> > Just updated the extension. Still doesn't work.
> 
> Of course; as I said, the fix wasn't related to this issue.
> 
> > All the episodes in the screenshot have that same error.
> 
> NOW that's interessing (and strange, considering that it worked perfectly here in the episodes I've tested it). I'll check those episodes soon™️

Can you reference an episode that worked for you so I can cross-check it?

**Comment by Cistmist** [comment]
> > Just updated the extension. Still doesn't work.
> 
> Of course; as I said, the fix wasn't related to this issue.
> 
> > All the episodes in the screenshot have that same error.
> 
> NOW that's interessing (and strange, considering that it worked perfectly here in the episodes I've tested it). I'll check those episodes soon™️

Just tried different shows from different years to see if it's just the newer shows. And only one show didn't return an error but still didn't load.
![Screenshot_20231126-190102](https://github.com/aniyomiorg/aniyomi-extensions/assets/49917604/87ee1941-a400-4b49-9e6b-29b511e2b546)
![Screenshot_20231126-190123](https://github.com/aniyomiorg/aniyomi-extensions/assets/49917604/bc90affe-cccb-4524-9cb6-4857d76ba305)
![Screenshot_20231126-190015](https://github.com/aniyomiorg/aniyomi-extensions/assets/49917604/0bcc6554-e458-4adb-b4c3-6296461c6ec8)

**Comment by Cistmist** [comment]
The third screenshot is from Mitsugoshi colors. It was the only show that didn't return the "Couldn't find video links" error but it still didn't load the video and there was only one video quality.

**Comment by Claudemirovsky** [comment]
> I'll check those episodes soon™️

Results:

Shangri-LA ep 9: Played just fine, in all hosters (FileLions, GogoStream, VidStreaming, StreamWish & Doodstream). Download also worked.

Kimi no koto ga DAI*100 Ep 8: Same as above, Played without any problems and had 0 problems when downloading.

Kusuriya no hitorigoto Ep 8: again, played just fine in all hosters and qualities. And again, had ZERO problems while downloading.

Ragna crimson Ep 9: yet again, played just fine in all servers. Downloading also worked.

Sousou no frieren ep 12: yes, it also worked flawlessy

Tested on Android 11 GO, ArmV7, Aniyomi PREVIEW R6991.

**Comment by Claudemirovsky** [comment]
Considering that **all** episodes tested worked in Aniyomi Preview in my tests, and that they're failing miserably in your aniyomi >stable< (as you said in the issue description), I'd recommend migrating to Preview.

**Comment by Cistmist** [comment]
> > I'll check those episodes soon™️
> 
> Results:
> 
> Shangri-LA ep 9: Played just fine, in all hosters (FileLions, GogoStream, VidStreaming, StreamWish & Doodstream). Download also worked.
> 
> Kimi no koto ga DAI*100 Ep 8: Same as above, Played without any problems and had 0 problems when downloading.
> 
> Kusuriya no hitorigoto Ep 8: again, played just fine in all hosters and qualities. And again, had ZERO problems while downloading.
> 
> Ragna crimson Ep 9: yet again, played just fine in all servers. Downloading also worked.
> 
> Sousou no frieren ep 12: yes, it also worked flawlessy
> 
> Tested on Android 11 GO, ArmV7, Aniyomi PREVIEW R6991.

Just cleared cache and user data of the app. And tried to open them and they work now, so restored my library.

Only problem I have now is that there's only 1080p in the video quality which is too big to download on phone. If possible could you bring back the 360,480, and 720 qualities. 

Note: some episodes only had one option being dood stream which you can't change the quality for.

**Comment by Cistmist** [comment]
![Screenshot_20231126-193253](https://github.com/aniyomiorg/aniyomi-extensions/assets/49917604/98c7bc56-a998-43a8-9567-d7ccba2304ff)
 Screenshot of available qualities.

**Comment by Cistmist** [comment]
> > I'll check those episodes soon™️
> 
> Results:
> 
> Shangri-LA ep 9: Played just fine, in all hosters (FileLions, GogoStream, VidStreaming, StreamWish & Doodstream). Download also worked.
> 
> Kimi no koto ga DAI*100 Ep 8: Same as above, Played without any problems and had 0 problems when downloading.
> 
> Kusuriya no hitorigoto Ep 8: again, played just fine in all hosters and qualities. And again, had ZERO problems while downloading.
> 
> Ragna crimson Ep 9: yet again, played just fine in all servers. Downloading also worked.
> 
> Sousou no frieren ep 12: yes, it also worked flawlessy
> 
> Tested on Android 11 GO, ArmV7, Aniyomi PREVIEW R6991.

Update: still using the stable version. 
I can stream the episodes but they only have 1080p as quality. Downloading though fails.

Previously when this error popped up it was because the downloader prioritized dood stream which used to return fails when downloading. Which was fixed at the time.

**Comment by Claudemirovsky** [comment]
> Screenshot of available qualities.

Again, that's a issue that only exists in Aniyomi Stable: when I tested in it, GogoStream/VidStreaming extractor didn't work, so its videos (with qualities like 480p, 720p, etc) won't show up. Again, I recommend migrating to Preview, as it is much better in general.

**Comment by Cistmist** [comment]
> > Screenshot of available qualities.
> 
> Again, that's a issue that only exists in Aniyomi Stable: when I tested in it, GogoStream/VidStreaming extractor didn't work, so its videos (with qualities like 480p, 720p, etc) won't show up. Again, I recommend migrating to Preview, as it is much better in general.

Yup can confirm that everything works fine on preview. Thanks! Will close this now.
