### ISSUE TITLE
HDFilmCehennemi: Subtitles and audio are not synchronized.

### ISSUE THREAD

**Issue by Lenkalul** [aniyomiorg/aniyomi-extensions#2557]
### Source information

HDFilmCehennemi 13.6

### Source language

Turkish

### Steps to reproduce

1. Open the movie you want to watch on HDFilmCehennemi

### Expected behavior

Watch the selected movie with subtitles, video and sound synchronized.

### Actual behavior

The subtitles, video and audio do not play in sync as they should, and sometimes the subtitles and sometimes the audio play first and the video plays intermittently.

### Aniyomi version

Preview r6691

### Android version

Android 11

### Other details

This problem occurred after the last update of the extension. There was no such problem before.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Have you checked if this happens in the source itself?

By the way, you said that "There was no such problem before", but all the latest update did was add subtitles support to the Rapidrame extractor, which nullifies any correlation with audio synchronization problems or even subtitle problems on other hosters.
