### ISSUE TITLE
Uhdmovies:failed to bypass cloudfare

### ISSUE THREAD

**Issue by aadio7** [aniyomiorg/aniyomi-extensions#2559]
### Source information

Uhdmovies

### Source language

En

### Steps to reproduce

Open aniyomi
Have the uhdmovie extension
Open it 

### Expected behavior

Open the extension 
Then it will show the content and video will play

### Actual behavior

Opening the extension ..
Loads a lot of time .. 
Then show cloudfare bypass error

### Aniyomi version

0.12.3.10

### Android version

Android 12

### Other details

Cloudfare bypass error

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by aadio7** [comment]
Please update this goat website......

**Comment by Secozzi** [comment]
Follow the Cloudflare section in the troubleshooting guide that you acknowledged that you've read. If it doesn't work, wait until they lower their protection or use another extension.

**Comment by aadio7** [comment]
> Follow the Cloudflare section in the troubleshooting guide that you acknowledged that you've read. If it doesn't work, wait until they lower their protection or use another extension.

Already done the first method before posting this issue ... and cant understand the second method...

**Comment by Secozzi** [comment]
Which method are talking about, exactly? And which part is it that you don't understand?

**Comment by aadio7** [comment]
> Which method are talking about, exactly? And which part is it that you don't understand?

Changing user agent ..
What value i have to set in default user agent string

**Comment by aadio7** [comment]
> As the guide says, you might need to try different ones and just see which works. The guide also has a reference list of available user-agents to try.

if that don't work .. Will it not work ..like can't it be fixed by you guys??

**Comment by Secozzi** [comment]
The steps in the guide is the fix, if it doesn't work there's nothing we can do.

**Comment by aadio7** [comment]
> The steps in the guide is the fix, if it doesn't work there's nothing we can do.

Thats sucks ... as mostly good websites adding these🥲

**Comment by aadio7** [comment]
> The steps in the guide is the fix, if it doesn't work there's nothing we can do.

"cloudflare interceptor needs to be added in extension but doesn't gurantees bypass" is it something you can do this by coding??
