### ISSUE TITLE
Old episodes are not downloading 

### ISSUE THREAD

**Issue by MkMinhaj** [aniyomiorg/aniyomi-extensions#2562]
### Source information

Gogoanime 13.72

### Source language

English 

### Steps to reproduce

I want to download the old episodes of Wanmei Shijie anime so that I can watch it anytime while I'll be free. But there is showing some kind of error 

### Expected behavior

Can you please fix this following issue 

### Actual behavior

Download error 

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Other details

Wanmei Shijie old episodes 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by avinave14102001** [comment]
> ### Source information
> Gogoanime 13.72
> 
> ### Source language
> English
> 
> ### Steps to reproduce
> I want to download the old episodes of Wanmei Shijie anime so that I can watch it anytime while I'll be free. But there is showing some kind of error
> 
> ### Expected behavior
> Can you please fix this following issue
> 
> ### Actual behavior
> Download error
> 
> ### Aniyomi version
> 0.12.3.10
> 
> ### Android version
> Android 13
> 
> ### Other details
> Wanmei Shijie old episodes
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
> * [x]  I will fill out all of the requested information in this form.



I am also face same problem old episode are not downloading or new episode are also not downloading 
In gogoanime domain after change a name 
If get solution please tell me

And some help as anime fan I asked very one 

Please see this problem

**Comment by Secozzi** [comment]
When you say "some kind of error", what is the error, exactly? Also, are you able to watch the episode?

**Comment by avinave14102001** [comment]
> When you say "some kind of error", what is the error, exactly? Also, are you able to watch the episode?

Yes I am able to watch episode 
But but I am not download the episode new episodes and old episode

**Comment by Secozzi** [comment]
@avinave14102001 I'm not asking you, I'm asking @MkMinhaj

**Comment by Secozzi** [comment]
If the videos can be watched, then the extension is working fine. Any download problems would be the app's fault, and should be reported in the [repo for the main app](https://github.com/aniyomiorg/aniyomi/issues/new/choose).

**Comment by MkMinhaj** [comment]
Okay got it. Thanks

**Comment by avinave14102001** [comment]
> If the videos can be watched, then the extension is working fine. Any download problems would be the app's fault, and should be reported in the [repo for the main app](https://github.com/aniyomiorg/aniyomi/issues/new/choose).

You tell us this a app fault .
So please tell me how to solved this problem step by step  because this very serious problem 😔😭😔
And give  any solution

**Comment by Secozzi** [comment]
Either read the troubleshooting guide that you acknowledged you've read when creating a new issue, or open an issue on the repo for the main app.

**Comment by avinave14102001** [comment]
> Either read the troubleshooting guide that you acknowledged you've read when creating a new issue, or open an issue on the repo for the main app.

Please show me step

Please you create new issue I don't
Please help
