### ISSUE TITLE
Gogoanime domain after change a name domain name old or new episode are not downloading in aniyomi library app

### ISSUE THREAD

**Issue by avinave14102001** [aniyomiorg/aniyomi-extensions#2563]
### Source information

Gogoanime 13.78

### Source language

English 

### Steps to reproduce

Ok

### Expected behavior

Episode are not downloading gogoanime domain after change a name

### Actual behavior

Some one help 

### Aniyomi version

0.12.13.10

### Android version

Android 11

### Other details

Please help 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Are you able to watch the episodes?

**Comment by avinave14102001** [comment]
> Are you able to watch the episodes?

Yes I am able watch episode
But I am not able download old episode or new episode this is issue 😞😞 gogoanime domain I am recently update Gogoanime domain

**Comment by Secozzi** [comment]
If you're able to watch the episodes, then the extension is working just fine. Any downloading problems would be the app's fault.
