### ISSUE TITLE
AllMoviesForYou extension is showing error when it tried to play any video

### ISSUE THREAD

**Issue by REFLEXGAMING007** [aniyomiorg/aniyomi-extensions#2565]
### Source information

AllMoviesForYou 13.12

### Source language

English

### Steps to reproduce

Just open the extension & try to play anything.

### Expected behavior

The extension should've played the video when I clicked on it.

### Actual behavior

When I tried to play any video, it's showing
"Video list is empty" error message 

![Screenshot_20231128-151552972](https://github.com/aniyomiorg/aniyomi-extensions/assets/56241882/5b3122ec-1156-4084-86fc-2788d7b209db)

### Aniyomi version

App version: 0.14.6-6697 (standard, 2b8000b81, 106, 2023-11-14T22:48Z) Android version: 12 (SDK 31) Android build ID: SKQ1.210821.001.WW_Phone-31.0210.0210.303-0 release-keys Device brand: asus Device manufacturer: asus Device name: ASUS_I003_1 Device model: ASUS_I003DD Device product name: WW_I003D

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
current url:https://anymovie.cc/
