### ISSUE TITLE
Seez extension is showing error when it tried to play any video

### ISSUE THREAD

**Issue by REFLEXGAMING007** [aniyomiorg/aniyomi-extensions#2566]
### Source information

Seez 13.5

### Source language

English

### Steps to reproduce

Just open the extension & try to play anything.

### Expected behavior

The extension should've played the video when I clicked on it.

### Actual behavior

When I tried to play any video, it's showing
"Expected start of the object '{', but had 'EOF' instead at path: $..." error message

![Screenshot_20231128-115944213](https://github.com/aniyomiorg/aniyomi-extensions/assets/56241882/1c035a47-aa5a-44bb-a9ab-093600e54de3)

### Aniyomi version

App version: 0.14.6-6697 (standard, 2b8000b81, 106, 2023-11-14T22:48Z) Android version: 12 (SDK 31) Android build ID: SKQ1.210821.001.WW_Phone-31.0210.0210.303-0 release-keys Device brand: asus Device manufacturer: asus Device name: ASUS_I003_1 Device model: ASUS_I003DD Device product name: WW_I003D

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
@Samfun75 I still get the Toast notification `loading failed: HTTP error 404 Not Found`no matter which video i start.
TBH Seez and Moflix-Stream have never worked for me in the first place and are mainly used for collection purpose.
But it would be nice, if i could actually watch them there... 😉
Is there a fix?

**Comment by Samfun75** [comment]
> @Samfun75 I still get the Toast notification `loading failed: HTTP error 404 Not Found`no matter which video i start. TBH Seez and Moflix-Stream have never worked for me in the first place and are mainly used for collection purpose. But it would be nice, if i could actually watch them there... 😉 Is there a fix?

As I've found out during testing seez doesn't streaming links for all the media listed there, check on browser if it's actually streamable.

And for future, don't use closed issues for report. Make a new one with details or if it's just a question ask in discord.

**Comment by LittleFreak** [comment]
> > @Samfun75 I still get the Toast notification `loading failed: HTTP error 404 Not Found`no matter which video i start. TBH Seez and Moflix-Stream have never worked for me in the first place and are mainly used for collection purpose. But it would be nice, if i could actually watch them there... 😉 Is there a fix?
> 
> As I've found out during testing seez doesn't streaming links for all the media listed there, check on browser if it's actually streamable.
> 
> And for future, don't use closed issues for report. Make a new one with details or if it's just a question ask in discord.

whats the actual url? i find several in the websearch and dont want to get infected 0=)
open in browser whitin the app shows only a text of meta data, not the website.
