### ISSUE TITLE
AniWatch And Kaido: Failed to extract video.

### ISSUE THREAD

**Issue by MegaMinus** [aniyomiorg/aniyomi-extensions#2568]
### Source information

AniWatch 13.36 (English)

### Source language

English

### Steps to reproduce

1. Download the extension
2. Add an anime
3. Click on start to watch the anime

### Expected behavior

It should let me watch the anime

### Actual behavior

It goes back where we select episode and says Failed to extract video

### Aniyomi version

Preview r6691

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MegaMinus** [comment]
It is same bug with Kaido as well

**Comment by user4302** [comment]
This happens for downloads as well
