### ISSUE TITLE
Gogoanime not working 

### ISSUE THREAD

**Issue by Clutchess** [aniyomiorg/aniyomi-extensions#2569]
### Source information

Gogoanime v13. 72

### Source language

English

### Steps to reproduce

Open gogoanime extension, shows error 502

### Expected behavior

Show anime list

### Actual behavior

Showing error 502

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Http error code that start with 5 means the server itself is having issues, which isn't the extensions fault. Wait until the website stops having issues.
