### ISSUE TITLE
Gogoanime domain is not working video is not playing 

### ISSUE THREAD

**Issue by avinave14102001** [aniyomiorg/aniyomi-extensions#2570]
### Source information

Gogoanime 13.78

### Source language

English 

### Steps to reproduce

Please help 

### Expected behavior

![Screenshot_2023-11-28-23-20-02-22_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/151993381/55e3e84a-8065-4aa3-ab81-3488b3d0495d)

### Actual behavior

Please 🙏🙏🥺

### Aniyomi version

0.12.13.10

### Android version

Android 11

### Other details

Anyone see this problem please help solved this problem 🙏😭🙏
As anime fan help

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This is a problem with gogoanime's website, not the extension.

**Comment by avinave14102001** [comment]
> This is a problem with gogoanime's website, not the extension.

If you have idea 💡 how much time take to solved this problem 😞😕 please tell me

**Comment by Secozzi** [comment]
Since it's not our problem to fix, we cannot possibly give any time estimate.

**Comment by avinave14102001** [comment]
> Since it's not our problem to fix, we cannot possibly give any time estimate.

So you tell wait some time gogoanime domain fix this problem
If any idea how time take please tell me 

Your gogoanime domain is working
