### ISSUE TITLE
AllAnime: Add custom baseurl setting

### ISSUE THREAD

**Issue by X-Oracle** [aniyomiorg/aniyomi-extensions#2574]
### Source name

Allanime

### Source language

English

### Describe your suggested feature

Can you devs make the domain section of allanime extension a text field instead of a list of fixed domains , so I can replace its value with a new domain?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
The extension relies on an API, which has a different domain than the one you see if you load allanime in a browser. There is no way that the average user knows which url to put in there, so I don't think this is a good idea.
