### ISSUE TITLE
We used gogoanime domain in aniyomi app library old episode are download or new are not downloaded 

### ISSUE THREAD

**Issue by avinave14102001** [aniyomiorg/aniyomi-extensions#2583]
### Source information

Gogoanime 13.78

### Source language

English 

### Steps to reproduce

![Screenshot_2023-11-30-15-57-43-33_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/151993381/2820187a-f793-4190-9e82-446e12d056b8)
![Screenshot_2023-11-30-15-58-46-30_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/151993381/cfc76999-c5f3-4d06-afb4-5320d00a8f8b)

Can see In the first image anime name throne of seal this anime or other anime old episode are downloaded

But new are not downloaded in aniyomi app library 

### Expected behavior

Some take action of this problem are coming 😕😎 I can not downloaded the episodes on aniyomi app 

### Actual behavior

New episode are not downloaded
But old episode are downloaded 
Why I don't understand 😔

### Aniyomi version

0.12.13.10

### Android version

Android 11

### Other details

Some one  see this in gogoanime domain use in aniyomi app please ask this problem 

How can solved this problem 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
https://github.com/aniyomiorg/aniyomi-extensions/issues/2563#issuecomment-1829648496

**Comment by avinave14102001** [comment]
> [#2563 (comment)](https://github.com/aniyomiorg/aniyomi-extensions/issues/2563#issuecomment-1829648496)

I ask you why you close this problem

**Comment by avinave14102001** [comment]
> [#2563 (comment)](https://github.com/aniyomiorg/aniyomi-extensions/issues/2563#issuecomment-1829648496)



> [#2563 (comment)](https://github.com/aniyomiorg/aniyomi-extensions/issues/2563#issuecomment-1829648496)

Tell me please why you close this problem solved please

**Comment by Secozzi** [comment]
The reason I closed it is explained in the comment I just linked.

**Comment by Secozzi** [comment]
You've been told multiple times that this is the app's fault, and this isn't the place to open issues for the app. Please actually read the comments that has been told to you as well as everything in the acknowledgment section.

**Comment by avinave14102001** [comment]
> You've been told multiple times that this is the app's fault, and this isn't the place to open issues for the app. Please actually read the comments that has been told to you as well as everything in the acknowledgment section.

So bro you tell me 
How I can in commented properly so everyone can understand

**Comment by Secozzi** [comment]
> - [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).

I just told you to read the acknowledgment section, now please stop asking pointless questions and actually take the time to read the stuff I've told you. You've made me repeat myself enough times already.
