### ISSUE TITLE
MissAV: Http error 103

### ISSUE THREAD

**Issue by tony6674** [aniyomiorg/aniyomi-extensions#2584]
### Source information

MissAV 13.5

### Source language

English

### Steps to reproduce

i am opening MissAV extension and http errror 103 is shown in home page 

### Expected behavior

show contnet in home page and show searched content

### Actual behavior

htttp error 103 is shown in home page
content is not loading

### Aniyomi version

0.12.3.10

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
That's fixed in [aniyomi Preview](https://aniyomi.org/download/).
