### ISSUE TITLE
New mirror for AniWave

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi-extensions#2590]
### Source information

Aniwave 13.59

### Source language

English 

### Source new URL

Aniwave.vc

### Other details

All other domains have now been blocked in Airtel India.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by avinave14102001** [comment]
Same error are coming in gogoanime we can't download episode are coming new episode or old episode

**Comment by J4zzyB1te7s** [comment]
@SinchanBanerjee-tech @YouSummoner try this it has aniwave.vc domain
[en-aniwave.zip](https://github.com/aniyomiorg/aniyomi-extensions/files/13579353/en-aniwave.zip)

**Comment by SinchanBanerjee-tech** [comment]
> @SinchanBanerjee-tech @YouSummoner try this it has aniwave.vc domain [en-aniwave.zip](https://github.com/aniyomiorg/aniyomi-extensions/files/13579353/en-aniwave.zip)

I installed it. But Animiru can't detect the extension. What to do?

**Comment by SinchanBanerjee-tech** [comment]
> @SinchanBanerjee-tech @YouSummoner try this it has aniwave.vc domain [en-aniwave.zip](https://github.com/aniyomiorg/aniyomi-extensions/files/13579353/en-aniwave.zip)

Thanks! But posters for most of the animes aren't loading.
