### ISSUE TITLE
Uhdmovies: new content not showing on uhdmovie

### ISSUE THREAD

**Issue by aadio7** [aniyomiorg/aniyomi-extensions#2613]
### Source information

Uhdmovies 13.19(english)

### Source language

English

### Steps to reproduce

Open aniyomi
Open uhdm extension

### Expected behavior

If any content upload on website then it should also show on uhdm extension and there should be 3 worker as usual

### Actual behavior

The killers of the flower moon is uploaded on 4dec but still not showing up in extension... and my adventure with superman(which uploaded early from killer of flower) have only one worker... but there no problem in older uploads maybe they are uploaded before new updates(13.18 & 13.19) of uhdm

### Aniyomi version

0.12.3.10

### Android version

Android 12

### Other details

![Screenshot_20231205-161003_Chrome](https://github.com/aniyomiorg/aniyomi-extensions/assets/147267681/0eeb856a-416a-42ba-9a45-341011b600c1)
![Screenshot_20231205-161056_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/147267681/cd15784c-58bf-48b1-bc7c-9469912d28b9)
![Screenshot_20231205-161138_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/147267681/5d96ee8d-3b38-4477-ada3-4061946d0760)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
> The killers of the flower moon is uploaded on 4dec but still not showing up in extension...

Your screenshot shows it, but it isn't showing up here when opening it on the browser, at the main page (https://uhdmovies.zip). Maybe it got removed from the main page? If so, it isn't the extension fault, and it is working as expected. Btw, you're still able to simply search the serie name, so you can watch it even without it showing up in the popular page.

> ... have only one worker...

You're using aniyomi STABLE. Aniyomi stable is known for having some strange problems with video extractors, so you should be using Aniyomi [Preview](https://aniyomi.org/download) instead.

**Comment by aadio7** [comment]
> > The killers of the flower moon is uploaded on 4dec but still not showing up in extension...
> 
> Your screenshot shows it, but it isn't showing up here when opening it on the browser, at the main page (https://uhdmovies.zip). Maybe it got removed from the main page? If so, it isn't the extension fault, and it is working as expected. Btw, you're still able to simply search the serie name, so you can watch it even without it showing up in the popular page.
> 
> > ... have only one worker...
> 
> You're using aniyomi STABLE. Aniyomi stable is known for having some strange problems with video extractors, so you should be using Aniyomi [Preview](https://aniyomi.org/download) instead.

I am using preview brother... 
Search the main page https://uhdmovies.zip on any browser not see through webview.. its showing ... yeah i can find the killers of flower using the search... and my other issue was worker ... there were 3 workers earlier but now only 1 ..  does it will create problem???

**Comment by aadio7** [comment]
> > The killers of the flower moon is uploaded on 4dec but still not showing up in extension...
> 
> Your screenshot shows it, but it isn't showing up here when opening it on the browser, at the main page (https://uhdmovies.zip). Maybe it got removed from the main page? If so, it isn't the extension fault, and it is working as expected. Btw, you're still able to simply search the serie name, so you can watch it even without it showing up in the popular page.
> 
> > ... have only one worker...
> 
> You're using aniyomi STABLE. Aniyomi stable is known for having some strange problems with video extractors, so you should be using Aniyomi [Preview](https://aniyomi.org/download) instead.

![Screenshot_20231206-064104_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/147267681/7b61787f-311c-4158-8cd0-c6591d47753d)

In preview also showing only 1 worker for each quality.... and earlier with quality it also shows size

**Comment by aadio7** [comment]
> > The killers of the flower moon is uploaded on 4dec but still not showing up in extension...
> 
> Your screenshot shows it, but it isn't showing up here when opening it on the browser, at the main page (https://uhdmovies.zip). Maybe it got removed from the main page? If so, it isn't the extension fault, and it is working as expected. Btw, you're still able to simply search the serie name, so you can watch it even without it showing up in the popular page.
> 
> > ... have only one worker...
> 
> You're using aniyomi STABLE. Aniyomi stable is known for having some strange problems with video extractors, so you should be using Aniyomi [Preview](https://aniyomi.org/download) instead.

![Screenshot_20231206-134127_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/147267681/e78667b8-811e-4588-a264-76b5e9fe75c1)
![Screenshot_20231206-133801_Chrome](https://github.com/aniyomiorg/aniyomi-extensions/assets/147267681/b50f4156-70e3-454c-ba02-71ffec6de22d)

Now its showing when find me in your memory uploaded... so the problem is its dont show the last uploaded content on main page... its cab show upto the 2nd last uploaded ...
