### ISSUE TITLE
AnimeTake: No anime showing

### ISSUE THREAD

**Issue by LyuboA31** [aniyomiorg/aniyomi-extensions#2620]
### Source information

Animetake 13.2

### Source language

English

### Steps to reproduce

1. go to Animetake
2. choose either popular or latest
3. Nothing works no anime is showed

### Expected behavior

to show anime in latest, popular and when searching by name 

### Actual behavior

Animetake Dosn't show anything when you search or when you choose latest or popular nothing works even when try different DNS

### Aniyomi version

Preview r7217

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Just checked the source and **everything** is working: Popular anime page, latest updates, search, anime details page, episode list and video list extraction. This source uses Cloudflare protection, and maybe that's the issue you're facing (which isn't the extension's fault).

Please, read **and** follow the instructions of the Cloudflare section in [Aniyomi's troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/#cloudflare) to solve it, or wait until the source lowers their protection level. You can also just migrate to another extension too.
