### ISSUE TITLE
Superstream's thumbnails aren't loading

### ISSUE THREAD

**Issue by JohnKirk1337** [aniyomiorg/aniyomi-extensions#2644]
### Source information

SuperStream 13.10

### Source language

English

### Steps to reproduce

Just access SuperStream through the app.

### Expected behavior

For thumbnails to load

### Actual behavior

Thumbnails don't load :(

### Aniyomi version

App version: 0.14.6-6691 (standard, 5fd00d4a1, 105, 2023-11-02T23:11Z) 

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closing in favour of #3305
