### ISSUE TITLE
Animesaga hindi not working 

### ISSUE THREAD

**Issue by phisher98** [aniyomiorg/aniyomi-extensions#2645]
### Source information

Animesaga.in

### Source language

hindi

### Steps to reproduce

Open any show and play any episode 

### Expected behavior

Play video 

### Actual behavior

no links found or error

### Aniyomi version

v0.12.3.10

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Anujbr00** [comment]
I am also facing the same issue
