### ISSUE TITLE
Please add AitrVip extractor for TRAnimeİzle

### ISSUE THREAD

**Issue by kyoyacchi** [aniyomiorg/aniyomi-extensions#2649]
### Source information

TrAnimeİzle 13.11

### Source language

Turkish

### Steps to reproduce

Use tranimeizle

### Expected behavior

a

### Actual behavior

a

### Aniyomi version

0.16.0.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Use the correct issue template.

**Comment by kyoyacchi** [comment]
> Use the correct issue template.

I was editing it... Is it still would be valid?

**Comment by Secozzi** [comment]
It would be preferable if you use the correct issue template

**Comment by kyoyacchi** [comment]
https://github.com/aniyomiorg/aniyomi-extensions/issues/2650 this one is OK, i guess..
