### ISSUE TITLE
Please add AitrVip extractor for TRAnimeİzle

### ISSUE THREAD

**Issue by kyoyacchi** [aniyomiorg/aniyomi-extensions#2650]
### Source information

TrAnimeİzle 13.11

### Source language

Turkish

### Steps to reproduce

1.Install tranimeizle extension.
2. Try to watch an anime

### Expected behavior

It should(optional) show video hosts more than Sibnet.

### Actual behavior

I have enabled all video hosts for TRAnimeİzle except okru and sendvid(this one is banned in Turkiye)
Since my internet is average, i'm having hard time to watch anime in Sibnet but, it frequently only shows "Sibnet" to play video and it freezes every 5 seconds (annoying)

### Aniyomi version

0.16.0.0

### Android version

Android 11

### Other details

Please add other video hosts

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Use the "Feature request" issue template for feature requests, not the "bug report" template

**Comment by kyoyacchi** [comment]
> Use the "Feature request" issue template for feature requests, not the "bug report" template

 I ain't gonna open a third issue...
