### ISSUE TITLE
Multi select media for jellyfin

### ISSUE THREAD

**Issue by Sadwhy** [aniyomiorg/aniyomi-extensions#2652]
### Source name

Jellyfin

### Source language

Multi

### Describe your suggested feature

![Screenshot_20231217_135631_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/99601717/591782aa-c263-4290-abb2-7b0405dc1d65)
Instead of just selecting one media library. Could you make it into a check box and give the ability to select multi media libraries in a single extension? Without having to use multiple jellyfin extensions? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
I'm not entirely sure if the hassle to add this is worth it, as the reason for multiple jellyfin extensions existing is to prevent constantly going extension settings and change the library. Also, once you've added an entry to your library it doesn't matter which extension it comes from.

**Comment by Sadwhy** [comment]
> I'm not entirely sure if the hassle to add this is worth it, as the reason for multiple jellyfin extensions existing is to prevent constantly going extension settings and change the library. Also, once you've added an entry to your library it doesn't matter which extension it comes from. Another problem is that paging wouldn't be completely accurate.

It is worth it bro. If I didn't have a problem by using multiple instances of jellyfin for just one server then I wouldn't have made this issue.
