### ISSUE TITLE
Please Add MangaReader

### ISSUE THREAD

**Issue by MegaMinus** [aniyomiorg/aniyomi-extensions#2655]
### Source name

MangaReader

### Source link

https://mangareader.to/

### Source language

English/France/Japanese

### Other details

It has so much vast majority of manga.
![Screenshot_20231218_151705_Brave](https://github.com/aniyomiorg/aniyomi-extensions/assets/140636598/1ad73290-4c00-4b5e-bb05-cc38a8d59eea)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This isn't the repo for manga extensions. Besides, this already has an extension.
