### ISSUE TITLE
Kuramanime: video list is empty

### ISSUE THREAD

**Issue by Sofie99** [aniyomiorg/aniyomi-extensions#2662]
### Source information

Kuramanime 13.11 (Indonesia)

### Source language

Indonesia

### Steps to reproduce

1. Play any anime
2. exit with error message : "video list is empty"

### Expected behavior

played well

### Actual behavior

exit video

### Aniyomi version

Preview r6691

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kyoyacchi** [comment]
Same for tranimeizle
