### ISSUE TITLE
Add Toono.in source

### ISSUE THREAD

**Issue by SinchanBanerjee-tech** [aniyomiorg/aniyomi-extensions#2664]
### Source name

Toono

### Source link

toono.in

### Source language

Hindi

### Other details

It's a website for hindi dubbed anime & cartoons. Pretty similar to Anime-world.in but has much more content. [You may say we already have Yomiroll for hindi dubs, but NO. THERE ARE MANY OTHER NETWORKS who dub anime in hindi nowadays... which aren't available on Yomi]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by SinchanBanerjee-tech** [comment]
Apparently it also has dubs in other indian languages like tamil & telugu.

**Comment by aadio7** [comment]
> toono.in

Toonworld4all.me is a better site for toons
