### ISSUE TITLE
Failed to bypass Cloudflare

### ISSUE THREAD

**Issue by AGA2707** [aniyomiorg/aniyomi-extensions#2669]
### Source information

KissAnime 13.5

### Source language

English

### Steps to reproduce

1. Install KissAnime extension.
2. Open the extension.
3. See error Failed to bypass Cloudflare.

### Expected behavior

Should bypass Cloudflare.

### Actual behavior

Can't bypass Cloudflare.

### Aniyomi version

0.12.3.10

### Android version

10

### Other details

I don't think if KissAnime extension needs an update. I tried all the troubleshooting, open WebView browser and bypass the Cloudflare there, clearing browser cookies, change web string, reinstall extension, I also tried to reinstall the aniyomi app but the problem still there. The extension works on past few days but suddenly the error appeared and all my libraries on the extension gone.
![Screenshot_2023-12-24-09-49-06-089_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi-extensions/assets/148602118/c1decf3a-f530-489c-8738-33c6160d325b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Follow the cloudflare section in the troubleshooting guide that you acknowledged that you've read, if it doesn't help wait until they lower protection or migrate to other sources.

**Comment by AGA2707** [comment]
@Secozzi I tried all the troubleshoot that I read and I don't read. I can't migrate cause all the libraries from the extension are all gone.
