### ISSUE TITLE
Add zoro.to extension 

### ISSUE THREAD

**Issue by virusRK** [aniyomiorg/aniyomi-extensions#2674]
### Source name

Zoro.to 

### Source language

English 

### Describe your suggested feature

I would like to make a humble request to the developer of the Aniyomi application. I have been using this app since 2022 and I love it.I couldn't stop using it. I use the Zoro.to extension to watch English dubbed anime, but I couldn't find it in the new update. It's a great extension to watch anime. Could you please provide it again on our application, Aniyomi? Thank you.

### Other details

Additional information about extension please add that extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
It's because zoro.to got rebranded to aniwatch.to, so you just need to use the Aniwatch extension.

**Comment by virusRK** [comment]
Bro it's get use when we want to watch in sub but I need in dubbed in english so I try that but it still dubbed unavailable 
And if we speak up about zoro.to is has dubbed with subtitles to
>
