### ISSUE TITLE
A problem for Arabic sources

### ISSUE THREAD

**Issue by mustafa191199** [aniyomiorg/aniyomi-extensions#2675]
### Source information

tuktukcinema (Arabic ) ....akwam (Arabic)

### Source language

Arabic 

### Steps to reproduce

No videos work at all 

### Expected behavior

Websites should be updated and ensured that they are working 

### Actual behavior

Please update the sources 

### Aniyomi version

R6691

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Please make one issue per source instead of mentioning multiple sources in the same issue.
