### ISSUE TITLE
[Source Request] ihavenotv.com (Documentary only)

### ISSUE THREAD

**Issue by 12345axc** [aniyomiorg/aniyomi-extensions#268]
## Source website
- Name: I Have No TV
- Link: https://ihavenotv.com/
- Language(s): English

## Other details
An English curated streaming site focusing on documentary, from NatGeo, PBS. etc.

Content hosted on Streamtape and YouTube.
ST example: https://ihavenotv.com/sir-david-spiegelhalter-discusses-thomas-bayes-and-ronald-fisher-people-of-science-with-brian-cox
YT example: https://ihavenotv.com/the-deadliest-being-on-planet-earth-the-bacteriophage-in-a-nutshell

**Comment by 12345axc** [comment]
@jmir1 Wrong closed issues
This is not AsianLoad related.

**Comment by ahmedgamal17** [comment]
@12345axc ok sorry I tagged the wrong issue in my PR wait for jmir to open it

**Comment by 12345axc** [comment]
Added more info
