### ISSUE TITLE
Gogoanime

### ISSUE THREAD

**Issue by LyuboA31** [aniyomiorg/aniyomi-extensions#2681]
### Source information

Gogoanime 13.78

### Source language

English

### Source new URL

https://anitaku.io

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
That's a fake clone, not an official gogoanime domain
