### ISSUE TITLE
I am trying to use gogoanime but it doesn't work

### ISSUE THREAD

**Issue by Navdeep2663** [aniyomiorg/aniyomi-extensions#2683]
### Source information

Gogoanime 13.78 (English)

### Source language

English 

### Steps to reproduce

When i try to open a series 
![Screenshot_20231229_132541_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/124970015/6beef96a-4abc-402e-9867-b1303fbec0f2)

### Expected behavior

It should been easy to watch on gogoanime
![Screenshot_20231229_130906_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/124970015/4441a827-7354-4462-88d0-cf3902568811)

### Actual behavior

But every time i play a episode this happens 
![Screenshot_20231229_132638_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/124970015/106d771b-eb1e-4387-a4a7-1d79aa12bf5c)

### Aniyomi version

App version: 0.12.3.10

### Android version

Android version: 13

### Other details

Here i are my device details please help ASAP ( Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.M127GXXS6DWK1
Device brand: samsung
Device manufacturer: samsung
Device name: m12
Device model: SM-M127G
Device product name: m12dd )

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LyuboA31** [comment]
gogoanime has moved to new domain anitaku.io

**Comment by LyuboA31** [comment]
apparently anitaku.io is Unofficial domain but anitaku.to is working now and the extension is working fine

**Comment by Secozzi** [comment]
Closing as this issue has most likely been solved in the new app update. If the issue persists, please create a new issue.
