### ISSUE TITLE
Aniwatch link change

### ISSUE THREAD

**Issue by 1YuviKing1** [aniyomiorg/aniyomi-extensions#2690]
### Source information

Aniwatch.to -> Aniwatchtv.to

### Source language

English

### Steps to reproduce

The link got changed

### Expected behavior

Old link doesn't work

### Actual behavior

Anime from that source that was in library says null error

### Aniyomi version

Preview r6691

### Android version

Android 12

### Other details

![Screenshot_20240102_091444_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/112407714/a90c351b-d54b-45ef-b4cc-9e60cf3b8945)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by HarbingerOfTheEnd** [comment]
Has there been any work done in this? Cause i no longer can access aniwatch through aniyomi.

**Comment by 1YuviKing1** [comment]
Aniwatch domain just get slow.
I suppose it's gonna get down in few months.
I prefer to change site to watch anime.

**Comment by fakebhai** [comment]
irrelevant issue now
