### ISSUE TITLE
Gogoanime domain can not download episode click option is download in aniyomi app

### ISSUE THREAD

**Issue by avinave14102001** [aniyomiorg/aniyomi-extensions#2691]
### Source name

Gogoanime 

### Source link

https://anitaku.to/

### Source language

English 

### Other details

I am trying so many time aniyomi app 
Episode are not download

First I clicked download option but episode are not downloading 
He showing red colour Mark like this ‼️‼️‼️

Anyone see this problem please check 
And gogoanime or new anitaku.to
Ok

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Cistmist** [comment]
It's still not working.
