### ISSUE TITLE
Update filters AniTube and animesvision

### ISSUE THREAD

**Issue by Rey619Gamer** [aniyomiorg/aniyomi-extensions#2697]
### Source name

AniTube and AnimesVision

### Source language

Português - Brasil

### Describe your suggested feature

Not showing 2024 in these extensions 
![Screenshot_20240103-183330_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/59585126/44761022-015b-40c2-922e-556cd1cc0f1b)
![Screenshot_20240103-183312_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/59585126/e740f78c-9196-4589-a296-2b31d8ffa2cd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Note: AnimesVision doesn't have 2024 in their year filter yet.
