### ISSUE TITLE
Video list empty error and web view not working in Dramacool.

### ISSUE THREAD

**Issue by bipolardawg** [aniyomiorg/aniyomi-extensions#2700]
### Source information

Dramacool 

### Source language

English subbed

### Steps to reproduce

Open titles which are currently airing, eg: A good day to be a dog and try to play it. It will show video list empty error and also the web view is not working.

### Expected behavior

It should've worked!

### Actual behavior

Video list empty error

### Aniyomi version

Preview r6691

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
it's mostly because of broken links by other hosts. adding Asianload/standard-server host (extractor) should solve it. which seems to be working in all episodes and it should also help with new releases as it's first only uploaded on their host.
