### ISSUE TITLE
Animepahe Cloudflare Issue

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi-extensions#2706]
### Source information

Animepahe 13.26

### Source language

English 

### Steps to reproduce

Try to play any episode.

### Expected behavior

Episode should load.

### Actual behavior

It tries to load the episode but then gives an error "failed to bypass cloudflare"

### Aniyomi version

Preview r6691

### Android version

Android 13

### Other details

I did try changing the user agents but the issue persists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://aniyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources.
