### ISSUE TITLE
AniTube erro no download

### ISSUE THREAD

**Issue by Mynameluis** [aniyomiorg/aniyomi-extensions#2727]
### Source information

AniTube 13.13 (português Brazil)

### Source language

Português Brazil 

### Steps to reproduce

Quando eu aperto pra baixar um episódio 
Ele começa e depois de um tempo a 
Porcentagem do download começa a ficar maluca
Vai pro 99% volta pro 1% e assim contínua a ate cancelar o download 

### Expected behavior

Baixar normalmente o episódio solicitado 

### Actual behavior

Invés de baixar o episódio
A porcentagem do download do anime fica maluca indo pro 99% voltando pro 1% e fica assim até dar erro

### Aniyomi version

App version: 0.15.2.0-7443

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This is a problem with the main app, not the extension. Report it on the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose) instead.
