### ISSUE TITLE
Anime site india

### ISSUE THREAD

**Issue by ShankarKSH001** [aniyomiorg/aniyomi-extensions#2750]
### Source name

Animerulz

### Source link

https://animerulz.to

### Source language

Multi(India)

### Other details

Indian anime website.Can you pls add this site cause mostly low content and  not working Indian contents in aniyomi sources.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by 1YuviKing1** [comment]
When this one will add?

**Comment by Yuv-Sama-00** [comment]
Bro the site changed its domain now it's 
https://animerulz.to/home/
Thanks for requesting this website, I've also came here to make a request of this website!

**Comment by ShankarKSH001** [comment]
> Bro the site changed its domain now it's https://animerulz.to/home/ Thanks for requesting this website, I've also came here to make a request of this website!

🤝

**Comment by ShoyebOP** [comment]
I also want it as a source
