### ISSUE TITLE
I want to add an extension for Vietnamese people to watch anime

### ISSUE THREAD

**Issue by folacid28** [aniyomiorg/aniyomi-extensions#2761]
### Source name

anime vietsub

### Source link

https://animevietsub.io/

### Source language

Vietnamese

### Other details

"+18/NSFW = no"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
The bot seems to have problems, but the issue is a duplicate of #202
