### ISSUE TITLE
Add multimovie 

### ISSUE THREAD

**Issue by Mrunknow3** [aniyomiorg/aniyomi-extensions#2773]
### Source name

Multimovie

### Source link

https://multimovies.uno/

### Source language

Hindi And English

### Other details

It have good interface and almost all movie and series and famous anime and k drama

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Mrunknow3** [comment]
How you close

**Comment by fakebhai** [comment]
we already have multimovies extension

**Comment by Mrunknow3** [comment]
Sorry i seen hindi and don't find. But multimovie doesn't working solve this

**Comment by fakebhai** [comment]
if it's broken then create an issue under relevant issue template
