### ISSUE TITLE
IT'S multi language anime source called anime rulz

### ISSUE THREAD

**Issue by Mrunknow3** [aniyomiorg/aniyomi-extensions#2774]
### Source name

Animerulz

### Source link

https://animerulz.in/home/

### Source language

English,Japanese,Hindi,Tamil,Telgu,Bangali,malayalam and hindi

### Other details

It's have almost all anime 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Mrunknow3** [comment]
HOW THIS CLOSED?

**Comment by fakebhai** [comment]
#2750

**Comment by Mrunknow3** [comment]
Ok this duplicated but you don't added original request animerulz.in
