### ISSUE TITLE
Multimovie doesn't work

### ISSUE THREAD

**Issue by Mrunknow3** [aniyomiorg/aniyomi-extensions#2775]
### Source information

Multimovie 14.15 (English)

### Source language

English

### Steps to reproduce

Cloudflare bypass fail i seen your solution on website open webviw and refresh and apply i am not robot and close webviw but webviw doesn't bypass cloudflare 

### Expected behavior

Cloudflare bypass fail i seen your solution on website open webviw and refresh and apply i am not robot and close webviw but webviw doesn't bypass cloudflare 

### Actual behavior

Instead open website and bypass cloudflare

### Aniyomi version

Preview r7473

### Android version

Android 13

### Other details

Fix this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Mrunknow3** [comment]
Again closed

**Comment by Secozzi** [comment]
The closure is valid. Read the bot message as to why.
