### ISSUE TITLE
[Bug] <AnimePahe>: <Can't download or stream episodes>

### ISSUE THREAD

**Issue by Hokage027** [aniyomiorg/aniyomi-extensions#278]
## Device information
- App version: 0.12.3.6
- Android version: 1. Android 11, 2. Android 10
- Device: 1. Redmi Note 7 Pro, 2. Redmi Note 4x

## Source information
- Name: AnimePahe
- Extension version: 12.12

## Steps to reproduce
1. Open any anime from AnimePahe extension.
2. Stream or download the episode. 

### Expected behavior
Episode should play.

### Actual behavior
Episode doesn't play or download.
"ERROR GETTING LINK"

## Other details
 I have tried all the troubleshooting methods and cleared cache, cookies and DNS over HTTPS and turned HLS links on and off

https://user-images.githubusercontent.com/98649557/151664302-65e70b6a-5595-4dd9-abbd-49bb32cf8bed.mp4

**Comment by Samfun75** [comment]
Closing as this is not applicable on latest versions.
