### ISSUE TITLE
Multimovie problem

### ISSUE THREAD

**Issue by Mrunknow3** [aniyomiorg/aniyomi-extensions#2782]
### Source information

Multimovie 14.15 (English) 

### Source language

English

### Steps to reproduce

1. Open multimovie
2. Go to watch anything ex one punch man ep 1.
3. Problem is that say video list is empty

### Expected behavior

Video list empty. 

### Actual behavior

Play ep. 

### Aniyomi version

Preview r7473

### Android version

Android 13

### Other details

I contact admin of multimovie he said aniyomi don't added streamwish. They say contact aniyomi and say add streamwish server in aniyomi. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by heliosII** [comment]
Is there is nullpointerexception error ... so you could add that in this issue in other details

**Comment by Mrunknow3** [comment]
How to solve?
