### ISSUE TITLE
multimovies : cloudflare and nullpointerexception error

### ISSUE THREAD

**Issue by heliosII** [aniyomiorg/aniyomi-extensions#2785]
### Source information

multimovies 14.15

### Source language

English

### Steps to reproduce

step1: open aniyomi
step2: open multimovies

### Expected behavior

the extension will not show cloudflare error..even if shows changing user agent will show the content and play the content

### Actual behavior

the extension showing cloudflare error but changing user agent string also dont work since opening content show nullpointerexception : error ... cant play anything 

### Aniyomi version

aniyomi r7473

### Android version

android 12

### Other details

please solve and bypass the cloudflare error... and the biggger problem nullpointerexception error

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by heliosII** [comment]
maybe duplicate of #2782 .. cant tell surely

**Comment by Mrunknow3** [comment]
Bro how to solve nullpointextension problem I change agent now Cloudflare bypassed but click anything that say 
Video list is empty

**Comment by heliosII** [comment]
> Bro how to solve nullpointextension problem I change agent now Cloudflare bypassed but click anything that say Video list is empty
 U tell that streamwish is missing ... so thats why its showing error??.. so maybe aniyomi can add the extractor

**Comment by Mrunknow3** [comment]
Now that nothing we can do

**Comment by jmir1** [comment]
![grafik](https://github.com/aniyomiorg/aniyomi-extensions/assets/43830312/b9424e65-decf-4673-8810-d9e488fecc9e)

**Comment by Mrunknow3** [comment]
Yes how to add who add go I added issue
