### ISSUE TITLE
on aniyomi extensions website add (compile zip file) for filtered or all extensions to download

### ISSUE THREAD

**Issue by Character95** [aniyomiorg/aniyomi-extensions#2790]
### Describe why this should be added

on aniyomi when i want to download or update more than 100+ extensions app crashes so i install them through some programs that have multi-install option and i need to download from aniyomi extensions download website.
![IMG_20240119_213535](https://github.com/aniyomiorg/aniyomi-extensions/assets/25694091/90bfbbcf-5b14-46fa-8709-acaa3b18daeb)

### Other details

downloading extensions individualy is time consuming

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open (or closed) issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
https://github.com/aniyomiorg/aniyomi-extensions/tree/repo

![Screenshot_2024-01-20-12-30-57-510_com android chrome](https://github.com/aniyomiorg/aniyomi-extensions/assets/53574579/231966f9-8567-4dd8-8132-e02d057bccb9)

Download this branch as zip and it has folder called apk with all the extensions

**Comment by Character95** [comment]
thanks you saved me 2 hours of install...
