### ISSUE TITLE
Manga-oni

### ISSUE THREAD

**Issue by Omega-iso** [aniyomiorg/aniyomi-extensions#2791]
### Source name

Manga-oni

### Source link

https://manga-oni.com/

### Source language

Español

### Other details

+18

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
You chose the wrong repo...
I'd recommend to contact the people of https://keiyoushi.github.io/ instead.

**Comment by Secozzi** [comment]
@LittleFreak Don't share third party repositories
