### ISSUE TITLE
aniyomi-all.missav-v14.6.apk not work in CloudStream

### ISSUE THREAD

**Issue by OptimisticXNY** [aniyomiorg/aniyomi-extensions#2794]
### Source information

aniyomi-all.missav-v14.6

### Source language

all

### Steps to reproduce

1. Install CloudStream and configure Aniyomi Extensions in CloudStream
2. Install missav Extension in Aniyomi
3. Other aniyomi Extensions work fine in CloudStream, but missav Extension does not display content in CloudStream and does not support search

### Expected behavior

missav Extension displays content normally in CloudStream like he does in aniyomi

### Actual behavior

missav Extension does not display content in CloudStream and does not support search

### Aniyomi version

0.15.2.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We are not affiliated with cloudstream and will not look at bugs made through the cloudstream app.
