### ISSUE TITLE
[Bug] <Animepahe>: <error getting links>

### ISSUE THREAD

**Issue by Slamandwr** [aniyomiorg/aniyomi-extensions#281]
## Device information
- Tachiyomi version:0.12.3.6-4506
- Android version:11
- Device:redmi

## Source information
- Name:Animepahe
- Extension version:12.12

## Steps to reproduce
1. Just open the anime saved in library from animepahe
2. Just select any other anime from animepahe

### Expected behavior
When you select any episode it's closes suddenly showing error getting link

### Actual behavior
When you select any episode from animepahe extension it's shows error getting links sometimes rarely shoes connection error something like that when ever u click an episode from animepahe extension sometimes when u click animepahe extension it's shows no animes it just shows connection error. 

## Other details
These are the things showing in animepahe extension even my friend has the same probs. So plz, kindly fix this issue so we could watch some anime.

**Comment by mnabid** [comment]
Did you enable "Use HLS Links" in Animepahe's extension settings?

**Comment by ErenGrisha** [comment]
I have tried Both by turning it on and off but it is not playing in either case.

**Comment by Slamandwr** [comment]
How to do it??

**Comment by Slamandwr** [comment]
I got it I enable it now it's working thank you
