### ISSUE TITLE
BetterAnime is dead

### ISSUE THREAD

**Issue by Blackklegend** [aniyomiorg/aniyomi-extensions#2811]
### Source name

Better Anime

### Source language

Portuguese

### Source link

https://betteranime.net

### Other details

Closed due to DMCA 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Joshsanxx** [comment]
You can still log in to the site, what doesn't work is just the genre filter and search
