### ISSUE TITLE
Unable to resolve host "mixdrop.sx" issue

### ISSUE THREAD

**Issue by Latinlee** [aniyomiorg/aniyomi-extensions#2820]
### Source information

AnimeOnline.Ninja 14.36

### Source language

Spanish

### Steps to reproduce

1.Play any anime on AnimeOnline.ninja extension
2.Player will show, and closed automatically
3.And you got  Unable to resolve host "mixdrop.sx" message

### Expected behavior

Video playing normally

### Actual behavior

Player force closed and showing "Unable to resolve host mixdrop.sx" message, This happens with 99 % of the anime I try.

### Aniyomi version

0.15.2.3

### Android version

Android 13

### Other details

![Screenshot_2024-01-24-15-42-19-167_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi-extensions/assets/102179835/8f9e2c18-32ac-4d77-9bfb-54e3d239b933)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
mixdrop has changed its name to https://mixdrop.ag, we will be solving the problem as soon as possible, I have also seen that in the new animeninja chapters and the new movies they do not use mixdrop, even so I will be attentive to it
