### ISSUE TITLE
Add more video extractors (like DoodStream) to MonosChinos

### ISSUE THREAD

**Issue by P10Ms** [aniyomiorg/aniyomi-extensions#2831]
### Source name

MonosChinos

### Source language

Spanish

### Describe your suggested feature

The MonosChinos extension has few of the video extractors used on the site, and it would be great to have DoodStream, filemoon or streamtape as video extractors.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
I'll add streamtape and filemoon, but DoodStream has to wait while we fix it
