### ISSUE TITLE
Yomiroll Sub Bug

### ISSUE THREAD

**Issue by LittleFreak** [aniyomiorg/aniyomi-extensions#2846]
>              Re-open the issue if it's till happening on latest version of app(0.15.3) and >extension(14.29).
>And check on Aniyomi as well not just kuuki
>
_Originally posted by @Samfun75 in https://github.com/aniyomiorg/aniyomi-extensions/issues/2432#issuecomment-1910212808_

Affirmative...
Despite my preferred language setting (German) yomiroll (14.29) still sets the subtitles in Arabic for each episode and local token is ignored aswell. This happens with aniyomi (0.15.2.1) and animiru (0.16).

**Comment by Samfun75** [comment]
Hmm this happens only for soft sub, for me it's always setting it to English. The app will try to guess your locale from your device, what is your device language and locale set too?

**Comment by WGmg23** [comment]
also show two spanish(latinoamerican) the second doesn't work

**Comment by LittleFreak** [comment]
> Hmm this happens only for soft sub, for me it's always setting it to English. The app will try to guess your locale from your device, what is your device language and locale set too? 

My device language is German.
I don't know why it's selecting Arabic in the first place 😅

**Comment by Samfun75** [comment]
> I don't know why it's selecting Arabic in the first place 😅

That's was because it was sorted alphabetically and it the app can find your locale it selects the first one. But after this update it will put your preferred sub language first and it will be selected if available

**Comment by LittleFreak** [comment]
Fixed after so much time,
Thanks @Samfun75 ❤️
