### ISSUE TITLE
Animes Orion changed domain

### ISSUE THREAD

**Issue by kyhapi** [aniyomiorg/aniyomi-extensions#2849]
### Source information

Animes Orion 14.1

### Source language

PT-BR

### Source new URL

https://animesorionvip.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
As far as I know, that's **not** their official domain, it's just yet another copycat 🔎

**Comment by kyhapi** [comment]
> Pelo que eu sei, esse **não** é o domínio oficial deles, é apenas mais um imitador 🔎

So unfortunately they must have shut down the website, I thought they had changed dominoes after they won't publish anything on social media, searching the website only this other one comes up

**Comment by kyhapi** [comment]
There is also another source with the dead site #2893 

I accidentally closed it, I don't know how to use GitHub very well

**Comment by Claudemirovsky** [comment]
Skill issue
