### ISSUE TITLE
Animes House: error loading episodes

### ISSUE THREAD

**Issue by kyhapi** [aniyomiorg/aniyomi-extensions#2858]
### Source information

Animes House 14.10

### Source language

Português ( Brasil )

### Steps to reproduce

1. choose an anime
2. select an episode
3. the episode does not load and displays "loading failed: https: HTTP error 404 Not Found"
![Screenshot_20240201-162024](https://github.com/aniyomiorg/aniyomi-extensions/assets/147045416/005e47df-df2a-419c-a0bf-e0e42de5d223)

### Expected behavior

when selecting the episode and for the player to load and start playing the episode.

### Actual behavior

the episode does not load and displays "loading failed: https: HTTP error 404 Not Found"

### Aniyomi version

Preview r7493

### Android version

Android 13

### Other details

This problem occurs when trying to watch episodes of any anime of that particular length, I checked in WebView and the episodes load normally.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by edgardmessias** [comment]
This extension was removed
