### ISSUE TITLE
Aniplay.co change of structure

### ISSUE THREAD

**Issue by Yoshinizar** [aniyomiorg/aniyomi-extensions#2863]
### Source information

Aniplay 14.6

### Source language

Italiano

### Source new URL

https://aniplay.co

### Other details

the site has kept the same site but has made changes to the display and structure with a new version of the entire site

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Yoshinizar** [comment]
yes it exists but it has changed structure

**Comment by Claudemirovsky** [comment]
The bot closed it because you used the wrong template.

**Comment by Yoshinizar** [comment]
> Il bot l'ha chiuso perché hai utilizzato il modello sbagliato.

Oh scusa non lo sapevo, lo hai riaperto tu per me?
