### ISSUE TITLE
movies n shows 4k and 1080p quality

### ISSUE THREAD

**Issue by jvsandhu** [aniyomiorg/aniyomi-extensions#2872]
### Source name

braflix

### Source link

https://www.braflix.app/

### Source language

Englis 

### Other details

best site witch nice sources and fast speed [https://www.braflix.app/](url)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by LeGenDaRy15PT** [comment]
It's a very complete site, if you could add it as an extension it would be perfect
