### ISSUE TITLE
Animes Aria died

### ISSUE THREAD

**Issue by kyhapi** [aniyomiorg/aniyomi-extensions#2893]
### Source name

Animes Aria

### Source language

Português ( Brasil )

### Source link

https://animesaria.com/

### Other details

![Screenshot_20240208-075559](https://github.com/aniyomiorg/aniyomi-extensions/assets/147045416/ba5ab5f2-e3ca-4067-b927-233619744d86)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by edgardmessias** [comment]
This extension was removed.
