### ISSUE TITLE
Aniwave Cloudflare looping, no fix

### ISSUE THREAD

**Issue by Nintenstation** [aniyomiorg/aniyomi-extensions#2897]
### Source information

Aniwave 14.65

### Source language

English

### Steps to reproduce

When you open the aniwave source, it loads and loads until it gives up loading without any results. It messages that this is caused by cloudflare protection not getting bypassed. Now there is a number of steps a user could take to solve this issue, such as accepting cloudflare via the webview, or changing the string in advanced options for a more unconventional troubleshooting. However none of this worked in the end. I'm open if anyone has a specific solution to follow, but I'm convinced this is a very innate issue only the developers can troubleshoot and fix.

### Expected behavior

Opened up aniwave extensions, should load results.

### Actual behavior

It gives a cloudflare issue that keeps looping indefinitely.

### Aniyomi version

0.15.2.4. (latest version at the very least)

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
That's actually a skill issue. The cloudflare troubleshooting steps works, you just need to follow them well and try different user-agents and etc.
Proof: ![Screenshot_20240208153119.png](https://github.com/aniyomiorg/aniyomi-extensions/assets/63046606/6b85bd70-0ffe-44b7-a8dd-6592360ca756)

**Comment by Nintenstation** [comment]
> That's actually a skill issue. The cloudflare troubleshooting steps works, you just need to follow them well and try different user-agents and etc.
> Proof: ![Screenshot_20240208153119.png](https://github.com/aniyomiorg/aniyomi-extensions/assets/63046606/6b85bd70-0ffe-44b7-a8dd-6592360ca756)
> 
> 

Can you tell me what user-agent string you have? I tried so many and none of them worked. I want to try yours to see if it works. Thanks in advance.

**Comment by Nintenstation** [comment]
> That's actually a skill issue. The cloudflare troubleshooting steps works, you just need to follow them well and try different user-agents and etc.
> Proof: ![Screenshot_20240208153119.png](https://github.com/aniyomiorg/aniyomi-extensions/assets/63046606/6b85bd70-0ffe-44b7-a8dd-6592360ca756)
> 
> 

Never mind, finally found one that worked

**Comment by Allless** [comment]
Will leave this here in case someone needs it

``` txt
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.164 Mobile Safari/537.36
```
