### ISSUE TITLE
Donghuastream not working

### ISSUE THREAD

**Issue by LyuboA31** [aniyomiorg/aniyomi-extensions#2900]
### Source information

Donghuastream 14.5 English

### Source language

English

### Steps to reproduce

1. Open any anime
2. No Episodes found
3. Issue Nullpointerexeption: null

### Expected behavior

to load the all episodes for the chosen anime

### Actual behavior

No episodes found anime page Dosn't load at all

### Aniyomi version

Preview r7493

### Android version

Android 10

### Other details

All Donghuastream Domains it's same site but different url please add as option
Donghuastream.co.in
Donghuastream.org
Donghuastream.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LyuboA31** [comment]
can ypu please replace Donghuastream with https://naruldonghua.xyz/ it's a better website then Donghuastream

**Comment by Secozzi** [comment]
Create a new issue for a source request instead of commenting on unrelated issues

**Comment by LyuboA31** [comment]
14.7 update still has the same issues

**Comment by fakebhai** [comment]
> 14.7 update still has the same issues

version bump doesn't necessarily mean extension fix

**Comment by LyuboA31** [comment]
well this one had 5 or 6 so far without a fix so why new version if there's nothing new

**Comment by Claudemirovsky** [comment]
> well this one had 5 or 6 so far without a fix so why new version if there's nothing new

It's a global version bump, the extension happens to use a library that got changes and so it had to be bumped to reflect the changes (which doesn't necessarily translates to a fix)
