### ISSUE TITLE
Coomer, Kemono Video Extensions

### ISSUE THREAD

**Issue by KarunaTG** [aniyomiorg/aniyomi-extensions#2901]
### Source name

Coomer, Kemono

### Source link

https://coomer.su and https://kemono.su

### Source language

English 

### Other details

Nsfw +18

These sources are in the manga sources but not in anime sources.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Duplicate of #2050

Also, please only request a single source per issue
