### ISSUE TITLE
Add Rebahin

### ISSUE THREAD

**Issue by WEPOXS** [aniyomiorg/aniyomi-extensions#2903]
### Source name

Rebahin

### Source link

http://179.43.169.210

### Source language

Indonesia

### Other details

NSFW/+18= no

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Does the site have a domain?

**Comment by WEPOXS** [comment]
> Does the site have a domain?

Mybe, nah

**Comment by WEPOXS** [comment]
> Does the site have a domain?

New url http://179.43.163.54/
