### ISSUE TITLE
URL Change: Animetake

### ISSUE THREAD

**Issue by Elixtra** [aniyomiorg/aniyomi-extensions#2918]
### Source information

Animetake

### Source language

English

### Source new URL

https://animetake.su/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
?
The link above is denied for me, while [animetake.tv](https://animetake.tv),which is currently used by the extension v14.4 works just fine.
