### ISSUE TITLE
Video List Is Empty 

### ISSUE THREAD

**Issue by ZeanSLux** [aniyomiorg/aniyomi-extensions#2920]
### Source information

SFlix 14.24

### Source language

English

### Steps to reproduce

1.Play One Piece live action on SFlix extension
2.Player will show, and closed automatically
3.And you got video list empty message

### Expected behavior

Video Playing Normally

### Actual behavior

Showing Video List Is Empty 

### Aniyomi version

0.15.2.4

### Android version

Android 10

### Other details

👍

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Illythia** [comment]
This is happening with dopebox too

**Comment by tsunaproxD** [comment]
same problem 🤙

**Comment by Secozzi** [comment]
Closing in favour of #2935
