### ISSUE TITLE
GoAnimes: the episodes do not load

### ISSUE THREAD

**Issue by kyhapi** [aniyomiorg/aniyomi-extensions#2926]
### Source information

GoAnimes 14.10

### Source language

Português (Brasil)

### Steps to reproduce

1. choose an anime
2. choose an episode
3. the episode keeps loading without stopping
![Screenshot_20240213_162843_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/147045416/0c16b496-2bc5-4c19-8b99-a2b77444052d)

### Expected behavior

and for the episode to load and start playing

### Actual behavior

the episode keeps loading without stopping

### Aniyomi version

PreView r7493

### Android version

Android 13

### Other details

I checked the webview and the episodes are working normally

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by avinave14102001** [comment]
> ### Source information
> GoAnimes 14.10
> 
> ### Source language
> Português (Brasil)
> 
> ### Steps to reproduce
> 1. choose an anime
> 2. choose an episode
> 3. the episode keeps loading without stopping
>    ![Screenshot_20240213_162843_Aniyomi](https://private-user-images.githubusercontent.com/147045416/304526344-0c16b496-2bc5-4c19-8b99-a2b77444052d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDk2NTQsIm5iZiI6MTcwOTU0OTM1NCwicGF0aCI6Ii8xNDcwNDU0MTYvMzA0NTI2MzQ0LTBjMTZiNDk2LTJiYzUtNGMxOS04Yjk5LWEyYjc3NDQ0MDUyZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQxMDQ5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzU0M2ZhMzkwNDYyZDBkYWFmYTJjYTIyM2ViNGE5YjJhYjFkMjQ0ZjI0ZGNkYTBlNjEwZTQyOTdhYzcwOWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5SzlB677Ke41RINdTVBmgpUZdPF57MPYoYkyMLuyWK4)
> 
> ### Expected behavior
> and for the episode to load and start playing
> 
> ### Actual behavior
> the episode keeps loading without stopping
> 
> ### Aniyomi version
> PreView r7493
> 
> ### Android version
> Android 13
> 
> ### Other details
> I checked the webview and the episodes are working normally
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
> * [x]  If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
> * [x]  I will fill out all of the requested information in this form.

![Screenshot_2024-03-04-07-12-49-29_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/151993381/4b5ee41b-4f44-4250-ae14-3e7ebc0357f8)



I am face this problem

**Comment by Secozzi** [comment]
@avinave14102001 Stop making unrelated comments to isseus
