### ISSUE TITLE
Animeler changed their domain

### ISSUE THREAD

**Issue by kyoyacchi** [aniyomiorg/aniyomi-extensions#2931]
### Source information

Animeler 14.9

### Source language

Turkish

### Source new URL

https://animeler.co/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
uhhhhhh......... no, the domain didn't change, the extension is broken because the _api_ changed. Also, animeler.co redirects to animeler.me (the domain that the extension is using).

**Comment by kyoyacchi** [comment]
![Screenshot_20240215-014428](https://github.com/aniyomiorg/aniyomi-extensions/assets/63583961/8e1bd426-d22c-48b6-aed0-8ba3e9e8dab3)
