### ISSUE TITLE
Sflix & DopeBox Not Play Video? 

### ISSUE THREAD

**Issue by lavara123** [aniyomiorg/aniyomi-extensions#2935]
### Source information

DopeBox 14.25

### Source language

English

### Steps to reproduce

rabbitstream not working maybe change code 

### Expected behavior

Extractor not work (rabbitstream)

### Actual behavior

---

### Aniyomi version

Preview r7493

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tsunaproxD** [comment]
what is happening? there is no solution...

**Comment by LittleFreak** [comment]
Please don't just write "it doesn't work" 🙄

The toast notification says `video list is empty`
