### ISSUE TITLE
Empty video from hsteam

### ISSUE THREAD

**Issue by Craagh** [aniyomiorg/aniyomi-extensions#2948]
### Source name

Hsteam.moe

### Source language

English 

### Source link

Https://hstream.moe

### Other details

Any video from hstream are empty 
![Screenshot_2024-02-17-17-05-59-79_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi-extensions/assets/78241145/fe0287e6-10ea-4792-937b-a80bd9695a02)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
`Error 403` refers to a cloudfare issue, most likely at your end.
hstream.moe is **not** down.

**Comment by kaoru2** [comment]
!close

**Comment by fakebhai** [comment]
try [troubleshooting](https://aniyomi.org/docs/guides/troubleshooting/) if it's still occurring
