### ISSUE TITLE
dopebox and superstream 

### ISSUE THREAD

**Issue by stevenwhat68** [aniyomiorg/aniyomi-extensions#2950]
### Source information

Dope box 14.47Super stream 14.10

### Source language

English 

### Steps to reproduce

The dope box source doesn't show vids anymore for 3 weeks for me so i switch to super stream and now it doesn't work too

### Expected behavior

It should work but no and there is no new update for source

### Actual behavior

The dope box source doesn't show vids anymore for 3 weeks for me so i switch to super stream and now it doesn't work too

### Aniyomi version

0.15.2.4

### Android version

Android 11

### Other details

The dope box source doesn't show vids anymore for 3 weeks for me so i switch to super stream and now it doesn't work too

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Please only create one issue per source
