### ISSUE TITLE
Source Request: NSFW Rule 34

### ISSUE THREAD

**Issue by otakuprograma2020** [aniyomiorg/aniyomi-extensions#2951]
### Source name

NSFW Rule 34

### Source link

https://nsfwr34.com

### Source language

English

### Other details

+18/NSFW=Yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Isn't this the same as the existing rule 34 extension?

**Comment by otakuprograma2020** [comment]
> Isn't this the same as the existing rule 34 extension?

If you open the website you will see that they are different websites
