### ISSUE TITLE
Please fix anime world india

### ISSUE THREAD

**Issue by MaximusSteel777** [aniyomiorg/aniyomi-extensions#2956]
### Source information

Anime world India 14.8

### Source language

Multi 

### Steps to reproduce

When I want to watch any anime it shows 6 secs of the clip

### Expected behavior

To let me watch the whole episode 

### Actual behavior

Shows 6 seconds of the episode 

### Aniyomi version

Preview r7493

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Sohail-XD** [comment]
One workaround for now is to use an external player. Long press the episode and click the bottom right icon and preferably use vlc. 

**Though it should be kept in mind that some series are not playing sounds**

So the best workaround is to change the default user agent in `settings->Advanced->Default User Agents` and paste the first one in this [link](https://www.whatismybrowser.com/guides/the-latest-user-agent/android)
