### ISSUE TITLE
"Drive Website"?

### ISSUE THREAD

**Issue by LbsLightX** [aniyomiorg/aniyomi-extensions#2958]
### Source name

Vadapav

### Source link

https://vadapav.mov/

### Source language

Multi Audio

### Other details

So I found this website a few weeks ago. Provide **"Anime-Movies-TvShow-Documentaries-Others"** It's new although they don't have, I believe, a very large library yet. I know we already have an "edytjedhgmdhm" extension, but it would be nice to have this extension here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by uzuto** [comment]
Second this, it has a huge library of anumekaizoku's content.
