### ISSUE TITLE
HentaiVideos source suggestion

### ISSUE THREAD

**Issue by mobby45** [aniyomiorg/aniyomi-extensions#2966]
### Source name

HentaiVideos

### Source link

https://hentaivideos.net

### Source language

English

### Other details

+18/NSFW = yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [x] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Urahara99** [comment]
Add me some more ----

1.hentai.tv(English)
  *1080p only.
  *Newer uploads are 48fps upscaled.
  *Watermark.
  *Big Library.
  *Soft Sub mostly.

2.ihentai.xyz(Vietnamese)
  *Different qualities.
  *Upscaled.
  *Medium library.
  *Hard Viet sub.

I recommend both for high quality videos ✅.

**Comment by fakebhai** [comment]
> Add me some more ----
> 
> 1.hentai.tv(English)
>   *1080p only.
>   *Newer uploads are 48fps upscaled.
>   *Watermark.
>   *Big Library.
>   *Soft Sub mostly.
> 
> 2.ihentai.xyz(Vietnamese)
>   *Different qualities.
>   *Upscaled.
>   *Medium library.
>   *Hard Viet sub.
> 
> I recommend both for high quality videos ✅.
> 

make a separate issue instead of commenting here
