### ISSUE TITLE
Aniwave: Other video hosts not detected except for Mp4Upload

### ISSUE THREAD

**Issue by MikaelaMuller** [aniyomiorg/aniyomi-extensions#2967]
### Source information

Aniwave 14.66

### Source language

English 

### Steps to reproduce

Watch "The Animatrix"
Check available resolution

### Expected behavior

All version of the anime from all available hosts should be listed.

### Actual behavior

Only Mp4Upload is listed despite all sources being available on the webpage itself.

### Aniyomi version

r7509

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by MikaelaMuller** [comment]
Occasionally the sources are missing entirely.

**Comment by chakibchemso** [comment]
Ye me 2 today none of my animes are loading, it says "video list is empty". Tried reinstalling the extension and clearing cache and cookies tho. I'm using the latest chrome user agent which should be fine. The WebView loads perfectly.

**Comment by KillerDogeEmpire** [comment]
@chakibchemso @MikaelaMuller that's because github took down my key repo. Aniyomi was using my repo to get the keys. I will fix soon

**Comment by chakibchemso** [comment]
@KillerDogeEmpire ok thx, report back when it's done. Aniwave is my main ext. Now I'm left /no anime :'3

**Comment by chakibchemso** [comment]
It's working again! can you confirm? And prob. close this if so!

**Comment by KillerDogeEmpire** [comment]
@chakibchemso that's because I made a scuffed key repo
