### ISSUE TITLE
Chineseanime Not Working

### ISSUE THREAD

**Issue by LyuboA31** [aniyomiorg/aniyomi-extensions#2977]
### Source information

Chineseanime 14.6

### Source language

Multi

### Steps to reproduce

1. Open Chineseanime
2. Choose any of these Anime
Great Doctor Miss Nine, Make Money to be king, Xixing Ji Asura, Primordial Spiritual Lord
those are only few examples most anime don't work

### Expected behavior

to load the chosen episode

### Actual behavior

error: video list is empty

### Aniyomi version

Preview r7509

### Android version

Android 10

### Other details

it's been very long time since Chineseanime hasn't worked properly last several updates didn't fix it 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LyuboA31** [comment]
still same issues after last update

**Comment by LyuboA31** [comment]
14.8 update still has the same issues

**Comment by fakebhai** [comment]
> 14.8 update still has the same issues

pr isn't merged yet, wait for next update
