### ISSUE TITLE
AniWatch extension failing

### ISSUE THREAD

**Issue by ThunderousLeft** [aniyomiorg/aniyomi-extensions#2979]
### Source information

Ani Watch 14.40

### Source language

English

### Steps to reproduce

1. Attempt to use AniWatch extenion

2. Fails

3. Open WebView

4. Page declares AniWatch is rebranding to HiAnime

5. Flee the ad/malware spam because there's no adblock here 

### Expected behavior

Should be able to watch anime

### Actual behavior

Fails to load any new content 

### Aniyomi version

0.15.2.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alphastark** [comment]
AniWatch.to is down and has been re-branded to HiAnime.to

**Comment by 1YuviKing1** [comment]
> AniWatch.to is down and has been re-branded to HiAnime.to. I would think it should be an easy fix to just update URLs in the code

Agreed
