### ISSUE TITLE
Betteranime extension not working 

### ISSUE THREAD

**Issue by Vhiniz** [aniyomiorg/aniyomi-extensions#2984]
### Source information

Betteranime 14.9 (Português)

### Source language

Português (Brazil)

### Steps to reproduce

Ways to reproduce the error 

1 - Open extension 
2 - Do a search
3 - Update an anime that is in this Extension 

### Expected behavior

The expected would be:

1 - The extension opens normally
2 - Get search results 
3 - The anime update

### Actual behavior

![Screenshot_20240302-144333](https://github.com/aniyomiorg/aniyomi-extensions/assets/115049368/58cd85ab-646f-4d36-b217-633742d8ee39)

### Aniyomi version

0.15.2.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by edgardmessias** [comment]
This site was closed by dmca

**Comment by kyhapi** [comment]
> Este site foi fechado pelo dmca

the site is like this to prevent it from crashing, the site works normally if you have an account

**Comment by kyhapi** [comment]
![Uploading Screenshot_20240513-125137.png…]()

**Comment by DollynDeveloper** [comment]
The site works perfectly if you log in to an account on it. But, out of nowhere, the extension started to have playback errors, where either the video does not load or simply plays with problems.

**Comment by DollynDeveloper** [comment]
The Better Animes website is experiencing problems, consequently the extension on Aniyomi as well. But just wait for them to fix it soon.
