### ISSUE TITLE
Gogoanime (Anitaku) not working 

### ISSUE THREAD

**Issue by Ragul32** [aniyomiorg/aniyomi-extensions#2986]
### Source information

Gogoanime 14.79

### Source language

English 

### Steps to reproduce

Just refresh anime library 

### Expected behavior

Show new ep with updated library 

### Actual behavior

If i refresh library i get ! Read error: ssl=0xb40000719211a7c8: Failure in SSL library, usually a protocol error
error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR (external/boringssl/src/ssl/tls_record.cc:592 0xb400007191f65480:0x00000003) 

### Aniyomi version

Preview 7509 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by khaled-0** [comment]
```SSLPeerUnverifiedException: Hostname ajax.gogo-load.com not verified: certificate: sha256/UU+T8/ hxwLx8bH5YZdmf8mnO9pWYO5rDbHOJBu4cnCQ= DN: CN=apnigiftshop.com subjectAltNames: [".apnigiftshop.com, apnigiftshop.com]```

**Comment by Secozzi** [comment]
This is an issue with GoGoAnime's website, not the extension. Wait until they fix it.

**Comment by khaled-0** [comment]
Hey the site is working well now but the extension have the same SSL Error
