### ISSUE TITLE
Add binge-watch.to as an extension for movies and tv shows 

### ISSUE THREAD

**Issue by phoenix02023** [aniyomiorg/aniyomi-extensions#2997]
### Source name

Bingewatch.to

### Source link

https://bingewatch.to/home

### Source language

English 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
It appears to be a mirror of sflix, which already exists as an extension.

**Comment by phoenix02023** [comment]
If it is a mirror then it should also be down when sflix  and dopebox was broken.but it was online during that time

**Comment by Secozzi** [comment]
By "broken", do you mean the extensions are broken?

**Comment by phoenix02023** [comment]
Yes, dopebox and sflix extensions are broken rn right?

**Comment by Secozzi** [comment]
Yes, and since bingewatch is a mirror of sflix it's going to have the exact same issues as the sflix extension, so there isn't any point in adding this.
