### ISSUE TITLE
aniwatch is now hianime

### ISSUE THREAD

**Issue by nfw64** [aniyomiorg/aniyomi-extensions#3002]
### Source information

Aniwatch 14.40

### Source language

English

### Source new URL

https://hianime.to

### Other details

rebrand

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Duplicate of #2979
