### ISSUE TITLE
No episode found gogoanime domain

### ISSUE THREAD

**Issue by akumarsmapp** [aniyomiorg/aniyomi-extensions#3003]
### Source information

Gogoanime 13.78

### Source language

English 

### Steps to reproduce

![Screenshot_2024-03-04-07-12-49-29_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/136121093/0c79af1c-0bba-48fe-88d0-48244cc4ec99)

### Expected behavior

![Screenshot_2024-03-04-17-26-15-24_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/136121093/a4cb6215-6fd1-41e7-9df3-3633e7650289)

### Actual behavior

Episode are not showing 

### Aniyomi version

0.12.13.10

### Android version

Android 11

### Other details

Please they problem are not solved 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
> ### Source information
> 
> Gogoanime 13.78
> 
> ### Source language
> 
> English 
> 
> 
> ### Aniyomi version
> 
> 0.12.13.10
> 
> ### Android version
> 
> Android 11
> 
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> - [X] I have written a short but informative title.
> - [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
> - [X] I have updated all installed extensions.
> - [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).


how much ignorance can you have? app not updated, extension not updated, and extension still sometime works changing dns so not even troubleshooting. it's been already resolved update your app and extension.

**Comment by fakebhai** [comment]
> how much ignorance can you have? app not updated, extension not updated, and extension still sometime works changing dns so not even troubleshooting. it's been already resolved update your app and extension. 
> 

also it's already closed in #2998 which was also opened by you.

**Comment by akumarsmapp** [comment]
But brother episode are not showing his message are coming 
![Screenshot_2024-03-04-07-12-49-29_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/136121093/9dc52742-7fdc-4233-9493-73360e9aa8c9)


![Screenshot_2024-03-04-17-26-15-24_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi-extensions/assets/136121093/357f1f85-285d-4e06-9ddd-abc0567ea9c9)

**Comment by akumarsmapp** [comment]
> > ### Source information
> > Gogoanime 13.78
> > ### Aniyomi version
> > 0.12.13.10
> > ### Acknowledgements
> > 
> > * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> > * [x]  I have written a short but informative title.
> > * [x]  I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
> > * [x]  I have updated all installed extensions.
> > * [x]  I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
> 
> how much ignorance can you have? app not updated, extension not updated, and extension still sometime works changing dns so not even troubleshooting. it's been already resolved update your app and extension.

Brother if I am update my app Manga extensions are not working 😕 like  manga dex, manga reader , e t c are not working after I am update the app 

If have solution please tell me

**Comment by fakebhai** [comment]
> But brother episode are not showing his message are coming

as I said earlier update your extension it's already resolved.

**Comment by akumarsmapp** [comment]
> > But brother episode are not showing his message are coming
> 
> as I said earlier update your extension it's already resolved.

You have a any solution for Manga readings extension are not if I am update my app

**Comment by Secozzi** [comment]
This repo is for anime extension, and anime extensions only. Don't ask for unrelated stuff here
