### ISSUE TITLE
Suggestion: Auto update extensions

### ISSUE THREAD

**Issue by Elixtra** [aniyomiorg/aniyomi-extensions#3004]
### Describe why this should be added

This feature alone can help this project immensely. This feature ensures that users will always have the latest improvements, bug fixes and security patches without any manual intervention. This feature can improve the UI by keeping the app up to date which in turn provides a smooth service. This single feature can allow developers to apply new features seamlessly and effectively, ensuring it remains competitive in adapting to the ever changing needs of users.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open (or closed) issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Don't use ChatGPT to create issues

**Comment by Elixtra** [comment]
Sure I won't use it again but wouldn't something like this improve the platform by alot?
