### ISSUE TITLE
The language does not appear in Latin Spanish

### ISSUE THREAD

**Issue by josefredohd** [aniyomiorg/aniyomi-extensions#3007]
### Source information

Yomiroll 14.30 (spanish)

### Source language

Spanish

### Steps to reproduce

I try to choose the Latin Spanish language for the death note anime, but it does not appear, I have updated aniyomi and yomiroll to the latest version, I also have Latin Spanish chosen as the main audio, and this does not work, I can only choose the Japanese audio .

### Expected behavior

Being able to select Latin Spanish audio

### Actual behavior

Latin audio does not appear, only Japanese

### Aniyomi version

Preview r7509

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by josefredohd** [comment]
@Samfun75 help please

**Comment by josefredohd** [comment]
@Samfun75 Yes, I have the local token activated, and I only see an option in Spanish

**Comment by Samfun75** [comment]
I can't find Death Note bruv even after changing the token to ES and a couple of others, can you send a screenshot of the anime detail?

**Comment by josefredohd** [comment]
![Screenshot_2024-03-05-07-21-47-651_xyz.jmir.tachiyomi.mi.debug.jpg](https://github.com/aniyomiorg/aniyomi-extensions/assets/22134405/ccafb67d-d2d7-4d33-a71e-93185a2fe273)

![Screenshot_2024-03-05-07-22-03-483_xyz.jmir.tachiyomi.mi.debug.jpg](https://github.com/aniyomiorg/aniyomi-extensions/assets/22134405/1e9ac764-9db6-4d06-ab35-7fdd7e84ce4d)

@Samfun75

**Comment by Samfun75** [comment]
Ok I've check with MX and can see the anime but crunchy is not sending the other languages even tho they say they have them, the only other language i could get was french dub using FR token. So, I'm closing this issue as we can't do anything from extension side. best you could do is connect to a vpn where the Spanish dub is available
![image](https://github.com/aniyomiorg/aniyomi-extensions/assets/38332931/aacd86e5-bea7-437b-b946-b513d8f7605a)
