### ISSUE TITLE
Anitube changes URL 

### ISSUE THREAD

**Issue by Vhiniz** [aniyomiorg/aniyomi-extensions#3009]
### Source information

Anitube 14.13

### Source language

Português Brasil 

### Source new URL

Anitube.ninja

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Rey619Gamer** [comment]
![Screenshot_20240305-173211_Edge](https://github.com/aniyomiorg/aniyomi-extensions/assets/59585126/78f873d1-c3b0-473a-84d3-d4462c4897bc)
![Screenshot_20240305-173216_Edge](https://github.com/aniyomiorg/aniyomi-extensions/assets/59585126/c2ab26ac-da46-470b-bac4-ed3d435d5d36)
AniTube continues to be anitube.vip, the site anitube.ninja is another site
