### ISSUE TITLE
Anitube error 

### ISSUE THREAD

**Issue by Vhiniz** [aniyomiorg/aniyomi-extensions#3010]
### Source information

Anitube 14.13

### Source language

Português (Brasil)

### Steps to reproduce

1 - Open an anime in the anitube extension 
2 - Open an episode 

Or

1 - Download an episode 

### Expected behavior

The episode should load and the episode should download.

### Actual behavior

The episode does not load and an error occurs when downloading.

### Aniyomi version

0.15.2.4

### Android version

Android 11

### Other details

(this is a new report, the previous ones have been closed)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kyhapi** [comment]
The website has a problem, the administrators said that the data center motherboard burned out
![Screenshot_20240306-070342~3](https://github.com/aniyomiorg/aniyomi-extensions/assets/147045416/5f8ada9e-ddd5-4ec4-8557-225286e243ad)

**Comment by edgardmessias** [comment]
This was fixed.
