### ISSUE TITLE
aniwave cannot load due to "Security check"

### ISSUE THREAD

**Issue by Nintenstation** [aniyomiorg/aniyomi-extensions#3011]
### Source information

Aniwave  14.66

### Source language

English

### Steps to reproduce

This is a very complicated issue, but I'll try my best to explain. I tried to fix it, but nothing has been working. So I think the aniwave extension needs an update.

Basically it used to work, until I had an extreme bug crash with the app that made it stop completely for an infinite loop. The only solution for me was to literally delete ALL data (including user data) on aniyomi, and even re-installed it. Now I can open it, except it brought another issue... Aniwave refuses to work.

When I open WebView, I notice that it says "security check" and then continues to the aniwave website. This wasn't here before, so it means that it might be the security check that is the issue here. Though I'm not sure, the extension might need an update so we can bypass this, or accept it automatically.

The thing is that it never had this issue before my app crashed entirely, and had to delete everything. Another thing that might be noteworthy is that some of the covers for some anime, like apotheocary diaries, changed. So maybe the website just "changed" after I re-installed the app? This the source might need an update?

If there is a solution to have, such as a new user agent, please tell me. With that being said, already tried ALL of that, and nothing works...

### Expected behavior

What should happen is that I can go to aniwave without it not being able to load. It loaded perfectly fine, but now due to "Security check" it can't

### Actual behavior

This happens instead. Keep in mind that the webview does "succed" loading, but it only does so through security check, which crashes the source itself
![20240305_214653](https://github.com/aniyomiorg/aniyomi-extensions/assets/110612128/0477da9f-bbf6-40d3-99bf-b56313bf55eb)
![20240305_214658](https://github.com/aniyomiorg/aniyomi-extensions/assets/110612128/6e92298e-0efc-4974-a611-e6685eae1440)
![20240305_214708](https://github.com/aniyomiorg/aniyomi-extensions/assets/110612128/728a4b9a-b1d0-4b84-bc13-c64913b132da)

Some examples on my tablet.

### Aniyomi version

Stable 0.15.2.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by tibi22** [comment]
I'm having the same issue. Tried all the debug options but it didn't work.
In the apl web view it loads the security check then the website homepage and then it goes black, while it doesn't do it in an external browser, so it probably gets a redirect or something is blocked when inside the web view.

**Comment by Nintenstation** [comment]
> I'm having the same issue. Tried all the debug options but it didn't work.
> In the apl web view it loads the security check then the website homepage and then it goes black, while it doesn't do it in an external browser, so it probably gets a redirect or something is blocked when inside the web view.

Have you tried user agent string? Try this one: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.164 Mobile Safari/537.36

Ignore if I misunderstood. I'm not well versed, so I suggest asking questions in the discord server for Aniyomi, on the support channel for more. 

Discord: https://discord.com/invite/HA2grg9z

Good luck!
