### ISSUE TITLE
Allanime WebWiew error

### ISSUE THREAD

**Issue by KeremDgGG** [aniyomiorg/aniyomi-extensions#3016]
### Source information

AllAnime 14.31

### Source language

English

### Steps to reproduce

1. View an anime page
2. Press on webview
3. Shows "Error Page" on allanime (allanimenews.com) website

### Expected behavior

Showing webview of the anime

### Actual behavior

Directing to "Error Page" of Allanime

### Aniyomi version

Preview r7509

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
> Actual behavior
Directing to "Error Page" of Allanime
![Screenshot_20240308_102848_Animiru.jpg](https://github.com/aniyomiorg/aniyomi-extensions/assets/53310735/c4647684-73e1-4052-980b-4cad9c3e6470)
That's a cloudfare issue, which you might resolve on your own - or maybe not.
Have you tried the troubleshooting yet, as described in the wiki? 

> "Remember and switch to the last used volume" function doesn't work properly. Even though the last volume is 5 for example, it's stuck at 6 and always opens anime with 6 volume
That's a issue for the main repo

**Comment by KeremDgGG** [comment]
![Screenshot_20240308_125022_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/37026785/97728092-f989-43fc-966f-57e656afaa06)
No, it's not about cloudflare

> > Actual behavior
> > Directing to "Error Page" of Allanime
> 
> Error-Screenshot
> 
> ![Screenshot_20240308_102848_Animiru.jpg](https://private-user-images.githubusercontent.com/53310735/311185638-c4647684-73e1-4052-980b-4cad9c3e6470.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTE2NzQsIm5iZiI6MTcwOTg5MTM3NCwicGF0aCI6Ii81MzMxMDczNS8zMTExODU2MzgtYzQ2NDc2ODQtNzNlMS00MDUyLTk4MGItNGNhZDljM2U2NDcwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA5NDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMmIzNjdmNTFmYjQ4MjA3ZTEyZTNkODI4MmU3NmRjMjEzNjYxMTVlMzQ5MzQwNWZmODMzY2JjNTUzMWExMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.khUrrvkStwmsl83uQ038RooIbwdbJcopNpI0w0BTCEM)
> 
> That's a cloudfare issue, which you might resolve on your own - or maybe not. Have you tried the troubleshooting yet, as described in the [documentation](https://aniyomi.org/docs/guides/troubleshooting/#cloudflare)?
> 
> > "Remember and switch to the last used volume" function doesn't work properly. Even though the last volume is 5 for example, it's stuck at 6 and always opens anime with 6 volume
> 
> That's a issue for the [main repo](https://github.com/aniyomiorg/aniyomi), not here in the extensions

**Comment by KeremDgGG** [comment]
For other problem, looks like I edited it in wrong place
