### ISSUE TITLE
Manga Demon

### ISSUE THREAD

**Issue by Darkon82** [aniyomiorg/aniyomi-extensions#3042]
### Source name

Manga Demon

### Source link

https://demonreader.org/

### Source language

English

### Other details

[Manga Demon 1.4.9.zip](https://github.com/aniyomiorg/aniyomi-extensions/files/14554731/Manga.Demon.1.4.9.zip)

Previously supported in Tachiyomi, extension is not updated anymore and is not working anymore. Can you make a new one? Thx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We don't manage manga extensions
