### ISSUE TITLE
HTTP Error 429 whenever im downloading or reading 

### ISSUE THREAD

**Issue by ss7vegeto12** [aniyomiorg/aniyomi-extensions#3047]
### Source information

999Hentai multi 1.4.5

### Source language

English 

### Steps to reproduce

Search any manga, read it or download it, throws the HTTP error 429.  The extension says obsolete, but i just recently downloaded and read a manga on it.. and if by any chance this is not supported or anything, then y isnt there any hentai extension there ??
![Screenshot_20240313-234022](https://github.com/aniyomiorg/aniyomi-extensions/assets/85555816/c4d519ae-1b49-4861-a62b-09a7fde3952b)
 

### Expected behavior

That when i tap the chapter to open it and read it

### Actual behavior

, it opens, black screen, closes and throws HTTP Error 429

### Aniyomi version

App version: 0.15.2.4-7513 (standard, 1c34c4c1b, 122, 2024-03-10T14:33Z) Android version: 11 (SDK 30; build KF6k-H696AeAgAfAh-R-OP-230323V426) Android build ID: KF6k-H696AeAgAfAh-R-OP-230323V426 Device brand: TECNO Device manufacturer: TECNO MOBILE LIMITED Device name: TECNO-KF6k (KF6k-OP) Device model: TECNO KF6k WebView: Android System WebView 122.0.6261.105 MPVLib version: mpv c6ccabe (Jan 28 2024 15:38:16) Libplacebo version: v7.342.0 FFmpeg version: n6.1.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We don't manage manga extensions, that extension wasn't made by us
