### ISSUE TITLE
Yomiroll - Video list is empty error.

### ISSUE THREAD

**Issue by Luguinhaas** [aniyomiorg/aniyomi-extensions#3049]
### Source information

Yomiroll 14.30

### Source language

Multi

### Steps to reproduce

1. Choose any anime available in the extension
2. Open any episode of the chosen anime
3. the "video list is empty" error appears

### Expected behavior

Episode shoud play

### Actual behavior

Video list is empty

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Other details

https://github.com/aniyomiorg/aniyomi-extensions/assets/163368882/b4d0aa3a-b71a-4ae9-84f5-3d7397c045b8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by josefredohd** [comment]
Same problem

**Comment by dnmodder** [comment]
Same problem here

**Comment by Luffyirl** [comment]
same here

**Comment by Ndido11** [comment]
There is no way to fix it?

**Comment by deepakdiplo** [comment]
When will get this yomiroll extension back...

**Comment by Secozzi** [comment]
Yomiroll is gone and is not coming back, see #3053. Also, please stop commenting on old and irrelevant issues.
