### ISSUE TITLE
After Update Still "List Empty Issue"

### ISSUE THREAD

**Issue by PokiFLIX** [aniyomiorg/aniyomi-extensions#3052]
### Source information

Yomiroll 14.31

### Source language

All

### Steps to reproduce

- Ref.: to Issue #3049 

### Expected behavior

Loading the Anime

### Actual behavior

Video list is Empty error

### Aniyomi version

Preview r7513

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Alexjaison22** [comment]
> ### Source information
> 
> Yomiroll 14.31
> 
> ### Source language
> 
> All
> 
> ### Steps to reproduce
> 
> - Ref.: to Issue #3049 
> 
> ### Expected behavior
> 
> Loading the Anime
> 
> ### Actual behavior
> 
> Video list is Empty error
> 
> ### Aniyomi version
> 
> Preview r7513
> 
> ### Android version
> 
> Android 12
> 
> ### Other details
> 
> _No response_
> 
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> - [X] I have written a short but informative title.
> - [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
> - [X] I have updated all installed extensions.
> - [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
> - [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
> - [X] I will fill out all of the requested information in this form.

Same problem

**Comment by PrimeTwister** [comment]
Yes not yet fixed I think
