### ISSUE TITLE
AnimeFenix cambio de URL

### ISSUE THREAD

**Issue by Entmyer** [aniyomiorg/aniyomi-extensions#3054]
### Source information

AnimeFenix 14.35

### Source language

Español 

### Source new URL

https://vww.animefenix.vip/

### Other details

AnimeFenix.tv ya no aparece y sale un error, pero el otro si se mantiene 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
thats a copycat

**Comment by Secozzi** [comment]
The extension works just fine, follow the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/) for any errors. And as said by bapeey, the url you mentioned doesn't appear to be the legitimate animefenix.

**Comment by Entmyer** [comment]
It just keeps appearing like this and I've already done everything indicated by the troubleshooting guide
![Screenshot_2024-03-16-20-22-59-196_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi-extensions/assets/105583392/90fdec91-5878-441d-bb92-3e49d74a6d39)
