### ISSUE TITLE
Video list empty

### ISSUE THREAD

**Issue by Raey1** [aniyomiorg/aniyomi-extensions#3067]
### Source information

Multimovies 14.17

### Source language

English

### Steps to reproduce

1. Open the last of us
2. Try watching episode 1
3. An error occurs 'video list is empty'

### Expected behavior

The episode should play

### Actual behavior

The episode stops playing and an error occurs saying 'video list is empty'

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Other details

This also happens to some movies and other shows

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by suyash01** [comment]
temporary solution would be to retry the operation as for me retrying helps. You might have to retry few times.
