### ISSUE TITLE
Torrentio Anime: "loading failed"

### ISSUE THREAD

**Issue by edmxn** [aniyomiorg/aniyomi-extensions#3068]
### Source information

Torrentio Anime (Torrent / Debrid) 14.3 (All)

### Source language

All

### Steps to reproduce

1. Open an anime
2. Open episode
3. "loagind failed"

### Expected behavior

Should play the torrent≠episode

### Actual behavior

"loading failed"

### Aniyomi version

Preview r7513

### Android version

Android 12

### Other details

And if you change "torrent≠episode", it just loads and does nothing
- Even if the torrent≠ep have seeds, it just keep loading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
either buy a debrid service and put your token in extension settings or use one of [forks](https://aniyomi.org/forks/) Kuukiyomi to do it locally.
