### ISSUE TITLE
AniWave not loading episodes.

### ISSUE THREAD

**Issue by RumiaSan** [aniyomiorg/aniyomi-extensions#3100]
### Source information

en.nineanime v14.66

### Source language

English

### Steps to reproduce

1. Open AniWave source
2. Select any anime
3. Error toast

### Expected behavior

AniWave should load all episodes as normal.

### Actual behavior

Got this JSON error toast.
![Screenshot_20240326-075224_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/163794124/8bfebd1c-7f6b-471b-90fe-55d687747be5)

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Nek-12** [comment]
Same here

**Comment by Fuzm2** [comment]
Same here too

**Comment by chakibchemso** [comment]
Same 
![Screenshot_20240327_081545_Aniyomi.jpg](https://github.com/aniyomiorg/aniyomi-extensions/assets/41765106/5e566bee-86e9-4ce2-aa16-d12f9cef150f)

**Comment by krishnanunny001** [comment]
Same![Screenshot_2024-03-28-19-33-26-976_xyz.jmir.tachiyomi.mi.debug.jpg](https://github.com/aniyomiorg/aniyomi-extensions/assets/102284873/43175d40-af32-475d-9c8a-0c05c27483f8)

**Comment by jdyaras** [comment]
Same x100¹⁰⁰
