### ISSUE TITLE
Url has changed (PelisPlusTo)

### ISSUE THREAD

**Issue by Latinlee** [aniyomiorg/aniyomi-extensions#3116]
### Source information

Pelisplushd 14.51 (pelisPlusTo)

### Source language

Spanish

### Source new URL

https://www17.pelisplushd.to/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by imper1aldev** [comment]
The domain did not change, it was down. The extension is working correctly.
