### ISSUE TITLE
torrentio anime not working 

### ISSUE THREAD

**Issue by Ndido11** [aniyomiorg/aniyomi-extensions#3128]
### Source information

Torrentio Anime 14.4 (Many languages)

### Source language

All languages

### Steps to reproduce

1.Open anime 2. Play episode 3. It doesn't play and "loading failed" appears 

### Expected behavior

The chapter is already for watch

### Actual behavior

Does not play video and the screen remains black 
![Screenshot_20240404_005611](https://github.com/aniyomiorg/aniyomi-extensions/assets/163615225/5eee2ee0-525a-4714-9333-54c3baca77cb)

### Aniyomi version

Stable 0.15.2.4

### Android version

Android 13

### Other details

What is the token I need?
![Screenshot_20240404_005621](https://github.com/aniyomiorg/aniyomi-extensions/assets/163615225/1532995b-a3e9-4a76-bfd8-b12c26902ebb)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
You need to buy a premium debrid service, the token is an account token you can get from your account settings. Alternatively, you can use [Kuukiyomi](https://aniyomi.org/forks/Kuukiyomi/) since that supports torrent streaming.
