### ISSUE TITLE
HTTP 429

### ISSUE THREAD

**Issue by Lolnod** [aniyomiorg/aniyomi-extensions#3133]
### Source information

999Hentai 1.4.5 (Multi)

### Source language

Multi

### Steps to reproduce

1. First step (I open the extension)
2. Issue here (It says "HTTP 429, check website in WebView")

### Expected behavior

I'm just gonna wait for 15 minutes and everything will be fine.

### Actual behavior

It's been 2 months and it's still the saying the same thing.

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Other details

How do I remove HTTP error 429?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
we don't manage manga extensions, and this repo is only for anime extensions.
