### ISSUE TITLE
Superstream not working

### ISSUE THREAD

**Issue by fam007e** [aniyomiorg/aniyomi-extensions#3143]
### Source name

Superstream

### Source language

English

### Source link

https://showbox.shegu.net/api/api_client/index/

### Other details

The superstream extension doesn't load as it showed I've been blocked even though I didn't download anything or used VPN or anything. Then after this block I even used clear cookies and tried my own IP and then changed via VPN and different DoHs but the problem persists.

![IMG_20240407_095418](https://github.com/aniyomiorg/aniyomi-extensions/assets/19180457/bdfe0468-e3d7-4c27-a401-383fb3726579)
![IMG_20240407_095405](https://github.com/aniyomiorg/aniyomi-extensions/assets/19180457/72ca3108-0be1-486f-8a03-bf5947e3ce4c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by PSYOPUS13** [comment]
Me to.😔

**Comment by Animefamboy** [comment]
I want superstream to be fixed as soon as possible

**Comment by Quicksolverr** [comment]
Even mine didn't working
What happened to super stream i didn't do anything weird or used any vpn still error persists when i open webviews it said you have been blocked but for what reason please someone find out the solution

**Comment by ArchCelestial** [comment]
It is still down.
