### ISSUE TITLE
AnimeUI Dead

### ISSUE THREAD

**Issue by DYoussefMM** [aniyomiorg/aniyomi-extensions#3145]
### Source name

AnimeUI

### Source language

Multi

### Source link

https://animeui.com/

### Other details

They created a new website called sudatchi so the old page will no longer be supported or updated.
![Screenshot_20240407_203928_Kiwi Browser](https://github.com/aniyomiorg/aniyomi-extensions/assets/147215578/752bee8a-5b28-4de3-ae15-e23e12e5ebf0)
![Screenshot_20240407_203819_Kiwi Browser](https://github.com/aniyomiorg/aniyomi-extensions/assets/147215578/14c99023-eed3-4d0e-a8a9-38b879b64c95)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
The site is up and the extension is working (for now)
