### ISSUE TITLE
Seez stopped working

### ISSUE THREAD

**Issue by n1teraven** [aniyomiorg/aniyomi-extensions#3160]
### Source information

Seez 14.8

### Source language

English

### Steps to reproduce

Open any content and you get the following behaviour following error: URLDecoder: illegal hex characters in escape (%) pattern : %c?

### Expected behavior

Content should play

### Actual behavior

following error: URLDecoder: illegal hex characters in escape (%) pattern : %c?

### Aniyomi version

0.15.2.4

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by paravabasculus** [comment]
yeah same error
