### ISSUE TITLE
Add Voiranime

### ISSUE THREAD

**Issue by Zerlaxv1** [aniyomiorg/aniyomi-extensions#3164]
### Source name

voiranime

### Source link

https://v5.voiranime.com/

### Source language

French

### Other details

in the [issue 33](https://github.com/aniyomiorg/aniyomi-extensions/issues/33) the github bot said to open a new request 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by InjuredVolt** [comment]
I want too
