### ISSUE TITLE
Hentai stream(Hstream) Search isn't working!

### ISSUE THREAD

**Issue by Yuv-Sama-00** [aniyomiorg/aniyomi-extensions#3195]
### Source information

Hstream 14.7 (English)

### Source language

English

### Steps to reproduce

1 Open the Hstream
2 Try to search a hentai for example :- Master piece the animation
3 It would show the buffering circle but instead of search results it shows the popular.

### Expected behavior

I don't know,
Coding Error!

### Actual behavior

Refresh the page instead of search!

### Aniyomi version

r7519

### Android version

Android 11

### Other details

Please also check other hentai extension, some these are also not working like java null expecation, empty video link, no tags!, etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Yuv-Sama-00** [comment]
jmir1 Hey but search is still not working.

**Comment by fakebhai** [comment]
re-open it secco

**Comment by Yuv-Sama-00** [comment]
> re-open it secco

Nope, it's not working Should I upload a Screen Recording but it will contain NSFW stuff hope git don't ban me for this!!?

**Comment by Secozzi** [comment]
> > re-open it secco
> 
> Nope, it's not working Should I upload a Screen Recording but it will contain NSFW stuff hope git don't ban me for this!!?

Don't send NSFW images/videos here

**Comment by Yuv-Sama-00** [comment]
> > > re-open it secco
> > 
> > 
> > Nope, it's not working Should I upload a Screen Recording but it will contain NSFW stuff hope git don't ban me for this!!?
> 
> Don't send NSFW images/videos here

Okay! 👌
