### ISSUE TITLE
Torrentio Anime (Torrent/Debrid) Extension Showing Empty Video link while downloading a Episode.

### ISSUE THREAD

**Issue by Yuv-Sama-00** [aniyomiorg/aniyomi-extensions#3196]
### Source information

Torrentio 14.5 (Multi)

### Source language

Multi

### Steps to reproduce

1 Open Torrentio.
2 Click on an anime.
3 Long press on download icon for any episode.
4 Error:- Empty Video Link.

### Expected behavior

I don't know,
I'm up to date of every extension that I has been using.

### Actual behavior

Code Error happened after I updated the extension.

### Aniyomi version

r7519

### Android version

Android 11

### Other details

Here's a Clip👇

https://github.com/aniyomiorg/aniyomi-extensions/assets/166005207/d8c48d64-7cc9-4e76-bb4f-13f2a0246efe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
try refreshing your episode list and if still doesn't work do troubleshooting steps as mentioned in acknowledgements above.

and if you aren't aware, you'll need debrid service to use this extension in aniyomi

**Comment by Yuv-Sama-00** [comment]
> try refreshing your episode list and if still doesn't work do troubleshooting steps as mentioned in acknowledgements above.
> 
> and if you aren't aware, you'll need debrid service to use this extension in aniyomi

I am now logged in to by using Debrid link and created an API token and entered in extension setting still I don't get any links why?

**Comment by ni3x** [comment]
> > try refreshing your episode list and if still doesn't work do troubleshooting steps as mentioned in acknowledgements above.
> > and if you aren't aware, you'll need debrid service to use this extension in aniyomi
> 
> I am now logged in to by using Debrid link and created an API token and entered in extension setting still I don't get any links why?

Debird is a paid service, if you dont have valid debird accout with subscription, it won't provide any links.

**Comment by Yuv-Sama-00** [comment]
> > > try refreshing your episode list and if still doesn't work do troubleshooting steps as mentioned in acknowledgements above.
> > > and if you aren't aware, you'll need debrid service to use this extension in aniyomi
> > 
> > 
> > I am now logged in to by using Debrid link and created an API token and entered in extension setting still I don't get any links why?
> 
> Debird is a paid service, if you dont have valid debird accout with subscription, it won't provide any links.

But there's an "None" option in selector and it says select none to use/get torrents.
No need to enter a token if you have selected "None".. 
Doesn't that mean If a user selected none as default it gets torrent link.
Here see I'm currently using a telegram bot to get the same link where I get from the torrentio!
![image](https://github.com/aniyomiorg/aniyomi-extensions/assets/166005207/b7b4d653-445a-40ab-a00f-370c91711b78)

**Comment by Yuv-Sama-00** [comment]
Now it's working, there's a small little mistake from my side I'm literally Sorry for troubling that much I'm closing this Cause it's no longer a problem now..
![Screenshot_2024-05-10-16-12-44-73_3d72c870acdf8f5b3cd76c4f6ede4fa1](https://github.com/aniyomiorg/aniyomi-extensions/assets/166005207/5a25a3e8-3d75-44ed-aaae-920363760db3)
