### ISSUE TITLE
[Source Request] <YouTube>

### ISSUE THREAD

**Issue by karmakarmeghdip** [aniyomiorg/aniyomi-extensions#320]
## Source website
- Name: YouTube
- Link: youtube.com
- Language(s): Whatever you need....

## Other details
So yeah, this might be a surprise but YouTube actually has a lot of anime that can be watched for free legally. A lot of channels simulcast latest releasing anime on YouTube for free. 

Now contrary to what most people think, making a youtube plugin should be fairly easy as long as you know how to make REST API requests. There's this awesome project called invidious.io that exposes an api that can be used to get stream links. An option can be added in the plugin settings to enter the url to an invidious instance. This should be fairly easy since I have used the invidious api using curl in a shell script. I would create the plugin myself but I am not even remotely familiar with Android development and Kotlin... So please help me out!

**Comment by Lukyzzz** [comment]
Not gonna lie.... It would be sick

**Comment by TheMadHau5** [comment]
Bump! Has there been any work done regarding this?

**Comment by Secozzi** [comment]
Any and all work done will be shown here, you can subscribe to get notifications on it. Since nothing has been done since February last year it just means that no one is willing to work on this. Also, please do not "bump" issues as it doesn't help with anything.
