### ISSUE TITLE
Anime dekh

### ISSUE THREAD

**Issue by SazAnsari** [aniyomiorg/aniyomi-extensions#3203]
### Source name

anime dekho

### Source link

https://animedekho.net

### Source language

HINDI

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Nastherapper** [comment]
When it's gonna fix ?

**Comment by Secozzi** [comment]
> When it's gonna fix ?

It will be added whenever someone takes the time to code together an extension, and that could take anywhere from a few hours to a few years
