### ISSUE TITLE
MonosChinos extension appears to be broken

### ISSUE THREAD

**Issue by P10Ms** [aniyomiorg/aniyomi-extensions#3212]
### Source information

MonosChinos 14.27

### Source language

Spanish

### Steps to reproduce

1. Enter the app
2. Go to extensions
3. Open the extension

### Expected behavior

The extension should show up all the animes on the frontpage and would show up results when searching anime.

### Actual behavior

The extension doesn't show any animes and appears to be broken.

Image of what appears when entering the extension:
![image](https://github.com/aniyomiorg/aniyomi-extensions/assets/101501651/be7de650-efd5-4a61-8f50-2fc6137d9086)

### Aniyomi version

Preview r7519

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Kinoris** [comment]
It's sad that 3 weeks have passed and the extension is still not working
