### ISSUE TITLE
cambio de Fuente

### ISSUE THREAD

**Issue by rcuvas** [aniyomiorg/aniyomi-extensions#3231]
### Source information

https://tecnoscann.com/

### Source language

español

### Source new URL

https://visortecno.com/

### Other details

![SmartSelect_20240513_102458_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/82910307/f378b250-85b3-4661-a973-66abcbade1f4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
That's not an extension we manage
