### ISSUE TITLE
cambio de fuerte

### ISSUE THREAD

**Issue by rcuvas** [aniyomiorg/aniyomi-extensions#3232]
### Source information

https://olympusv2.gg/

### Source language

español

### Source new URL

https://leelolympus.com/

### Other details

![Screenshot_20240513_102929_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/82910307/6df61c11-1422-42d4-ace2-0e6cb0766d5f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
That's not an extension we manage
