### ISSUE TITLE
Cambio de fuente

### ISSUE THREAD

**Issue by rcuvas** [aniyomiorg/aniyomi-extensions#3235]
### Source information

https://mangasnosekai.com

### Source language

Español 

### Source new URL

https://mangasnosekai.com/

### Other details

![Screenshot_20240513_113952_Aniyomi](https://github.com/aniyomiorg/aniyomi-extensions/assets/82910307/8763a9f1-0b7a-4a45-a983-cec678d5368b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Diegopyl1209** [comment]
@rcuvas oye aweonao deja de abrir issues

**Comment by meowmeowofthemeows** [comment]
@rcuvas DEJA DE ABRIR PROBLEMAS MONO MATARÉ A TODA TU FAMILIA SI CONTINÚAS
