### ISSUE TITLE
GoAnimes Changed Domain 

### ISSUE THREAD

**Issue by DollynDeveloper** [aniyomiorg/aniyomi-extensions#3236]
### Source information

GoAnimes 14.14

### Source language

Portuguese Brazil

### Source new URL

https://www.goanimes.vip/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by edgardmessias** [comment]
This domain looks like https://www.hinatasoul.com/ (That the source videos are from https://www.anitube.vip/)
