### ISSUE TITLE
Animevietsub sour e request

### ISSUE THREAD

**Issue by Karutovn** [aniyomiorg/aniyomi-extensions#3239]
### Source name

Animevietsub 

### Source link

https://animevietsub.fun/

### Source language

Vietnamese 

### Other details

18+/nsfw = false
Website fanpage: https://www.facebook.com/animevsub?mibextid=ZbWKwL

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Karutovn** [comment]
@Secozzi why do you close this (this web don't have dmca notice) 🥲

**Comment by Secozzi** [comment]
We're not adding any new extension, unless they're for self hosted stuff
