### ISSUE TITLE
BetterAnime domain change

### ISSUE THREAD

**Issue by edgardmessias** [aniyomiorg/aniyomi-extensions#3252]
### Source information

Better Anime 14.9

### Source language

Portuguese

### Source new URL

https://betteranime.ws/

### Other details

I don't know if this domain is from the same owner, but it uses the same icon.
This domain uses the "animestream" theme

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by kyhapi** [comment]
I believe this is a fake website trying to pretend to be batter animes, the original website is working normally, but its extension is crashing the app

https://github.com/aniyomiorg/aniyomi-extensions/assets/147045416/89d500bd-a060-48e8-9999-3635780b6d80
