### ISSUE TITLE
Aniwave 

### ISSUE THREAD

**Issue by BlackMosss** [aniyomiorg/aniyomi-extensions#3254]
### Source information

Aniwave 14.69

### Source language

English 

### Steps to reproduce

3. No results found 

### Expected behavior

I think there's a problem with their website or domain

### Actual behavior

![20240521_085917](https://github.com/aniyomiorg/aniyomi-extensions/assets/170400147/d77ee797-cca8-4ea2-9fab-a40f259baa75)

### Aniyomi version

R7540

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by cgytrus** [comment]
aniwave seems to have made their cloudflare configs more strict, possibly also added more of their own protection
opening in webview causes the website to immediately redirect to the home page, opening in browser reveals 2 captchas, first one before loading the page, second one before playing the video
