### ISSUE TITLE
AnumeSAGA

### ISSUE THREAD

**Issue by L1veu** [aniyomiorg/aniyomi-extensions#3258]
### Source information

AnimeSAGA14.10

### Source language

Hindi

### Source new URL

https://hindidubbed4u.in/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by L1veu** [comment]
No it is not duplicate

**Comment by fakebhai** [comment]
> No it is not duplicate 

you used wrong source url

> Source new URL

> https://hindidubbed4u.in/
