### ISSUE TITLE
New Manga Source: Mangalife

### ISSUE THREAD

**Issue by ShataayuM** [aniyomiorg/aniyomi-extensions#3259]
### Source name

Mangalife

### Source link

https://manga4life.com/

### Source language

English

### Other details

It opens and has most mangas .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ShataayuM** [comment]
.

**Comment by fakebhai** [comment]
we won't make/manage manga extensions. this repo is for anime extensions.
