### ISSUE TITLE
AnimeUnity: Fetch video failed

### ISSUE THREAD

**Issue by mklive** [aniyomiorg/aniyomi-extensions#3269]
### Source information

"AnimeUnity 14.8"

### Source language

Italian 

### Steps to reproduce

Try to watch an episode from any anime hosted by AnimeUnity 

### Expected behavior

Video player should load with selected episode

### Actual behavior

"Failed to fetch video" error

### Aniyomi version

Preview r7567

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Freal5** [comment]
Did you solve it? Because I have the same problem with streaming community
