### ISSUE TITLE
Fmovies Domain change

### ISSUE THREAD

**Issue by Glitched027** [aniyomiorg/aniyomi-extensions#3272]
### Source name

FMovies 14.24

### Source link

https://thefmovies.org/

### Source language

English 

### Other details

This should work more smoothly for everyone who's facing problem with fmovies.to

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
That's not an alternative domain for fmovies, but rather a fake clone site.
