### ISSUE TITLE
Sudatchi

### ISSUE THREAD

**Issue by i0x404** [aniyomiorg/aniyomi-extensions#3274]
### Source information

all.sudachi 14.1

### Source language

Multi

### Source new URL

https://sudatchi.com/

### Other details

they changed the website link now it's not working in aniyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
That's the url that the extension is using
