### ISSUE TITLE
Source Request: Hdtoday.tv

### ISSUE THREAD

**Issue by ArchCelestial** [aniyomiorg/aniyomi-extensions#3277]
### Source name

HdToday

### Source link

https://hdtoday.tv/

### Source language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ArchCelestial** [comment]
there are shows/movies on hdtoday that sflix doesn't and besides, sflix shows an empty video list most times

**Comment by Secozzi** [comment]
> there are shows/movies on hdtoday that sflix doesn't 

Such as?

**Comment by ArchCelestial** [comment]
house as a show that shows an empty video list

**Comment by ArchCelestial** [comment]
nvr mind about the tv show and movie thing not showing up on both, I was looking at the wrong extension
