### ISSUE TITLE
Extension 

### ISSUE THREAD

**Issue by ymewto** [aniyomiorg/aniyomi-extensions#3281]
### Describe why this should be added

A list of manga extensions so people can read different manga

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open (or closed) issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This repo is only for anime extensions.

**Comment by ymewto** [comment]
> This repo is only for anime extensions.

Who does manga?

**Comment by Secozzi** [comment]
The official place for manga extensions is gone, and we will not share or endorse any third party manga extension repos
