### ISSUE TITLE
Fmovies

### ISSUE THREAD

**Issue by kb2010** [aniyomiorg/aniyomi-extensions#3287]
### Source information

14.24

### Source language

English

### Source new URL

fmovies.to

### Other details

It's moved from fmoviez.to to fmovies.to

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by kb2010** [comment]
I think this one needs to change in fmovies.kt

override val baseUrl = "https://fmoviesz.to"

To 

override val baseUrl = "https://fmovies.to"

**Comment by usyboi** [comment]
Please update fmovies domain to https://fmovies24.to/

**Comment by Claude-Kenni** [comment]
> Please update fmovies domain to https://fmovies24.to/

This one
