### ISSUE TITLE
Pobreflix extension changed url.

### ISSUE THREAD

**Issue by Vhiniz** [aniyomiorg/aniyomi-extensions#3290]
### Source information

Pobreflix 14.9

### Source language

Pt br

### Source new URL

https://pobreflix1.art/

### Other details

Old URL: https://pobreflix.biz/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by edgardmessias** [comment]
The `SuperFlixExtractor` needs some changes.
The source to extract: `https://superembeds.com/`
The source `https://supercdn.org/` is the same of `SuperFlixExtractor`
