### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AZE0k** [aniyomiorg/aniyomi-extensions#3313]
### Source name

Superstream

### Source language

English 

### Source link

https://showbox.shegu.net/api/api_client/index/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Duplicate of #3305
