### ISSUE TITLE
Video not playing and showing this error: java.lang.Exception: bruh

### ISSUE THREAD

**Issue by InjuredVolt** [aniyomiorg/aniyomi-extensions#3316]
### Source information

AnimeVostFr

### Source language

French

### Steps to reproduce

So I go to the Aniyomi application, I go to explore, then to the source: AnimeVostFr, I click on a random anime then I click on the first episode, the loading time is quite long, like thirty seconds, then the video player closes and displays this error: java.lang.Exception:bruh. Which I find quite weird then I try to watch another episode, for example episode 3, I still have the same error then another episode, I still have the same error, I change anime then I click on a random episode, I still have the same error, I tell myself that there would be no problem in web view and then I see that there is a problem that there is not on browsers like: chrome, firefox. Problem that I sent you as an attachment, thank you for fixing the problem.
![Screenshot_2024-06-07-14-51-19-474_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi-extensions/assets/172069340/036debe2-d98a-417d-b5a8-e46b1af097ac)

### Expected behavior

The expected behavior is that the anime episode should launch normally without exiting the player and displaying an error code.

### Actual behavior

The actual behavior is that: when I launch an episode of an anime in this extension, the video player closes and displays the error that I previously told you.

### Aniyomi version

0.15.3.0

### Android version

Android 13

### Other details

![Screenshot_2024-06-07-14-51-19-474_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi-extensions/assets/172069340/87d6d22a-5e59-45e9-8b0f-47709ee996be)
![Screenshot_2024-06-07-14-19-55-677_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi-extensions/assets/172069340/fbe9821a-c9c0-494c-9e46-ae0fe507b380)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by hollowshiroyuki** [comment]
bruh
