### ISSUE TITLE
Search problem on extension: AniSama

### ISSUE THREAD

**Issue by InjuredVolt** [aniyomiorg/aniyomi-extensions#3321]
### Source information

14.4

### Source language

French

### Steps to reproduce

When I want to search for an anime on the extension, it gives me any anime except the anime I'm looking for, it always gives me the same anime, no matter the search, moreover when I click on an anime, the episodes are not displayed, it gives me an error code instead, error code that you can find on the attachment below.
![Screenshot_2024-06-09-10-31-28-536_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi-extensions/assets/172069340/6de022cd-0f51-449d-a4da-18da543815a1)

### Expected behavior

What should happen is that: the search should lead me to the desired anime, and that by clicking on an anime it should have episodes displayed.

### Actual behavior

Instead it does the complete opposite of the expected behavior.

### Aniyomi version

0.15.3.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by hollowshiroyuki** [comment]
#3292 duplicate :3c
