### ISSUE TITLE
Please add Pornhub

### ISSUE THREAD

**Issue by Darkwater409** [aniyomiorg/aniyomi-extensions#3336]
### Source name

Pornhub

### Source link

https://www.pornhub.com

### Source language(s)

English, German, French, Spanish, Italian, Portuguese, Polish, Russian, Japanese, Dutch, Czech, Simplified Chinese

### Other details

The unofficial `all-pornhub` extension in the `jmir1/unofficial-aniyomi-extensions` repo doesn't work anymore, and that repo is now archived. 

So I would like to see a working extension for pornhub with filters added to this repo if anyone is up for it.

**+18/NSFW** = yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by hollowshiroyuki** [comment]
for the love of god, take a shower, go outside and touch some grass 💀

**Comment by Darkwater409** [comment]
> for the love of god, take a shower, go outside and touch some grass 💀

How bout instead of being a dick, you simply ignore requests you're not interested in.

**Comment by hollowshiroyuki** [comment]
nuh uh
+ cope
+ take a shower
+ already exists https://github.com/jmir1/unofficial-aniyomi-extensions/raw/repo/apk/aniyomi-all.pornhub-v13.6.apk

mods i urge you to close this issue at once

**Comment by Darkwater409** [comment]
> nuh uh
> + cope
> + take a shower
> + already exists https://github.com/jmir1/unofficial-aniyomi-extensions/raw/repo/apk/aniyomi-all.pornhub-v13.6.apk
> 
> mods i urge you to close this issue at once

Like I said, that one is broken. So stop being a dick and do your research.

**Comment by Darkwater409** [comment]
I've updated my post with more information about my source request. It should be better detailed now.

**Comment by meowmeowofthemeows** [comment]
brother get help, if you want pornhub go make it yourself. I agree with @hollowshiroyuki you should close this issue and make it not planned. and call him a dumbass :laughing:
