### ISSUE TITLE
There's no extension left !!!!

### ISSUE THREAD

**Issue by RuDru-OP** [aniyomiorg/aniyomi-extensions#3341]
### Source information

Hi anime, Gogoanime... nothing!!

### Source language

English

### Steps to reproduce

Open Animiru/aniyomi
Go to browse→extensions

### Expected behavior

Should give a list of All extensions available.... Atleast the languages

### Actual behavior

There are no extensions other than Google drive, Index and Jellyfin

### Aniyomi version

Animiru 17.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Due to a dmca takedown notice, we've had to remove most of our extensions. They're not coming back.

**Comment by RuDru-OP** [comment]
> Due to a dmca takedown notice, we've had to remove most of our extensions. They're not coming back.

That means the lucky ones like Me are only left with one extension.... DMCA do be fucking around with us aye

**Comment by RuDru-OP** [comment]
why don't you try this ?? 

Make a torrent file with All usable extensions in it and Place it somewhere like an easter egg

**Comment by Secozzi** [comment]
> why don't you try this ??
> 
> Make a torrent file with All usable extensions in it and Place it somewhere like an easter egg

No, we're not going to provide the old extensions.

**Comment by Secozzi** [comment]
> Then....Is it over???

You can still add third party repositories, but we won't provide where to find them nor any support for them.
