### ISSUE TITLE
all extraction are gone

### ISSUE THREAD

**Issue by V25king** [aniyomiorg/aniyomi-extensions#3342]
### Source link

Aniyomi

### Other details

Obsolete

### Requirements

- [X] Proof of ownership/intent to remove sent to a Aniyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

**Comment by Secozzi** [comment]
We took down our extensions due to a DMCA notice

**Comment by Wenuraka** [comment]
Will the app be usable again? 🧐
(Because there is nothing in the app now.)

**Comment by Secozzi** [comment]
The app is absolutely useable, there just won't be any official extensions. Feel free to use third party extensions (and no, we won't provide where to find them)
