### ISSUE TITLE
[Bug] <XS Anime>: <can't choose video quality>

### ISSUE THREAD

**Issue by Mua10** [aniyomiorg/aniyomi-extensions#335]
**PLEASE READ THIS**

I acknowledge that:

- I have updated:
  - To the latest version of the app (stable is v0.10.12)
## Device information Honor 7s
- Tachiyomi version:0.12.3.6
- Android version: 8.0

## Source information
- Name: XS Anime
- Extension version: 12.7

## Steps to reproduce
1. First Step
Go to extension settings
2. Second Step
Choose highest quality

### Expected behavior
Videos to play in high quality

### Actual behavior
Videos playing in low quality

**Comment by Secozzi** [comment]
Closing is this appears to be an issue with the website, not the extension. The extension will only use the qualities that the website provides, if there only exists low qualities then there's nothing aniyomi can do about it.
