### ISSUE TITLE
AnimeQ extension does not play 1080p videos.

### ISSUE THREAD

**Issue by Vhiniz** [aniyomiorg/aniyomi-extensions#3357]
### Source information

AnimeQ 14.1

### Source language

Portuguese (Brazil).

### Steps to reproduce

1 - Open an episode that has 1080p resolution.
2 - Select 1080p resolution.

### Expected behavior

The episode was supposed to play in 1080p.

### Actual behavior

The video goes black and the message appears: "loading failed".

### Aniyomi version

0.15.3.0

### Android version

Android 11.

### Other details

![Screenshot_20240622-094423](https://github.com/aniyomiorg/aniyomi-extensions/assets/115049368/de4ad834-abd9-4066-9a3a-67c6849940e0)

There is no problem on the extension website.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We do not support this extension.

**Comment by Vhiniz** [comment]
Could you tell me why?

Em sáb., 22 de jun. de 2024 09:49, Secozzi ***@***.***>
escreveu:

**Comment by Secozzi** [comment]
We removed almost all of our extensions due to a dmca notice, animeq being one of them. We don't support extensions that we removed (they show up as "obsolete" in the app)

**Comment by Vhiniz** [comment]
What will happen to the Aniyomi app? It is not possible to watch anime with just the three extensions.

**Comment by Secozzi** [comment]
See #3341
