### ISSUE TITLE
Extension source issue

### ISSUE THREAD

**Issue by Chickenshrimps** [aniyomiorg/aniyomi-extensions#3359]
### Source information

Kimoitv V14.1

### Source language

English 

### Steps to reproduce

1. Open Kimoitv source
2.Cloudfare Pass through by adding chrome user agent in settings
3. Open a certain movie title
4. Unable to fetch video when clicked on play button 

### Expected behavior

Video should be fetched directly from website and start playing 

### Actual behavior

![Screenshot_2024_0625_102840](https://github.com/aniyomiorg/aniyomi-extensions/assets/108865702/a0327a9d-7e20-4776-9663-82c6cc4a4546)

### Aniyomi version

Animiru fork

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Kimoitv is not a source we manage

**Comment by Chickenshrimps** [comment]
> Kimoitv is not a source we manage

Then why is there a source in the app if you don't 
FYI I use Animiru app , a fork of Aniyomi which has anime section only and since all the extension got took down, I used extensions repo source code to download source. If you don't manage it, tell me who does 😠

**Comment by Secozzi** [comment]
> If you don't manage it, tell me who does 😠

No, we don't associate with or support any third party repo/extension.

**Comment by Chickenshrimps** [comment]
Ok. But pls look forward for implementing it for future updates since that third party repo /extension has almost every media source you could possibly think of. 
It has Anime,Tv shows, Hollywood movies, Korean & Chinese shows, animated Movies and manga too 
Just that, it has issues while passing cloudfare and downloading it

**Comment by Secozzi** [comment]
The app already has support for adding third party extensions

**Comment by Chickenshrimps** [comment]
Yes I have issues for that particular extension

**Comment by Chickenshrimps** [comment]
Pls resolve it or look upon yourself

**Comment by Secozzi** [comment]
> Pls resolve it or look upon yourself

I already told you, we don't support this extension anymore and we won't give any support to third party extensions either. If you have any problems with third party extension, you should contact whoever is in charge of the extension repo, not us.
