### ISSUE TITLE
Why removed lot of extensions?

### ISSUE THREAD

**Issue by iocmet** [aniyomiorg/aniyomi-extensions#3364]
### Describe why this should be added

I don't want use template

### Other details

https://github.com/aniyomiorg/aniyomi-extensions/commit/cc6cffd7003b57368b0fe4a96a32bac583874080

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open (or closed) issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Because we were hit with a DMCA notice. See #3341
