### ISSUE TITLE
Eporner

### ISSUE THREAD

**Issue by CP665** [aniyomiorg/aniyomi-extensions#3366]
### Source name

Eporner 

### Source link

https://www.eporner.com/

### Source language

English 

### Other details

+18 = yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Due to a dmca takedown, we had to remove almost all of our extensions. It also means we won't make any new ones like this
