### ISSUE TITLE
Aniwave Json problem

### ISSUE THREAD

**Issue by Lofikoi** [aniyomiorg/aniyomi-extensions#3368]
### Source information

AniWave

### Source language

Emglish

### Steps to reproduce

Just clicking on a anime, it shows a Json error offset 23 etc...

### Expected behavior

It should show the episode 

### Actual behavior

It doesn't show any episodes and just show the error I mentioned.

### Aniyomi version

Latest

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We don't manage that extension anymore.

**Comment by Lofikoi** [comment]
> We don't manage that extension anymore.

Does anyone else manage it ?

**Comment by Secozzi** [comment]
We only manage the app nowadays, any extensions apart from the one already present in this repo are managed by someone else. We're not affiliated with any of them and will not provide any.
