### ISSUE TITLE
Fmovies

### ISSUE THREAD

**Issue by MrD005** [aniyomiorg/aniyomi-extensions#3369]
### Source information

Fmovies

### Source language

English 

### Source new URL

https://en.fmoviesz-to.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
1. That's a fake clone site, not the real fmovies site
2. We don't manage that extension anymore
