### ISSUE TITLE
NyoPon website

### ISSUE THREAD

**Issue by gabriidev** [aniyomiorg/aniyomi-extensions#3371]
### Source name

Nyo Source

### Source link

https://www.nyo-pon.com

### Source language

Spanish

### Other details

"+18/NSFW = yes"
Name: NyoPon
The website is made for WordPress. :)
Logo:
![20240802_183604] (https://github.com/user-attachments/assets/114811cf-6226-4c1e-8c67-bff9ff98543b) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Due to a DMCA notice, we will not make any more extensions.
