### ISSUE TITLE
Yomovies

### ISSUE THREAD

**Issue by Sense5543** [aniyomiorg/aniyomi-extensions#3372]
### Source information

https://yomovies.Town/

### Source language

Hindi

### Source new URL

https://yomovies.my/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Due to a DMCA takedown, we won't add any more extensions.
