### ISSUE TITLE
hanime.tv can't play videos

### ISSUE THREAD

**Issue by nivyanyctra** [aniyomiorg/aniyomi-extensions#3373]
### Source information

hanime.tv 14.18 (English)

### Source language

English

### Steps to reproduce

1. Open the anime I want to watch
2. Stream or play videos after downloading
3. An error appears 'unrecognized file format'
![Screenshot_2024-08-13-19-39-44-007_xyz jmir tachiyomi mi](https://github.com/user-attachments/assets/eeac77f7-f4e4-4b1d-b68e-f2d508e9e448)

### Expected behavior

Play videos smoothly

### Actual behavior

An error appears 'unrecognized file format'

### Aniyomi version

0.16.4.3 

### Android version

Android 13

### Other details

App version: 0.16.4.3 (standard, 959f84a, 124, 2024-07-01T22:25Z)
Android version: 13 (SDK 33; build TP1A.220624.014)
Android build ID: TP1A.220624.014
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: rosemary (rosemary_id)
Device model: M2101K7BNY
WebView: Android System WebView 127.0.6533.103
MPV version: 4d32db2
Libplacebo version: v7.349.0
FFmpeg version: n7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We do not maintain that extension anymore.
