### ISSUE TITLE
aniyomi extension yomovies 

### ISSUE THREAD

**Issue by Jashanbhakar** [aniyomiorg/aniyomi-extensions#3374]
### Source name

yomovies 

### Source language

hindi

### Source link

https://yomovies.my

### Other details

when we open the extension in aniyomi app it shows all the movies and other series but when we try to open it or play the video it doesn't open and show some kind of extension issue and if we try to open it in webview  then it shows webpage not found but before it shows webpage not found it shows us a different website for some seconds prmovies  (https://prmovies.my) . And after some research i found that there is some kind of code issue in extension .  the website of yomovies is working on browser if open it without extension .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Due to a DMCA takedown, we won't add any more extensions.
