### ISSUE TITLE
Http Error 404: Animepahe

### ISSUE THREAD

**Issue by givmemoneypls** [aniyomiorg/aniyomi-extensions#3375]
### Source name

Animepahe

### Source language

English

### Source link

https://animepahe.ru/

### Other details

Whenever I redownload Aniyomi, it works but suddenly stops after like a week or two and keeps saying "HTTP ERROR 404"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We don't manage that extension anymore.
