### ISSUE TITLE
AniWave returning Json error code upon opening any anime

### ISSUE THREAD

**Issue by ArtonGX** [aniyomiorg/aniyomi-extensions#3376]
### Source information

Aniwave 14.74 (English)

### Source language

English

### Steps to reproduce

1. open aniwave extension
![Screenshot_2024-08-18-01-02-46-21_dd604340c1d7941d42aee14dd16e00e8](https://github.com/user-attachments/assets/60283d16-d1c6-425b-b52d-5c4be1313fee)

2. open any anime
![Screenshot_2024-08-18-01-02-53-10_dd604340c1d7941d42aee14dd16e00e8](https://github.com/user-attachments/assets/3d1eefe1-cd3d-4645-84a5-5b849048db4b)

### Expected behavior

Should open a list with all the episodes

### Actual behavior

instead returns an empty list and a long Json error code

### Aniyomi version

Stable 0.16.4.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We don't manage that extension anymore.
