### ISSUE TITLE
MovierulzHD

### ISSUE THREAD

**Issue by Itz-Jay** [aniyomiorg/aniyomi-extensions#3381]
### Source name

MovierulzHD

### Source link

https://1movierulzhd.bar/movierulz-2024-watch-free-movies-online-hindi-telugu-tamil-english/

### Source language

English ,Hindi , Telugu , Tamil , Kannada 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Due to a DMCA takedown notice, we will not add any more piracy streaming sites
