### ISSUE TITLE
No results found

### ISSUE THREAD

**Issue by aggreyas** [aniyomiorg/aniyomi-extensions#3387]
### Source information

XS anime

### Source language

Arabic

### Steps to reproduce

1- open XS anime
2- no results f

### Expected behavior

Show popular anime 

### Actual behavior

No results found
![Screenshot_2024-11-02-19-10-43-209_xyz jmir tachiyomi mi](https://github.com/user-attachments/assets/b3a6f568-6d23-41d3-9454-1d07dde3a5a9)

### Aniyomi version

0.16.4.3

### Android version

Android 14

### Other details

The site has changed its address, and I cannot edit it and put the new correct link. I hope to solve the problem.
There are many Arabic sources with the same problem. The site links have changed, but the links cannot be changed in the add-ons and there is no update on them. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We don't manage that extension anymore
