### ISSUE TITLE
Nova fonte de Animes PT-BR 

### ISSUE THREAD

**Issue by delfreitas** [aniyomiorg/aniyomi-extensions#3388]
### Source name

Animes BR 

### Source link

https://animesbr.tv/

### Source language

Português Brasil - PT-BR

### Other details

![Screenshot_20241107-212412](https://github.com/user-attachments/assets/13ea1b04-2fb3-40ca-8980-f3f8afe8b5ad)
![Screenshot_20241107-213655](https://github.com/user-attachments/assets/98ca4301-aa7b-4a83-bc11-db23ea20924f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/aniyomiorg/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Due to a dmca takedown notice, we will not add piracy sites to our repo.

**Comment by delfreitas** [comment]
> Due to a dmca takedown notice, we will not add piracy sites to our repo.

Sorry, I confused this website with an official application that I use, and which is legal, after I went to see that the application does not have a website, only the app itself, thank you
