### ISSUE TITLE
Video list is empty

### ISSUE THREAD

**Issue by MrUchiha** [aniyomiorg/aniyomi-extensions#3393]
### Source information

AllAnime 14.32

### Source language

English

### Steps to reproduce

1. I open Dan Da Dan season 1 
2. Try to watch episode 9
3. And the error pops up saying (
![Screenshot_2024-12-07-17-45-35-432_xyz jmir tachiyomi mi](https://github.com/user-attachments/assets/65ef7eab-baab-4b8d-bf38-131a5f609c5c)
video list is empty) 
![Screenshot_2024-12-07-17-46-36-290_xyz jmir tachiyomi mi](https://github.com/user-attachments/assets/dc068a18-fee8-4758-95c9-6e9db7d40be1)

### Expected behavior

Video should work properly without error

### Actual behavior

Instead some error came (video list is empty) 

### Aniyomi version

0.16.4.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We do not manage that extension anymore, it was removed from our repo due to a DMCA notice.
