### ISSUE TITLE
Video list is empty error

### ISSUE THREAD

**Issue by Reign-Heart** [aniyomiorg/aniyomi-extensions#3395]
### Source information

Hianime latest ver

### Source language

English 

### Steps to reproduce

First select any anime in hianime or similar extension 
Second try to play an episode

### Expected behavior

It should play the episode

### Actual behavior

It shows  video list is empty 

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Other details

Samsung galaxy s6 lite 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We do not manage that extension anymore, it was removed from our repo due to a DMCA notice.

**Comment by Reign-Heart** [comment]
Ok
