### ISSUE TITLE
Asura Scan NullPointerException: Null

### ISSUE THREAD

**Issue by Shikio3** [aniyomiorg/aniyomi-extensions#3396]
### Source information

Asura Scans EN 1.4.42

### Source language

English

### Steps to reproduce

Open any of the following:
    - I Obtained a Mythic Item
    - Pick Me Up, Infinite Gacha
    - Reincarnation of the Suicidal Battle God
    - Return Of The Shattered Constellation
    - Return of the Disaster-Class Hero
    - Solo Leveling: Ragnarok
    - Your Talent is Mine
   Try refreshing or loading and it will cycle and refresh the title picture and get a NullPointerException: Null

### Expected behavior

Open the saved title, refresh to see if a new chapter is out.

### Actual behavior

No new load and can't open old chapter.

### Aniyomi version

Stable 0.16.4.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We don't manage manga extensions here.
