### ISSUE TITLE
Error in Hitomi extension

### ISSUE THREAD

**Issue by LeoneLDVA** [aniyomiorg/aniyomi-extensions#3400]
### Source information

Hitomi 1.4.33

### Source language

Spanish

### Steps to reproduce

_1.Open Hitomi
2.Go to "Recents" or "Filter" and also the search engine._

### Expected behavior

I was just hoping it would work as usual.

### Actual behavior

![Screenshot_20241217-130528_Aniyomi](https://github.com/user-attachments/assets/b7e62f54-ef12-4ac0-a4e5-475ce5d4598c)

### Aniyomi version

0.16.4.3-8019

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
That extension isn't managed here.

**Comment by LeoneLDVA** [comment]
> Esa extensión no se gestiona aquí.

_Where is it managed?__

**Comment by Secozzi** [comment]
> Where is it managed?

Not here.

**Comment by LeoneLDVA** [comment]
> > Where is it managed?
> 
> Not here.

So, where do I have to go to be managed?

**Comment by Secozzi** [comment]
> So, where do I have to go to be managed?

To where you got it from. We have never managed manga extensions so you didn't get it from here.

**Comment by LeoneLDVA** [comment]
> > So, where do I have to go to be managed?
> 
> To where you got it from. We have never managed manga extensions so you didn't get it from here.

I'm sorry, I didn't quite understand the question. Can you explain it to me in a better way?

**Comment by Secozzi** [comment]
This is repo is for anime extensions. You created an issue for a manga extension, which isnt managed here. You created an issue in the wrong place.

**Comment by LeoneLDVA** [comment]
> This is repo is for anime extensions. You created an issue for a manga extension, which isnt managed here. You created an issue in the wrong place.

But this manga extension issue can be fixed as if it were the anime extension issue?

**Comment by Secozzi** [comment]
> But this manga extension issue can be fixed as if it were the anime extension issue?

It must be reported to the right place. There is nothing we can do about a broken **manga** extension.

**Comment by LeoneLDVA** [comment]
> > But this manga extension issue can be fixed as if it were the anime extension issue?
> 
> It must be reported to the right place. There is nothing we can do about a broken **manga** extension.

So, where can I report this problem?

**Comment by Secozzi** [comment]
I don't know how many times I need to say this, wherever the extension is being maintained. We don't manage nor have we ever managed manga extensions, this is not the place for it.
