### ISSUE TITLE
HiAnime Issue

### ISSUE THREAD

**Issue by ZachariasDa1st** [aniyomiorg/aniyomi-extensions#3401]
### Source information

HiAnime 14.44 

### Source language

English

### Steps to reproduce

1. Browse
2. Open HiAnime extension 
3. Click on any anime & load up any episode

### Expected behavior

Episode should play 

### Actual behavior

An error message, "Video list is empty", is displayed

### Aniyomi version

Stable 0.16.4.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We do not manage that extension anymore, it was removed from our repo due to a DMCA notice.
