### ISSUE TITLE
Change the link to extension anime4up

### ISSUE THREAD

**Issue by aggreyas** [aniyomiorg/aniyomi-extensions#3403]
### Source information

anime4up 14.56

### Source language

Arabic

### Source new URL

https://anime4up.rest/

### Other details

Change the link to the extension anime4up

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
That extension was removed from this repo due to a DMCA notice. We do not manage it anymore.
