### ISSUE TITLE
Feature to change the link manually for the anime extension

### ISSUE THREAD

**Issue by aggreyas** [aniyomiorg/aniyomi-extensions#3404]
### Describe why this should be added

In manga extensions, there is an option in the extension settings to manually change the URL in case the website link changes. I hope this feature is added to anime extensions as well.
![photo_2024-12-20_21-23-16](https://github.com/user-attachments/assets/c350f4bc-dbb2-4cc4-acc7-bfcf96fcb6d2)
![photo_2024-12-20_21-23-04](https://github.com/user-attachments/assets/6626ce63-bd68-471d-86a3-1b6b9eff3d7c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open (or closed) issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Most extensions were removed due to a DMCA notice. We do not manage them anymore.
