### ISSUE TITLE
[Feature Request] <Animixplay and GoGo anime>: <Request to add default auto quality>

### ISSUE THREAD

**Issue by Entyipo** [aniyomiorg/aniyomi-extensions#367]
A default auto quality option should be added to the extensions Animixplay and GoGo anime.
It would help in case your internet speed fluctuates and you have to select the auto option Evey single time.

**Comment by Spikebinger99** [comment]
This ruined the Quality option for gogoanime its was the only app that plays videos smoothly until this request came by now there is no option plus you have to watch the video in buffer have to wait for the video to play cause of the buffer thanks to your request

**Comment by Entyipo** [comment]
I missed the part where that's my problem

**Comment by Secozzi** [comment]
Closed as this issue should be made to the main app repo, not the extensions repo.
