### ISSUE TITLE
[Source Request] <Mavanimes>

### ISSUE THREAD

**Issue by MXC48-zz** [aniyomiorg/aniyomi-extensions#371]
## Source website
- Name: Mavanimes
- Link: https://mavanimes.co/
- Language(s): french

## Other details
This is a site with a lot of choice and it would be nice if it was added 😁
Especially since for the moment there is only one source of anime in French.

**Comment by Musashi213** [comment]
I agree I hope someone add it

**Comment by leopoldhub** [comment]
Same, I will look for it if i have some time
