### ISSUE TITLE
[Bug] <9anime>: <Error 404>

### ISSUE THREAD

**Issue by Not-Naruto** [aniyomiorg/aniyomi-extensions#384]
## Device information
- Tachiyomi version: Stable 0.12.3.6
- Android version: 12

## Source information
- Name: 9anime
- Extension version: 12.2

## Steps to reproduce
1. Open a Video
2. It plays perfectly for a short while and then gives me an error

### Expected behavior
The video plays without problems

### Actual behavior
The video stops, and i get the message "Error 404"

**Comment by cENOUR** [comment]
I have the same issue, except it doesn't even start to play

**Comment by Claude-Kenni** [comment]
I have the same issue but it doesn't have a video even if it is short duration like you mentioned.

**Comment by cENOUR** [comment]
One thing I noted is that at least for me, it works fine when using mobile data

**Comment by Samfun75** [comment]
Closing as this not reproducible on latest versions of app and extension
