### ISSUE TITLE
[Bug] animixplay: pausing restarts download

### ISSUE THREAD

**Issue by KraXen72** [aniyomiorg/aniyomi-extensions#391]
## Device information
- Tachiyomi version: latest preview
- Android version: 11

## Source information
- Name: animixplay
- Extension version: 12.8

## Steps to reproduce
1. start downloading an episode
2. pause
3. resume
4. it's back at the beginning

### Expected behavior
semi downloaded episode will continue where it left off

### Actual behavior
semi downloaded episode gets reset and starts downloading from the start

**Comment by Secozzi** [comment]
Closed as the extension mentioned in the issue no longer exists.
