### ISSUE TITLE
[Feature Request] animeworld: add an alternative "episode source"  

### ISSUE THREAD

**Issue by Palloxin** [aniyomiorg/aniyomi-extensions#446]
## What feature should be added to this source?
Explain why this should be added
Add an alternative "episode source".
the extension Animeworld.tv gets his episodes from a download button that brings to another siteweb called "dood". in case the site is down i would like the extension to switch "episode source" automatically to the alternative one.
episodes of the website animeworld.tv has 5 download buttons (different sources) so i would like an alternative source where the extension gets episodes.

![160860942-083553db-686f-4a36-a1f7-20b0aedfb6fe](https://user-images.githubusercontent.com/75091899/160894101-f8a170dd-2077-460d-bb42-73f842be0830.png)

the reason i am suggestion this is that today the button circled by the blue color (the image above) didn't work for a few hours and the extension gets its links from that site.

**Comment by ahmedgamal17** [comment]
The problem some of these links I couldn't extract the video Link from it so I can't add them but the direct one I can add it

**Comment by Palloxin** [comment]
> The problem some of these links I couldn't extract the video Link from it so I can't add them but the direct one I can add it

@ahmedgamal17 
![IMG_20220330_193701](https://user-images.githubusercontent.com/75091899/160897057-e584e38c-b547-4629-ac3c-67f1f7cb3700.jpg)
this button has a direct video on it
