### ISSUE TITLE
[Source Request] <Anime iat>

### ISSUE THREAD

**Issue by Akashi123-deep** [aniyomiorg/aniyomi-extensions#471]
New source for anime
Name : anime iat
Link site : https://www.animeiat.tv/
Language : Arabic 
![Screenshot_20220409-012716_Chrome](https://user-images.githubusercontent.com/102795903/162551534-0d7165bf-0ace-4ea8-a17f-f847d36adfd5.jpg)

**Comment by Secozzi** [comment]
Duplicate of #344
