### ISSUE TITLE
[Source Request] Animekisa.tv

### ISSUE THREAD

**Issue by Retr0-15** [aniyomiorg/aniyomi-extensions#490]
## Source website
- Name: Animekisa
- Link: https://animekisa.tv/
- Language(s): English

## Other details
The animekisa that is already available as an extension does not have the latest anime and I think that it isn't the original Animekisa. So I hope you'll change the website to the original Animekisa which is Animekisa.tv

**Comment by Samfun75** [comment]
Duplicate of #45
