### ISSUE TITLE
[Issue] Gogoanime Latest

### ISSUE THREAD

**Issue by antocs** [aniyomiorg/aniyomi-extensions#493]
## Device information
* Tachiyomi version: Stable 0.12.3.6
* Android version: 12
* Device: Samsung Galaxy S10

## Source information
* Source name: Gogoanime
* Source extension version: 12.35

## Steps to reproduce
1. Tap "latest" on Gogoanime from "Source" tab

## Issue/Request
It doesn't show the latest added stuff (home page browser), but most popular ongoing.

## Other details
Latest from Aniyomi:
![Screenshot_20220412-202544_Aniyomi](https://user-images.githubusercontent.com/22413659/163028921-4ed22cff-6463-43a5-985a-5b9f30c98eb2.jpg)
Latest from homepage (browser, webview):
![Screenshot_20220412-202553_Aniyomi](https://user-images.githubusercontent.com/22413659/163028925-25e6e180-45f1-4216-a800-7bbf59086827.jpg)
Most popular ongoing:
![Screenshot_20220412-202558_Aniyomi](https://user-images.githubusercontent.com/22413659/163028929-fc5e67fe-3ddb-40d6-8499-33f3641a75dd.jpg)

**Comment by Secozzi** [comment]
Closed as this issue is no longer relevant.
