### ISSUE TITLE
[Bug] <oploverz>: <siye blocked>

### ISSUE THREAD

**Issue by bigbabyboost** [aniyomiorg/aniyomi-extensions#521]
## Device information
- Tachiyomi version: App version: 0.12.3.6-4761 (standard, c097e565d, 78, 2022-04-21T11:24Z)
Android version: 12 (SDK 32)
Android build ID: SP2A.220405.004
Device brand: google
Device manufacturer: Google
Device name: blueline
Device model: Pixel 3
Device product name: aosp_blueline

## Source information
- Name: oploverz
- Extension version: latest

## Steps to reproduce
1. Install oploverz ext
2. Browse

### Expected behavior
Site open normally

### Actual behavior
Site got blocked in my country

## Other details
Pls change oploverz.fan to oploverz.asia since old domain got blocked in my country

**Comment by Secozzi** [comment]
Closed as this issue is mostly likely not relevant. If you still have problems, please create a new issue.
