### ISSUE TITLE
[Feature Request] Filler episodes indicator

### ISSUE THREAD

**Issue by Nbee077** [aniyomiorg/aniyomi-extensions#524]
Adding a filler indicator next to the episode number/title would be a great feature, the metadata could be found in the following sites:

- https://www.fandom.com/
- https://animefillerlist.com/

**Comment by BhaturaGuy** [comment]
I second this

**Comment by Secozzi** [comment]
Closing as this feature should be handled through the main app, not the extensions. Please create an issue on the [main app](https://github.com/aniyomiorg/aniyomi/issues) instead.
