### ISSUE TITLE
[Source Request] Multi sources

### ISSUE THREAD

**Issue by Nbee077** [aniyomiorg/aniyomi-extensions#525]
**Anime related sites:**

- Name: Okanime
Link: https://okanime.tv
Language: Arabic / العربية 

- Name: Shahiid Anime
Link: https://shahiid-anime.net/
Language: Arabic / العربية 

- Name: شبكة كونان العربية
Link: https://detectiveconanar.com/
Language: Arabic / العربية 
Note: It has everything related to Case Closed (Ova, Movies, etc)

- Name: Animeiat أنميات
Link: https://www.animeiat.tv/
Language: Arabic / العربية 

- Name: Anime Titans
Link: https://animetitans.com
Language: Arabic / العربية 
Note: Good alternative of Animeiat 

- Name: Anime Silver
Link: https://www.animesilver.com
Language: Arabic / العربية 
Note: Decent alternative of Animeiat 

**Manga related sites:**

- Name: 3asq العاشق
Link: https://3asq.org/
Language: Arabic / العربية

**Comment by Secozzi** [comment]
Closing as multiple source requests were made. Please make a separate issue for each extension.
