### ISSUE TITLE
[Feature Request] Casting episodes to tv/streaming stick

### ISSUE THREAD

**Issue by ThunderWolf19** [aniyomiorg/aniyomi-extensions#527]
## What feature should be added to this source:

**_Casting_**
This would be a very useful feature and would make user experience much more engaging and frequent. At the moment the only way you can cast from the app is to install MX Player and hope the casting works, I love introducing my elderly mother to various Animes and I try to cast episodes to the Chromecast connected to the TV, but it can be awkward to achieve. Adding this feature, I believe, would be very beneficial to user experience.

**Comment by Secozzi** [comment]
Closed as this issue should made to the main aniyomi app repo, not the extensions repo.
