### ISSUE TITLE
[Source Request] RajaHentai.xyz

### ISSUE THREAD

**Issue by HikariHeaven** [aniyomiorg/aniyomi-extensions#530]
## Source website
- Name: RajaHentai
- Link: rajahentai.xyz
- Language(s): Indonesia

## Other details
This is a web streaming hentai anime(18+) with indonesian subtitle

**Comment by Start38** [comment]
@jmir1

**Comment by Start38** [comment]
when will this extension be added

**Comment by Secozzi** [comment]
> when will this extension be added

No eta on when extension requests will be fulfilled.

**Comment by Start38** [comment]
> > kapan ekstensi ini akan ditambahkan
> 
> Tidak ada kepastian kapan permintaan ekstensi akan dipenuhi.

🙁

**Comment by Start38** [comment]
> > kapan ekstensi ini akan ditambahkan
> 
> Tidak ada kepastian kapan permintaan ekstensi akan dipenuhi.

Can you add the Anoboy extension

**Comment by Secozzi** [comment]
There's already an [open request](https://github.com/aniyomiorg/aniyomi-extensions/issues/76) for Anoboy, just wait patiently until someone is willing to make an extension for it

**Comment by Start38** [comment]
> Sudah ada [permintaan terbuka](https://github.com/aniyomiorg/aniyomi-extensions/issues/76) untuk Anoboy, tunggu saja dengan sabar sampai ada yang mau melakukan perpanjangan untuk itu

Looks like nothing will be added😥

**Comment by Start38** [comment]
> There's already an [open request](https://github.com/aniyomiorg/aniyomi-extensions/issues/76) for Anoboy, just wait patiently until someone is willing to make an extension for it

Extension request from 2021

**Comment by kitsu2** [comment]
https://rajahentai.xyz
