### ISSUE TITLE
[Bug] <Source Name>: <short description>

### ISSUE THREAD

**Issue by Cxnstantine** [aniyomiorg/aniyomi-extensions#550]
## Device information
App version: 0.12.3.6 (standard, 67c506d, 72, 2022-01-06T02:47Z)
Android version: 10 (SDK 29)
Android build ID: VOG-L29 10.1.0.150(C431E19R2P5)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWVOG
Device model: VOG-L29
Device product name: VOG-L29EEA 

## Source information
- Name: 9anime
- Extension version: 12.4

## Steps to reproduce
1. I search for any anime, find them and click on play. 
2. The video player appears to be loading and then I get an 404 error every time. 

I have tried restarting the app, clear the app's cache and even reinstalling the app as well as all my extensions including the 9anime extension. I have also tried restarting my device and formating the cache partition. Other extensions work fine. I live in Greece and the 9anime website isn't banned in my country so it's not a VPN issue I guess. Normally I have waited before posting this, I actually found out about Aniyomi from a friend a month ago and installed the 9anime extension as well as others then but the 9anime extension never worked.

**Comment by Samfun75** [comment]
Closing as this not reproducible on latest versions of app and extension
