### ISSUE TITLE
[Source Request] <TVshows88>

### ISSUE THREAD

**Issue by Francisco576** [aniyomiorg/aniyomi-extensions#578]
## Source website
- Name: TVshows88
- Link: https://tvshows88.com
- Language(s): English

## Other details
I know this isn't Anime, but since Tachiyomi has Comics extensions (which aren't Manga), i think Aniyomi could add this extension so we can watch western TV shows and Movies.

**Comment by Secozzi** [comment]
Closed as ther website looks dead. If it ever comes back, please open a new issue,
