### ISSUE TITLE
[Bug] <Anime Saturn>: <changed domain>

### ISSUE THREAD

**Issue by Dome444444** [aniyomiorg/aniyomi-extensions#641]
## Device information
- Tachiyomi version: 0.12.3.7
- Android version: 11

## Source information
- Name: Anime Saturn
- Extension version: 12.5

## Issue
Unable to resolve host "animesaturn.it" : No address associated with hostname

animesaturn.it changed domain to animesaturn.cc

**Comment by Secozzi** [comment]
Closed as this issue is mostly likely not relevant. If you still have problems, please create a new issue.
