### ISSUE TITLE
[Bug] Kuronime : couldn't find any video links. 

### ISSUE THREAD

**Issue by MuhaGX** [aniyomiorg/aniyomi-extensions#650]
## Device information
App version: 0.12.3.7 (standard, 24c1ba6, 72, 2022-07-09T09:48Z)
Android version: 7.1.2 (SDK 25)
Android build ID: NRD90M.G955FXXU1AQJ5
Device brand: samsung
Device manufacturer: samsung
Device name: dream2lte
Device model: SM-G955F
Device product name: dream2ltexx
(Bluestacks Emulator)

- Android version: 7.1.2 (SDK 25)

## Source information
- Name: Kuronime
- Extension version:  12.2

## Other details

https://user-images.githubusercontent.com/70599137/178462968-770f8d52-17a2-4645-9fb3-10473ea0b389.mp4

**Comment by Secozzi** [comment]
Closed as this issue is mostly likely not relevant. If you still have problems, please create a new issue.
