### ISSUE TITLE
[Source Request] <Source Name>

### ISSUE THREAD

**Issue by ihaveaskimask** [aniyomiorg/aniyomi-extensions#655]
## Source website
- Name: Soap2Day
- Link: https://soap2day.ac/ or https://soap2day.do/
- Language(s): English

## Other details
Yes i know this isnt an anime site but i would still like to watch and keep track of some shows in app like The Boys.

The reason I request either the .ac or .do site is because (in my experience) although the .do site is unofficial to my knowledge it's subtitles work far better on mobile than the .ac site, so if it's possible to implement subtitles regardless it's probably better to use https://soap2day.ac/ since it's the official website but if it makes it any easier then yeah, I also apologize if this has already been requested or exists but I couldn't find anything.

**Comment by WindowsRefundDay** [comment]
Vidembed and sflix do same thing as soap2day maybe pack of TV shows

**Comment by Ulysses2333323** [comment]
Can you add extension moviejsoy.to
