### ISSUE TITLE
HURAWATCH

### ISSUE THREAD

**Issue by Sunderlevi** [aniyomiorg/aniyomi-extensions#684]
Please may it happen big fan of your work....
And keep up the good work....

## Source website
- Name: Hurawatch 
- Link: https://hurawatch.it/home
- Language(s): English 

## Other details
All Movies are available And Series Best Website I have ever seen check it out with different language subtitles and many video quality also many other language movies are also available like Spanish, Mexican, Bollywood and etc

**Comment by Secozzi** [comment]
Closed as the website looks dead. If it comes back, please open a new issue.
