### ISSUE TITLE
Zoro.to response 502

### ISSUE THREAD

**Issue by eBoard2** [aniyomiorg/aniyomi-extensions#739]
### Source information and language

Zoro.to 13.9

### Steps to reproduce

Everytime I play a video it shows response 502

### Expected behavior

It should work perfectly 

### Actual behavior

When I try to watch anime on zoro.to it after playing video for 2 to 3 minutes it always get paused and shows Response 502. I've tried everything that I can do so please solve this problem 

### Aniyomi version

0.12.3.7

### Android version

Android 10 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
Closing as this not reproducible on latest versions of app and extension
