### ISSUE TITLE
[Source Request] <Anoboy>

### ISSUE THREAD

**Issue by sumacool** [aniyomiorg/aniyomi-extensions#76]
Hello Admin, I think it's time to add an extension for the indondesian viewers  
So either gomunime or anoboy would be great
## Source website
- Name: anoboy
- Link: https://anoboy.media/
- Language(s): subtitle Indonesia

**Comment by Secozzi** [comment]
New url: https://anoboy.monster/

**Comment by Samfun75** [comment]
https://anoboy.lol/
https://anoboy.live/home/

Putting these here to close other duplicates

**Comment by kitsu2** [comment]
https://anoboy.monster/
