### ISSUE TITLE
[Feature Request] <Sflix, Seriesflix/Pelisflix>: <Subtitles option>

### ISSUE THREAD

**Issue by edmxn** [aniyomiorg/aniyomi-extensions#778]
## What feature should be added to this source?
Subtitles option for Sflix and Seriesflix/Pelisflix, as with zoro.to, work the same way
Sflix is a good source to watch series/movies in their original language with subtitles in different languages
Seriesflix/Pelisflix in the same way, only with this one there are practically only Spanish subtitles

**Comment by miguelantonioe** [comment]
@edmxn Could you comment on some examples of these movies/animes/series?

**Comment by Samfun75** [comment]
Closing as mentioned extensions support subtitles, except Seriesflix/Pelisflix. Open new issue if still relevant
