### ISSUE TITLE
[New Domain] <Gogoanime>: <Gogoanime.ee>

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi-extensions#790]
## What feature should be added to this source?

Gogoanime source has moved to the new domain gogoanime.ee, please add it in the source settings.

**Comment by adly98** [comment]
No worries it redirect to the new domain in the app

**Comment by MF-Debug** [comment]
![Screenshot_20221216-015817_Aniyomi](https://user-images.githubusercontent.com/6173607/207959377-8dc30cc5-c7b9-405d-b9e7-9d677241e45f.png)

none of the attached domains work anymore. these two are the new ones.
gogoanime.tel
gogoanime.ar

**Comment by Secozzi** [comment]
Resolved by #1693
