### ISSUE TITLE
Anime sources don't load, and load extremely slow

### ISSUE THREAD

**Issue by DrekAnon** [aniyomiorg/aniyomi-extensions#801]
### Source information and language

All, zoro.to has a different behavior 

### Steps to reproduce

1. Open the anime section OR an extension
2. Do searches for an anime
3. Most do not come back with any results, zoro.to loads quickly though
4. If I attempt to use Zoro.to it doesn't ever load the video

### Expected behavior

Play the video and show search results.

### Actual behavior

Videos don't load, tells me it can't get links and most extensions don't load anything; can't get search results.

### Aniyomi version

0.12.3.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
Closing as this not reproducible on latest versions of app and extension
