### ISSUE TITLE
Animixplay Videos Problem 

### ISSUE THREAD

**Issue by Solovertical** [aniyomiorg/aniyomi-extensions#809]
### Source information and language

Animixplay 13.13 En

### Steps to reproduce

1: It open Normally
2:When we play Video from the list

### Expected behavior

Video should play Normally as it play before ,and we can select desired quality 

### Actual behavior

It show error on playing video ,it freez 
Reference - Animixplay
TEKKEN Bloodline
![Screenshot_2022-08-27-06-05-47-596_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/109901807/187007558-c3474e69-c508-4b92-bd44-cededabec724.jpg)
![Screenshot_2022-08-27-06-05-55-662_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/109901807/187007562-0226e1c2-dc3b-434a-9e3c-c67536960529.jpg)

### Aniyomi version

Stable 0.13.5

### Android version

10

### Other details

Please Take your time to fix this, I don't think any extensions had this quality videos until now. We can easily download any video which some extensions doesn't provide.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closed as the extension in the issue no longer exists.
