### ISSUE TITLE
Two special arabic site 

### ISSUE THREAD

**Issue by wael-ouni** [aniyomiorg/aniyomi-extensions#814]
### Source name

laughtalear and detectiveconanar

### Source link

https://laughtalear.com/          https://detectiveconanar.com/watch/

### Language

Arabic

### Other details

The two site are special arabic anime site 
The first one:
https://laughtalear.com/
For one piece ep/movie/ova/filler
The second one:
https://detectiveconanar.com/watch/
For detective Conan ep/movies/ova/filler/special movie ep
The two site have the best arabic translate for the both works 
![Screenshot_20220828-211303](https://user-images.githubusercontent.com/111122017/187092849-7c7051af-e7fa-4aeb-ae65-edc47b4cf9eb.jpg)
![Screenshot_20220828-211203](https://user-images.githubusercontent.com/111122017/187092826-dd44babf-9438-4bf2-ae11-3a4233d30c72.jpg)
![Screenshot_20220828-211224](https://user-images.githubusercontent.com/111122017/187092831-fd4e91c8-60ab-4471-b0fe-ff1ef0de3b53.jpg)
![Screenshot_20220828-211151](https://user-images.githubusercontent.com/111122017/187092839-493c17ca-0a94-4be9-981f-2ac70403fa5d.jpg)
![Screenshot_20220828-211143](https://user-images.githubusercontent.com/111122017/187092842-0568f1e6-5cfc-430d-bdd8-b5ea1afb969a.jpg)
![Screenshot_20220828-211244](https://user-images.githubusercontent.com/111122017/187092845-08c2be95-9da9-4521-9c46-a66e6eb1f827.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.jmir.xyz/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closed as multiple source requests were made. Please make a separate issue for each extension.
