### ISSUE TITLE
 AnimesUp

### ISSUE THREAD

**Issue by Orionv1** [aniyomiorg/aniyomi-extensions#848]
### Source name

Animesup

### Source link

https://animesup.biz/

### Language

Portuguese

### Other details

![Screenshot_20220907-130335_Samsung Internet](https://user-images.githubusercontent.com/112901704/188926138-67a9867f-6c7b-4be2-98a0-43f73e53e552.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.jmir.xyz/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closed as the website has died. If it ever comes back, please open up a new issue.
