### ISSUE TITLE
[Feature Request] <Zoro.to>: <Seperate search results by sub and dub>

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi-extensions#890]
## What feature should be added to this source?
Ability to show seperate the search results of an Anime search in Zoro.to extension. 

##Explain why this should be added?
Currently, when an Anime is searched on Zoro.to extension, a single result shows up, in which users have to select whether to play to sub or dub version from the video quality selector inside the player. This also causes an issue when trying to download an episode, where users aren't able to select whether to download it in sub or dub version.

**Comment by Claudemirovsky** [comment]
Your problem can be solved by opening the ZORO.TO extension settings and selecting a video quality, language (sub/dub) and sub language. IF there is a video with these characteristics in the list, it will be selected automatically for watching or downloading.
(Browse > Anime Extensions > Zoro.to > Settings > English)

Following your feature request to the letter, the extension already has a language (sub/dub/sub&dub) search filter, just like the site.

**Comment by YouSummoner** [comment]
> Your problem can be solved by opening the ZORO.TO extension settings and selecting a video quality, language (sub/dub) and sub language. IF there is a video with these characteristics in the list, it will be selected automatically for watching or downloading.
> (Browse > Anime Extensions > Zoro.to > Settings > English)
> 
> Following your feature request to the letter, the extension already has a language (sub/dub/sub&dub) search filter, just like the site. 

I mean showing sub/dub as separate in the search results itself.

**Comment by Samfun75** [comment]
This is not possible as the source doesn't provide separate sub/dub results for search.
