### ISSUE TITLE
add new extensions for Ru community 

### ISSUE THREAD

**Issue by MM001-r** [aniyomiorg/aniyomi-extensions#902]
### Source name

yummyanime; animego; jut.su; amedia; animedub; shikimori

### Source link

https://yummyanime.club https://animego.org https://jut.su https://amedia.online https://animedub.ru https://shikimori.one

### Language

Русский

### Other details

Hi guys, please add to your application extensions of Russian sites, thanks for making such good programs.

Here are examples of sites:
https://yummyanime.club
https://animego.org
https://jut.su
https://amedia.online
https://animedub.ru
https://shikimori.one
Animevost
Animebest
HDrezka
like all the main ones named, I hope for you. thanks in advance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.jmir.xyz/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closed as multiple source requests were made. Please make a separate issue for each extension.
