### ISSUE TITLE
[Source Request] 123Movies

### ISSUE THREAD

**Issue by KRenix1** [aniyomiorg/aniyomi-extensions#924]
### Source name

123Movies

### Source link

https://123movies.tw/

### Language

English

### Other details

A free torrent website for movies with a variety of choices. It has some that other sources do not have as well. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.jmir.xyz/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
Closing as site is blank
