### ISSUE TITLE
AnimeTitans keep stopping Aniyomi

### ISSUE THREAD

**Issue by euijoonyeo** [aniyomiorg/aniyomi-extensions#959]
### Source information and language

"Animetitans 13.1 (Arabic)"

### Steps to reproduce

1- I installed AnimeTitans extension and launched it 
2- the list of Animes is showing normally
3- when I try to run an episode the app stopped 
4- If I try to run an episode another time, Aniyomi stopped immediately 

### Expected behavior

"the episodes running normally"

### Actual behavior

" the episodes doesn't running and stopping Aniyomi"

### Aniyomi version

"0.12.3.8"

### Android version

Android 7.0

### Other details

I tried with another phones with Android version 11 and the episodes running normally, I think AnimeTitans is not compatible with Android version 7.0
![Uploading Screenshot_20221019-183053.png…]()

Uploading mobizen_20221019_184958.mp4…

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Closed as this issue is mostly likely not relevant. If you still have problems, please create a new issue.
