### ISSUE TITLE
[Feature Request] 9anime: Domain need updates again. How about option to add custom domain. 

### ISSUE THREAD

**Issue by Abhinav1217** [aniyomiorg/aniyomi-extensions#971]
## What feature should be added to this source?
9Anime domain need to be updated again. 
Currently In India, only working domain is `.gs` which is a newly added one. Even the .me mirror is blocked because now they have option to stream on that domain too.

According to official reddit faq, Only three domains are currently active , and one redirect mirror.

Primary Sites:

-  [https://9anime.gs](https://9anime.gs/home)
-  [https://9anime.pl](https://9anime.pl/home)
-  [https://9anime.to](https://9anime.to/home)

Mirrors:
-  [https://9anime.id/](https://9anime.id/home)

At present, the select option does not show .gs domain which means I can't use this source without a VPN. **And to change a new domain, a new release of extension will be needed**

If you provide an option to add a custom domain (or complete url) then user from specific countries can choose the domain on their own, meaning only time you need to update this extension will be when keys are modified. 

Also it goes without saying that if you decide this route, then a warning to users that they should only use official domains not some crappy clone.

**Comment by Abhishek890** [comment]
#1303
