### ISSUE TITLE
DramaCool and AsianLoad won't download

### ISSUE THREAD

**Issue by Blue32456** [aniyomiorg/aniyomi-extensions#997]
### Source information and language

Dramacool - 13.24 Asianload - 13.18

### Steps to reproduce

1. Choose a video from one of the above extension
2. Select download
3. It never goes above 0% 

### Expected behavior

Videos should download.

### Actual behavior

It doesn't go above zero and doesn't download.

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by 8227846265** [comment]
Experienced the same issue.

Also, linking an older thread here:
- https://github.com/jmir1/aniyomi-extensions/issues/576

**Comment by Secozzi** [comment]
Closed as multiple bug reports were made. Please make a separate issue for each bug, if still applicable.
